### ISSUE TITLE
Problemen bij installeren op een Synology NAS (216+II)

### ISSUE THREAD

**Issue by Jeltel** [xirixiz/dsmr-reader-docker#1]
Ik probeer deze docker op een Synology NAS te installeren. 
Het compose bestand geeft al een fout, want de compose version 3 is niet beschikbaar.

Uiteindelijk via de GUI van Synology twee containers gestart met de settings genoemd in de compose.

Tijdens het starten worden de verschillende commando's uitgevoerd, maar zijn er ook enkele foutmeldingen. Die komen altijd neer op:

`OperationalError: could not translate host name "dsmrdb" to address: Name or service not known`

Nu zie ik geen andere foutmelding. Moet er een host dsmrb gemaakt worden? De postgres container heet dsmrb, zoals de compose aangeeft.

What to do?

**Comment by xirixiz** [comment]
Je hebt de Docker containers gestart zonder de docker-compose file?
Wanneer je dat doet is er geen relatie tussen beide containers.

Ik denk wanneer je het versienummer in de docker-compose file op versie 2 zet, en daarna docker-compose gebruikt, dat alles dan gewoon naar behoren werkt. Laat maar weten of het lukt, succes!

**Comment by Jeltel** [comment]
Ik had de twee containers wel gelinkt, maar dat werkte blijkbaar niet

Het aanpassen naar versie 2 én het toevoegen van privileged: true aan de dsmr container werkt.
Nu heb ik een webinterface. Nu eens kijken of hij ook data ophaalt :)

**Comment by xirixiz** [comment]
Oke, mooi! Ik zal de docker-compose op versie 2 zetten met privileged: true, dan is het wat bruikbaarder voor iedereen :)

**Comment by Jeltel** [comment]
Let op!

Het werkt dus nog niet én priviliged: true zorgt ervoor dat de container root rechten krijgt en schijnbaar overal toegang tot heeft. Dat moet je er wel bij vermelden.

Ik loop zelf vast op de datalogger :(

**Comment by xirixiz** [comment]
Ik gebruik de volgende settings:

- DSMR-versie 2
- /dev/ttyUSB0

Is de P1 kabel die je gebruikt ook actief op het source device?
Wellicht kan je eea checken of de USB poort die je gebruikt ook data geeft op de host zelf.

http://gejanssen.com/howto/Slimme-meter-uitlezen/

**Comment by Jeltel** [comment]
Ik had helemaal geen /dev/ttyUSB0

Er waren nog wat seriele drivers nodig op de Synology NAS: http://jadahl.dscloud.me/drivers.html

Nu mis ik helaas een webinterface. Ach stapje voor stapje ;)

**Comment by xirixiz** [comment]
Mooi! Ik kwam die drivers ook tegen idd.
