### ISSUE TITLE
Permission denied to /var/tmp/gunicorn--dsmr_webinterface.socket

### ISSUE THREAD

**Issue by daansan** [xirixiz/dsmr-reader-docker#102]
When creating a new container based on the docker compose file I run into the problem that I cannot access the web UI. When I access the web UI, this is what I see in the container log:

2020-03-20 15:22:47,031 DEBG 'nginx' stderr output:
2020/03/20 15:22:47 [crit] 203#203: *4 connect() to unix:///var/tmp/gunicorn--dsmr_webinterface.socket failed (13: Permission denied) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://unix:///var/tmp/gunicorn--dsmr_webinterface.socket:/", host: "server:7777"

The access rights to the /var/tmp/gunicorn--dsmr_webinterface.socket are:
srwxrwxr-x

When i issue the command:
chmod o+w /var/tmp/gunicorn--dsmr_webinterface.socket, they of course will be:
srwxrwxrwx

After I do this, I can access the UI successfully, but only until the next reboot of the container because that will reset the access modifiers.

**Comment by xirixiz** [comment]
Hi Daansan,

```
-rw-r--r--    1 root     root             2 Mar 23 23:15 dsmrreader--dsmr_backend.pid
-rw-r--r--    1 root     root             2 Mar 23 23:15 dsmrreader--dsmr_datalogger.pid
-rw-r--r--    1 root     root             3 Mar 23 23:15 gunicorn--dsmr_webinterface.pid
srwxrwxrwx    1 root     root             0 Mar 23 23:15 gunicorn--dsmr_webinterface.socket
```

When I look at my container, I see the security settings are fine. Perhaps you can share your Docker run command or your docker-compose file?

**Comment by daansan** [comment]
Hi Xirixiz,

Of course, my docker compose section below.
I've been expirimenting with numerous options regarding usernames and such but to no avail.

Thanks

  dsmr:
    container_name: dsmr
    image: xirixiz/dsmr-reader-docker:DYNUP-amd64
#    user: "root"
    depends_on:
      - dsmrdb
    networks:
      - dsmr
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmr_backups:/dsmr/backups
    environment:
      - DAEMON_USER=<my user -non root>
      - DAEMON_GROUP=root
      - TZ=${TZ}
      - DSMR_LOGLEVEL=DEBUG
      - DB_HOST=dsmrdb
      - DB_NAME=dsmrreader
      - DB_PORT=5432
      - DB_USER=${DSMR_PG_USER}
      - DB_PASS=${DSMR_PG_PASSWORD}
      - DSMR_USER=${DSMR_USERNAME}
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=${DSMR_PASSWORD}
      - VIRTUAL_HOST=localhost
      - ENABLE_HTTP_AUTH=false
      - SD_LOGLEVEL=debug
      - SD_AUTOSTART_BACKEND=true
      - SD_AUTORESTART_BACKEND=true
      - SD_USER=root
      - SD_GROUP=root
      - SD_AUTOSTART_DATALOGGER=false
      - SD_AUTORESTART_DATALOGGER=false
      - SD_AUTOSTART_MQTT=false
      - SD_AUTORESTART_MQTT=false
    ports:
      - 7777:80
      - 7779:443

**Comment by xirixiz** [comment]
Could you try and reacreate a container without the following env vars? Just to check?

```
  - DAEMON_USER=<my user -non root>
  - DAEMON_GROUP=root
  - SD_USER=root
  - SD_GROUP=root
```

**Comment by xirixiz** [comment]
You could also try the following. I use these as well, but not sure which containers make use of those as I include this in every Docker config :).

```
- PUID=1026
- PGID=100
- UID=1026
- GID=100
```

Where ID is the user you're starting the Docker container with, fe:
```
id
uid=1026(xirixiz) gid=100(users) groups=100(users),101(administrators),1023(http),65536(docker),65537(video)
```

**Comment by daansan** [comment]
Apologies for the delay, i will try this today and report back here.

**Comment by daansan** [comment]
Just gave it a try, now testing with the following docker-compose but to no avail:

  dsmr:
    container_name: dsmr
    image: xirixiz/dsmr-reader-docker:DYNUP-amd64
    user: "root"
    depends_on:
      - dsmrdb
    networks:
      - dsmr
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmr_backups:/dsmr/backups
    environment:
#      - DAEMON_USER=daansan
#      - DAEMON_GROUP=root
      - TZ=${TZ}
      - DSMR_LOGLEVEL=DEBUG
      - DB_HOST=dsmrdb
      - DB_NAME=dsmrreader
      - DB_PORT=5432
      - DB_USER=${DSMR_PG_USER}
      - DB_PASS=${DSMR_PG_PASSWORD}
      - DSMR_USER=${DSMR_USERNAME}
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=${DSMR_PASSWORD}
      - VIRTUAL_HOST=localhost
      - ENABLE_HTTP_AUTH=false
      - SD_LOGLEVEL=debug
      - SD_AUTOSTART_BACKEND=true
      - SD_AUTORESTART_BACKEND=true
#      - SD_USER=root
#      - SD_GROUP=root
      - SD_AUTOSTART_DATALOGGER=false
      - SD_AUTORESTART_DATALOGGER=false
      - SD_AUTOSTART_MQTT=false
      - SD_AUTORESTART_MQTT=false
      - PUID=${PUID}
      - PGID=1000
      - UID=${PUID}
      - GID=1000
    ports:
      - 7777:80
      - 7779:443

The PUID, PGID, UID and GID values are copied from the id command as suggested.

Before testing this I deleted the old container and ran a docker image prune, a docker volume prune and a docker system prune.

My socket file still has the following permissions:
srwxrwxr-x    1 root     root             0 Apr  6 12:24 gunicorn--dsmr_webinterface.socket
Missing the write permission for others.
