### ISSUE TITLE
Import van dagtotalen middels SQL query

### ISSUE THREAD

**Issue by PeterEIER** [xirixiz/dsmr-reader-docker#103]
Bram,
Ik heb van Dennis een aantal queries gekregen om csv (excel) backups weer terug te zetten in de DSMR database, hieronder zo'n query....

_INSERT INTO dsmr_stats_daystatistics(day, electricity1, electricity2, electricity1_returned, electricity2_returned, gas, electricity1_cost, electricity2_cost, gas_cost, total_cost) VALUES('2017-07-16',2.05,0.0,0.0,0.0,0.0,0.33,0.0,0.0,0.33);_

Mijn vraag is alleen hoe pak ik dat aan in Docker? Kan ik dit doen via Portainer en de console in Portainer?? Hulp, tips welkom.

**Comment by PeterEIER** [comment]
Bram het is mij gelukt op "eigenkracht", mbv dit https://stackoverflow.com/questions/34688465/how-do-i-run-a-sql-file-of-inserts-through-docker-run artikel.

Ik sluit het verzoek.

**Comment by xirixiz** [comment]
Oh, hahaha, ten eerste bedankt voor de koffie! Super!

Maar mooi dat het al gelukt is net voordat ik online kwam, volgens mij kan je het beste het volgende gebruiken:

```
docker exec -it <container-name> psql -U <DB_USER> -d <DB_NAME> -f /file.sql
```

**Comment by PeterEIER** [comment]
Geniet er van Bram, jouw docker container is echt een uitkomst waarvoor dank!

CLI commando als dat jij opgeeft heb ik ook gebruikt ;-)

**Comment by xirixiz** [comment]
Thanks! Het is soms lastig om tijd te vinden het te onderhouden, maar reacties als deze stimuleren mij om door te gaan met projecten in de community. Veel plezier met de DSMR Reeader in Docker!
