### ISSUE TITLE
Nog geen 3.8 versie beschikbaar voor Docker?

### ISSUE THREAD

**Issue by niekniek89** [xirixiz/dsmr-reader-docker#108]
Goedemorgen,

Ik heb zojuist binnen Docker "recreate" aangeklikt, en deze word netjes geupdate.
echter word alleen nog versie 3.7 aangeboden als latest, en niet de echte laatste versie (v3.8).
kan het kloppen dat v3.8 nog niet klaar is voor docker? of moet ik hiervoor bij iemand anders zijn?

alvast bedankt.

**Comment by xirixiz** [comment]
Goedemorgen,

Kan je aan geven welke arch en tag je van de Docker image gebruikt? 
Zelf gebruik ik AMD64 latest, en die is versie 3.8.

**Comment by niekniek89** [comment]
Goedemorgen,

onderstaande heb ik kunnen vinden (uit portainer) welke ik gebruik:

Docker image: xirixiz/dsmr-reader-docker:latest
Build | Docker 3.0.11+azure on linux, amd64

zojuist nogmaals een "recreate" gedaan, maar de latest image blijft helaas echt 3.7.

**Comment by xirixiz** [comment]
Heb je een docker pull gedaan voor recreate? Je moet uiteraard eerst de laatste variant van de image ophalen.

**Comment by jghaanstra** [comment]
Volgens mij zijn alleen de DYNUP docker varianten geschikt voor automatische upgrade. Het lukte mij eerder ook niet met tag latest.

**Comment by xirixiz** [comment]
Correct! Anders zijn het statische images met een vastgepinde versie. Dan moet je altijd een docker pull uitvoeren om echt latest op te halen.

**Comment by niekniek89** [comment]
Ik weet niet beter dan dat ik "recreate" gebruik binnen portainer. Zodra ik op "recreate" klik, zet ik het schuifje aan "pull latest image", en heb ik altijd de laatste versie, echter bij deze niet meer.

**Comment by niekniek89** [comment]
Ik zie ook dat alle images 5 dagen geleden zijn aangepast (waarschijnlijk naar 3.8). Alleen bij latest staat 20 dagen geleden... Geen idee of dat er iets mee te maken kan hebben?

![DSMR](https://user-images.githubusercontent.com/48858098/78867422-5e31b400-7a41-11ea-89ae-9418e5192600.PNG)

**Comment by xirixiz** [comment]
I notice there is an issue indeed with this tag... I'll check the Azure DevOps pipeline what went wrong and get back to you.

**Comment by xirixiz** [comment]
Fixed, my bad, messed up the pipeline :D

**Comment by niekniek89** [comment]
haha, geen probleem. top dat het is opgelost!
bedankt voor je support!

**Comment by niekniek89** [comment]
![image](https://user-images.githubusercontent.com/48858098/78871019-58d76800-7a47-11ea-88a3-c616e3864420.png)

is nu wel gelukt!
