### ISSUE TITLE
Foutmelding bij starten dsmr-docker 

### ISSUE THREAD

**Issue by koelkast88** [xirixiz/dsmr-reader-docker#11]
Ik probeer dit pakket met Docker op Ubuntu server aan de gang te krijgen, maar helaas krijg ik een foutmelding.

Nadat ik 'm heb gepulld: docker pull xirixiz/dsmr-reader-docker
Voer ik het volgende commando in: docker-compose start dsmr
Bleek dat ik docker-compose nog moest installeren, prima, gedaan.
Vervolgens dit commando gegeven: docker-compose start dsmr.
Daarna krijg ik een foutmelding:
ERROR: Can't find a suitable configuration file in this directory or any parent. Are you in the right directory? Supported filenames: docker-compose.yml, docker-compose.yaml

Wat doe ik fout? Mis ik iets? Begrijp ik het niet goed?

**Comment by xirixiz** [comment]
Hoi Koelkast,

docker-compose start dsmr gaat idd niet werken.

De docker-compose file bevat meerdere docker images, die hoef je niet te pullen, dat doet docker-compose (schil om docker) voor je.

Ga naar de gekloonde repo dir en voer uit: docker-compose up -d
Je kan de startup dan ook volgen met: docker-compose logs -f

Ik zou zeggen bestudeer de docu even:
https://docs.docker.com/compose/reference/

**Comment by xirixiz** [comment]
Deze repo moet je dus clonen: https://github.com/xirixiz/dsmr-reader-docker

**Comment by koelkast88** [comment]
Ah, dank voor je snelle reply!
Je merkt dat ik niet helemaal thuis ben in Docker en Linux.
Dacht 'even eenvoudig een docker image doen... ' Dat valt dus tegen.

De gekloonde repo dir, hoe vind ik die eigenlijk?

**Comment by xirixiz** [comment]
Oh, geen probleem hoor.

git clone https://github.com/xirixiz/dsmr-reader-docker.git dsmr-reader
cd dsmr-reader
docker-compose up -d
docker-compose logs -f

**Comment by koelkast88** [comment]
Oké! Ik ben weer wat verder. Maar nu krijg ik een andere foutmelding:

ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing th                           is error because you're using the wrong Compose file version. Either specify a v                           ersion of "2" (or "2.0") and place your service definitions under the `services`                            key, or omit the `version` key and place your service definitions at the root o                           f the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compos                           e/compose-file/

**Comment by xirixiz** [comment]
Die had je wel op google kunnen zoeke he....

https://github.com/xirixiz/dsmr-reader-docker/blob/master/docker-compose.yaml openen en versie 3 veranderen naar versie 2.

Succes!

**Comment by koelkast88** [comment]
Super! Dank voor je snelle actie!!!

2018-02-27 10:08 GMT+01:00 Bram van Dartel <notifications@github.com>:
