### ISSUE TITLE
Question: use ip instead of serial device

### ISSUE THREAD

**Issue by zuidwijk** [xirixiz/dsmr-reader-docker#111]
Not an issue, just a question:

Is it possible to either us an ip-adres as device (telnet to a device) or to create a virtual device within the docker container (like socat or ser2net)?

**Comment by xirixiz** [comment]
Unfortunately that's not possible.

**Comment by zuidwijk** [comment]
I see that socat can be ran as a container...: https://hub.docker.com/r/alpine/socat/
This could be interesting if this container could map a ip/telnet to a pseudo tty and forward/link that to the dsmr-reader docker :)

**Comment by xirixiz** [comment]
I looked into this, and I think it might be possible. Maybe I`ll add it in a future release as it shouldn't be hard to implement.

**Comment by zuidwijk** [comment]
Ik hoorde net dat het in de release van 4.1 komt, dus wachten we daar maar even op :) Niet de moeite waard om daar nu nog extra tijd en moeite in te steken lijkt mij 👍
