### ISSUE TITLE
After upgrading to 3.10 (latest) no new telegrams are processed

### ISSUE THREAD

**Issue by pimvullers** [xirixiz/dsmr-reader-docker#113]
After updating to latest image, no new telegrams are processed. 
I first expected it had to do with QNAP firmware upgrade that I combined (and might have messed with the permissions or so), but when entering the running docker, and listening on ttyUSB0 with microcom, I see telegrams. So the telegrams are accessable from withing the container, they are only not recorded/processed by DSMR reader.

**Comment by xirixiz** [comment]
I don't have any issues with the current/latest Docker image. Did you check the dsmr reader logfiles in the Docker container? Maybe your dsmr config isn't valid for some reason, you could also verify that.

**Comment by pimvullers** [comment]
Thanks for this hint. looks like the CRC of the telegrams are no longer accepted :(
Any idea what could cause this?

**Comment by xirixiz** [comment]
Not sure, but I think you can manage this in DSMR Reader itself. Maybe you can open an issue at the DSMR Reader repo.

**Comment by pimvullers** [comment]
Problem resolved: https://github.com/dennissiemensma/dsmr-reader/issues/1008
Thanks for providing the docker images, definitely eased the installation on my NAS.
