### ISSUE TITLE
MQTT not starting

### ISSUE THREAD

**Issue by nhe050** [xirixiz/dsmr-reader-docker#115]
Hi, I’m pretty new to DSMR and DSMR-reader so I might be missing something, but it seems like the MQTT client is not running in the container.
I recently pulled the latest image version and now the dsmr container runs with below configuration. For testing I enabled publishing the raw messages to MQTT. This quickly resulted in 200 queued messages in DSMR-reader but no traffic at all on my MQTT broker. I checked inside the container and there’s no pid file for the mqtt process. So I’m assuming it’s not being started or start fails.
Am I missing something? Any help would be appreciated.

Note: The data logger is running on a separate Pi and is delivering the telegrams to the api just fine.

Docker-compose config:
```dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/docker-data/dsmr/dsmr_backups:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - SD_AUTOSTART_MQTT=true
      - SD_AUTORESTART_MQTT=true
      - SD_AUTOSTART_DATALOGGER=false
      - SD_AUTORESTART_DATALOGGER=false
    ports:
      - 7777:80
      - 7779:443

**Comment by xirixiz** [comment]
Hi, can you please provide the logfiles of DSMR Reader? You can find the locations in README.MD in this repository.

**Comment by xirixiz** [comment]
Als can you see supervisord starting mqtt: `docker logs -f <container id/name>`

**Comment by nhe050** [comment]
Thanks for your response. I checked the logs and saw several modules being started, but no mention of mqtt. Several restarts of the container made no difference. Therefore I forced docker-compose to recreate the container to be sure the current config would be properly loaded and that solved it!
