### ISSUE TITLE
RFC voor wijzigingen in DSMR-reader 4.x

### ISSUE THREAD

**Issue by dennissiemensma** [xirixiz/dsmr-reader-docker#116]
Ik ben momenteel bezig met voorbereidingen voor DSMR-reader `4.x`, waarbij er weer de mogelijkheid om backwards incompatible changes te doen. De release is overigens naar verwachting pas over enkele weken.

Dit is de changelog tot nu toe: 
- https://github.com/dennissiemensma/dsmr-reader/blob/wip/v4.0/docs/changelog.rst#v4-0-0-2020-xx-xx

En de upgrade guide tot nu toe is dit:
- https://github.com/dennissiemensma/dsmr-reader/blob/wip/v4.0/docs/faq/v4_upgrade.rst

Voor zover ik kan inschatten zullen dat geen ingrijpende wijzigingen voor de Docker-installaties zijn om mee te nemen.

Echter, mijn vraag hier is of er misschien nog andersom vanuit jou behoefte is aan wijzigingen (t.b.v. Docker) die backwards incompatibility zijn en daarom mee kunnen met zo'n release. 

Zijn er nog zaken waar je recent tegenaan bent gelopen qua config of iets anders?

**Comment by dennissiemensma** [comment]
Ik denk dat ik sowieso nog even alle configs in DSMR-reader (en de overerving ervan) ga versimpelen. 
Ik zal dan dezelfde env vars aanhouden als die nu ook al worden gebruikt en de bovenstaande docs bijwerken.

**Comment by xirixiz** [comment]
Hoi Dennis, mooi dat je het zo goed onderhoud! 

Hoe meer er via environment vars gezet kan worden, des te eenvoudiger het is voor gebruik met Docker. 

**Item 1**
Voor het volgende heb ik nog een hack achtige workaround, al weet ik niet of dat nog van toepassing is:
- DSMRREADER_BACKEND_SLEEP
- DSMR_DATALOGGER_SLEEP

Worden de betreffende waarden nog gebruikt? Zo ja, kunnen die wellicht al worden ingezet als environment variabelen? ...ik kan dat zelf uiteraard ook even nakijken ;).

**Item 2**
Verder wordt er bij het starten van de Docker container altijd een gebruiker aangemaakt indien de opgegeven gebruiker niet bestaat. Wellicht dat dit vereenvoudigd kan worden.

```
function _run_post_config() {
  _info "Running post configuration..."
  cmd=$(command -v python3)
  "${cmd}" manage.py migrate --noinput
  "${cmd}" manage.py collectstatic --noinput
"${cmd}" manage.py shell -i python << PYTHON
from django.contrib.auth.models import User
if not User.objects.filter(username='${DSMR_USER}'):
  User.objects.create_superuser('${DSMR_USER}', '${DSMR_EMAIL}', '${DSMR_PASSWORD}')
  print('${DSMR_USER} created')
else:
  print('${DSMR_USER} already exists')
PYTHON
}
```

**Item 3**
Wellicht kunnen we Docker in de toekomst integreren zodat "alles" netjes bij elkaar staat en wijzigingen via PR's gedaan kunnen worden. Ik kan wel een fork maken wanneer 4.x uit is, de Docker code professionaliseren, en een PR maken. Wanneer er dan issues mochten zijn met de Docker release, dan blijf ik uiteraard beschikbaar voor ondersteuning en code wijzigingen. Mocht je dat zien zitten, dan hoor ik het graag.

**Comment by dennissiemensma** [comment]
Bedankt voor de input! Hier kan ik wat mee.

## Item 1
```
    DSMRREADER_BACKEND_SLEEP
    DSMR_DATALOGGER_SLEEP
```

Deze worden sinds v2.14 al niet meer gebruikt: https://dsmr-reader.readthedocs.io/en/latest/settings.html

Dus die kun kun je uitfaseren.

----

## Item 2
Mee eens, dus bij deze voor de v4-release een apart command ervoor gemaakt: https://github.com/dennissiemensma/dsmr-reader/commit/fa57c62f1faf74b9787ac2302cbcf2741e0ca86c

Je hoeft dan straks alleen `./manage.py dsmr_superuser` uit te voeren. 

Hij maakt de user dan aan op basis van de envvars:
- `DSMR_USER`
- `DSMR_PASSWORD`

Het e-mailadres heb ik maar gedefault naar username@localhost, gezien er toch geen functionaliteit gekoppeld is aan het e-mailadres van de gebruiker.

Als de gebruiker al bestaat, dan werkt `./manage.py dsmr_superuser` het wachtwoord van de gebruiker bij. 

Dus het script forceert simpelweg dat die gebruiker bestaat met dat wachtwoord.

----

## Item 3
Dat lijkt me erg mooi! Ik had een tijdje geleden al besloten om `dsmrreader` uiteindelijk te verplaatsen naar een aparte 'open-source' organisatie, die ik al heb aangemaakt: https://github.com/dsmrreader. 
Alleen wacht dat op het daadwerkelijke uitvoeren en ik zie daar wat tegenop, omdat het vanzelfsprekend een shitload aan referenties aanpassen wordt overal. Dit ondanks dat Github zelf het redirecten van zowel de repo in web als in Git goed lijkt te redirecten (na een test).

Mocht ik het toch daadwerkelijk uitgevoerd krijgen, dan kun je overwegen om je eigen repo hier ook onder te brengen zodat het wat meer bij elkaar staat. En dan kan ik je ook gewoon toevoegen als auteur/collaborator aan de organisatie.

**Comment by dennissiemensma** [comment]
Nogmaals bedankt voor de input. Ik zal tzt kijken of ik voor de eerste twee items later een aanzet kan maken via een PR, wanneer de release dichterbij komt.

**Comment by dennissiemensma** [comment]
Ik heb overigens in een aparte branch al een opzet gemaakt: https://github.com/xirixiz/dsmr-reader-docker/compare/master...dennissiemensma:wip/dsmrreader-v4

Wanneer dat zover is zal ik het je voorleggen als PR zodat je het ook even lokaal kunt testen en eventueel tzt aanvullen.

**Comment by xirixiz** [comment]
Hoi Dennis, ik ben even weg geweest maar inmiddels weer terug :).

Bedankt voor de heledere terugkoppeling, daar kan ik iets mee! En inderdaad, laat het maar weten wanneer je zover bent, dan ga ik het in Docker testen. Ik wil daar tzt ook wat meer automation/testing omheen bouwen, maar daar moet ik induiken. Ik kom meer uit de beheerhoek, dan uiteen ontwikkel hoek...  Maar goed, leren is altijd goed ;).

**Comment by dennissiemensma** [comment]
Nog een update.

Inmiddels heb ik ook InfluxDB-integratie voor dezelfde v4.x release staan. Het draaien gaat via de bestaande `dsmr_backend` en het configureren via de admin-interface, dus daar zou geen extra werk in moeten zitten.

Omdat er toch was issues waren met gebruikers die wel of geen MQTT gebruikten en het een persistent proces moest zijn (voor de verbinding), heb ik besloten om het samen te voegen met `dsmr_backend`. Dat betekent dat `dsmr_mqtt` verdwijnt en er (voor nu) ook geen vervanger voor komt.
Als het bij iedereen straks afdoende performt, dan scheelt dit ook weer een hoop extra beheer. 

Ik zal de PR voor Docker er tzt op aanpassen.
