### ISSUE TITLE
Error when restoring database

### ISSUE THREAD

**Issue by JvDaal** [xirixiz/dsmr-reader-docker#117]
I've managed to install DSMR in a docker on my Pi 4. Now I'd like to import a back-up database by using the commands:

docker-compose stop dsmr
docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader
docker exec -t dsmrdb createdb -O dsmrreader dsmrreader -U dsmrreader
cat dsmrreader.sql | docker exec -i dsmrdb psql -U dsmrreader
docker-compose start dsmr

However, the cat command gives me a strange error. See screenshot 2 and 3.

https://flic.kr/p/2jgc6DZ
https://flic.kr/p/2jgc513
https://flic.kr/p/2jgghQT

**Comment by xirixiz** [comment]
Probably because the bacup file is in tar.gz or gz format. Unpack the file first and try again, I think that'll solve the issue. Good luck!

**Comment by JvDaal** [comment]
Solved!
