### ISSUE TITLE
correct url in data logger when using docker on synology ?

### ISSUE THREAD

**Issue by githubnoobjk** [xirixiz/dsmr-reader-docker#119]
In     dsmr_datalogger_api_client.py  I have these lines

`API_SERVERS = (
    # You can add multiple hosts here... just uncomment the line below.
    ('http://10.0.0.31/api/v1/datalogger/dsmrreading', '356ABXX715'),
    # ('http://HOST-OR-IP-2/api/v1/datalogger/dsmrreading', 'APIKEY-2'),`

In my dsmr-reader I don't receive telegrams. The logging on my rapsberry gives this error:

`INFO:root:[2020-07-27 13:02:46.505107] Telegram read
INFO:root:[2020-07-27 13:02:46.508097] Sending telegram to: http://10.0.0.31/api/v1/datalogger/dsmrreading
ERROR:root:[2020-07-27 13:02:46.558862] API error: HTTP 405 - <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
Traceback (most recent call last):
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dsmr/dsmr_datalogger_api_client.py", line 126, in <module>
    main()
  File "/home/dsmr/dsmr_datalogger_api_client.py", line 106, in main
    for telegram in read_serial_port(**SERIAL_SETTINGS):
  File "/home/dsmr/dsmr_datalogger_api_client.py", line 61, in read_serial_port
    data = serial_handle.readline()
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/serial/serialposix.py", line 509, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

`

Now I wonder if the url is correct. 
According to Dennis Siemense the plugin is not needed.
In Synology  I created a user called dsmrreader and in dsmr reader I enabled API-calls and added the API-key

**Comment by dennissiemensma** [comment]
This issue was debugged and solved in dennissiemensma/dsmr-reader/issues/1058, as it was caused by a missing (non standard) port definition in the (DSMR-reader) API host, used by the datalogger script.
