### ISSUE TITLE
Web user interface op andere port dan 8888

### ISSUE THREAD

**Issue by poerlemans** [xirixiz/dsmr-reader-docker#12]
Om te beginnen een groot compliment voor dit werk. Het is met deze docker werkwijze een stuk gemakkelijker geworden om als niet-expert de nodige toepassingen op een linux systeem te installeren.

Vanwege problemen met een andere toepassing wil ik de web user interface op een andere poort dan 8888.
Ik dacht dat een voudig te doen door in de docker-compose.yaml file een ander poortnummer in te geven. Maar zo eenvoudig is het blijkbaar niet, Dit mislukte. Via deze andere poort kan ik de web user interface niet bereiken.
Hoe is dit wel mogelijk??

**Comment by xirixiz** [comment]
Leuk dat je dit project probeert te gebruiken!

Je moet het zo zien dat de Docker image (Dockerfile) luistert op poort 80 en 443. In de docker-compose.yaml file staat slechts een mapping naar die poorten bij het starten van de container.

Wanneer je dus het volgende aan zou passen, dan zou dat gewoon moeten werken:
`    ports:
      - <whatever>:80
      - <another_whatever>:443
`
Voorwaarde is uiteraard wel dat de poorten die je opgeeft niet al in gebruik zijn en dat beide poorten uniek zijn.

**Comment by poerlemans** [comment]
Dat was de oplossing! Bedankt.
Ik had hiervoor nagelaten om eerst de bestaande container te verwijderen, zodat daarna een nieuwe container met aangepaste poortinstellingen kon worden gemaakt.
