### ISSUE TITLE
New meter results in massive consumption and returns

### ISSUE THREAD

**Issue by mrwolf78** [xirixiz/dsmr-reader-docker#120]
A new energy meter was installed yesterday at my house. The graphs during the day look OK, but the archive data seems messed up by this. Is there a way to fix this (or remove the entire day, rather miss a day than a continuous massive difference).

Data:
Wed 29-07: Total consumed 4,56, returned 28.83
Thu 30-07: Total consumed -5,422.75, returned -6,523.91

It almost looks like it somehow did some calculation with the meter totals, they went back to 0 with the new meter obviously. The totals (low and high tariff) seem to match pretty well.

**Comment by dennissiemensma** [comment]
Hi @mrwolf78 this is a known issue and you can adjust the day/hour totals of the invalid day manually:

- https://dsmr-reader.readthedocs.io/en/latest/faq.html#i-ve-changed-to-a-different-smart-meter
- dennissiemensma/dsmr-reader/issues/994
- dennissiemensma/dsmr-reader/issues/666

**Comment by mrwolf78** [comment]
Thanks, I was looking into the hour statistics only. They showed no deviations. The day statistics however, where way off. I now set the entire day to 0.
