### ISSUE TITLE
Segmentation fault - Raspbian RPI3

### ISSUE THREAD

**Issue by Flight777** [xirixiz/dsmr-reader-docker#127]
After the latest apt-get packages update (incl Docker) on Raspbian Buster, I'm not able to run this containter anymore, it immediately errors with "Segmentation fault".

Any idea why this might be happening?

**Comment by xirixiz** [comment]
You really need to provide some more information or share some logfiles :).

Is it only for DSMR reader the segmentation fault? Is the error thrown within the DSMR reader Docker container or is it thrown by Docker, etc, etc.

**Comment by Flight777** [comment]
Sorry, still a bit of a newbie so was panicking ;)

Yes, only the DSMR reader container throws this error (I have few other running).

I have an old "DSMR container" the logs looks like this when I try to start it:

![image](https://user-images.githubusercontent.com/5236143/91709085-8651b900-eb82-11ea-9ec1-1f7a7b0639ac.png)

If I try to create a new container with:

`docker run -d \
  --name dsmr \
  --restart always \
  -p 7777:80 \
  -e DB_HOST=172.17.0.3  \
  -e DB_USER=****\
  -e DB_PASS=****  \
  -e TZ=Europe/Amsterdam  \
  -e VIRTUAL_HOST=localhost \
  -e DSM_RELEASE=latest  \
  -e DSMR_USER=dsmrreader \
  -e DSMR_PASSWORD=**** \
  -e DSMR_EMAIL=root@localhost \
  --device /dev/serial/by-id/usb-FTDI_P1_Converter_Cable_P140BY4H-if00-port0:/dev/ttyUSB0 \
  xirixiz/dsmr-reader-docker:latest`

Docker just throws the "Segmentation Fault" error immediately:

![image](https://user-images.githubusercontent.com/5236143/91709170-a7b2a500-eb82-11ea-8b95-d03bae98381d.png)

**Comment by Flight777** [comment]
PostgreSQL container is running fine btw.

**Comment by xirixiz** [comment]
This looks more like it, thanks! I`ll look into it!

**Comment by xirixiz** [comment]
Ah, DSM_RELEASE=latest .... remove that line

**Comment by Flight777** [comment]
Just tried it immediately, but still the same :(

**Comment by Flight777** [comment]
Any luck, or can I provide any more info to help?

**Comment by Flight777** [comment]
Seems to be an issue with arm32v7 package, I changed to v6 which is working...

**Comment by xirixiz** [comment]
Ok, great, thanks! I was just about to have a look! I`ll fix it the upcoming days as I will deploy an updated release with the possibility to use the Docker image as well for remote datalogger functionality. Did you use the arm32v7 package from the beginning or did you switch earlier from v6 to v7.
