### ISSUE TITLE
Improve the current release strategy

### ISSUE THREAD

**Issue by ju5t** [xirixiz/dsmr-reader-docker#128]
This is my personal opinion but I think the latest approach of installing DSMR during bootup doesn't adhere to what Docker is all about. Packaging up everything and tagging appropriately. 

It shouldn't run full installations when booting up, the power of Docker is to have it all compiled into the image. It feels like we're compiling software back in 1998. It's like installing from `yum/apt` and have it compile software. That's not what should happen. Especially as this means you're depending on both pypi and GitHub to be available.

At first I struggled to get this up and running. The installation failed. There was no logging as to why it did, it just did. Halfway through `pip install`. It tried to run manage.py but failed because it wasn't there. I had to remove the container a few times and rerun it to get it back up. This should not happen, ever. And I think this is where the current strategy is flawed.

In the current strategy you can update versions by setting `DSMR_RELEASE`. This sounds cool, but it comes with all sorts of possible issues. The most important one: dependencies. It's not just `requirements.txt`. Every function in `run.sh` is part of the installation. What if something changes? How do you ensure backwards compatibility? You can't just pin `DSMR_RELEASE` to and assume that the container will work with some of the changes you make. There is a lot that can go wrong.

Can you please revert the last change and have proper tagging set up, preferably in line with the versions DSMR releases? For example: dsmr-reader-docker:4.3.0 should match with DSMR version 4.3.0. This is clean, simple, understandable and similar to how other images are working too. And please tag releases on GitHub too. We're now depending on reverting commits. Tags make your life easy.

This allows for a much cleaner and reliant release strategy where you can easily go between version if required. You can even automate new releases based on the tag.

**Comment by xirixiz** [comment]
I fully agree with you, and thanks for sharing! However tagging, modifying version vars, fixing things and building consumes a lot of time....which I don't have a lot :). The other thing is that I also received a lot of requests to create a Docker image which updates on startup. So, in the past I created a seperate image for this functionality, but it resulted in extra code to maintain and even duplicate code.

So I fully agree but I'm struggling in finding a way to not have duplicate code, make versioning easy and make both static and dynamic Docker images available. Please share you thoughts.

**Comment by ju5t** [comment]
I'm not familiar with Azure pipelines or Github actions and only slightly familiar with Travis, we're using Gitlab. In Gitlab you can run particular commands only on tagged commits. I think in Travis it's: `if: tag IS present`.

Let's say you [tag a commit](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and push it to Github, you would like it to:

- Use this tag, in Travis it's `TRAVIS_TAG`
- Run `docker build`, use the tag as an environment variable.
- Build a container with the tag, `docker tag dsmr-reader-docker:${TRAVIS_TAG}`
- Tag it with latest, too: `docker tag dsmr-reader-docker:latest`
- Push them both with `docker push`.

This is just a small example. You're supporting multiple architectures so you probably have multiple builds that you need to tag, but that's why we have CI. In Travis you could use a matrix to build them on a variety of operating systems and architectures.

You could run a separate set of commands if you're not on a tagged commit. I think you're only using the master branch right now which isn't what I'm used to, but isn't very problematic either. You could tag (don't confuse this with git tag) your Docker containers on the master branch with a suffix/prefix of `edge` for example, allow people to use the latest and greatest, untested version if they want. If people are looking for stability they should use `latest` and if someone wants to pin a specific version and do controlled updates, they can use a specific version. This also allows you to easily revert if a version isn't working.

I haven't tested how this would work in the following situation:

- Current release is 4.3.0, this is tagged in git.
- Next release is 4.3.1. You don't need code changes.

I think you need a new commit that you tag instead of tagging master again. Arguably this should be a commit to the `CHANGELOG`. This will take some time, but not too much.

Updates on startup are stupid and make no sense. It's not what Docker is about. You never know what state you are in. That's why `latest` was 'invented'. The current automated updates are error prone, I don't think everyone realises it. Assuming most people use `docker-compose` these days, adding a cron that runs `docker-compose pull && docker-compose up -d` is all it takes.

**Comment by xirixiz** [comment]
Currently I modified development so a static Docker image is created with version tagging. Could you give it a try?

The tags are like:
```development-<version>-<architecture>```

So for example:
```development-v4.3.0-amd64``
