### ISSUE TITLE
DSMRreader not updating to version 4 (platform Pi4)

### ISSUE THREAD

**Issue by PeterEIER** [xirixiz/dsmr-reader-docker#130]
Upgrade from v3.12 to v4.x.x is not happening. My compose file was working to update v3.x to v3.y etc. Please advise.

**Comment by xirixiz** [comment]
Can you please share your docker-compose file (passwords redacted)?

**Comment by PeterEIER** [comment]
Attached (the password are faked (set to the defaults)).

[compose-yaml.txt](https://github.com/xirixiz/dsmr-reader-docker/files/5230623/compose-yaml.txt)

**Comment by xirixiz** [comment]
@dennissiemensma does PeterEIER needs to execute some manual upgrade steps?

From my point of view pulling release 4 and starting it will execute all required upgrade tasks.

```docker pull xirixiz/dsmr-reader-docker:latest``` and start the container via compose will do the job I suppose

**Comment by dennissiemensma** [comment]
> does PeterEIER needs to execute some manual upgrade steps?

If you applied [all changes](https://dsmr-reader.readthedocs.io/en/latest/faq/v4_upgrade.html) into the v4-Docker release (and I remember you did) then the user should only need to run `./deploy.sh`, on a native installation.

**Comment by xirixiz** [comment]
Nog gelukt?

**Comment by PeterEIER** [comment]
Helaas.
![errors](https://user-images.githubusercontent.com/25422313/94359979-61c9fd80-00aa-11eb-9615-23cc9fdefcec.png)

**Comment by xirixiz** [comment]
Dat hoeft ook inderdaad niet op deze manier in Docker, dat werkt niet op die manier. Virtualenv is sowieso niet geinstalleerd/nodig in Docker, dus daar gaat het dan al op mis. Je kan gewoon de laatste Docker image ophalen en starten, dan moet het goed zijn. Stel voor de zekerheid de db bestanden even veilig, zodat je altijd terug kan, al acht ik die kans zeer klein.

**Comment by PeterEIER** [comment]
Ik heb de latest al.
![is-up-to-date](https://user-images.githubusercontent.com/25422313/94362454-a6aa6000-00bb-11eb-80ce-2c27d0a4f68c.png)

**Comment by xirixiz** [comment]
Dus als ik het goed begrijp zie je in de UI dat je versie 4 draait, maar op DB level dat je op versie 3.12 zit?

**Comment by PeterEIER** [comment]
Docker compose vertelt mij dat er niets te updaten valt... De DSMR reader versie die opgestart wordt in die up-to-date container is versie 3.12.

**Comment by xirixiz** [comment]
``docker-compose pull dsmr``` haalt dus geen nieuwe image binnen?

Kan je de output een delen van ```docker images | grep dsmr```?

**Comment by PeterEIER** [comment]
docker-compose -f <compose-yaml.txt> up -d

En wat er in "compose-yaml.txt" staat heb gedeeld met je aan het begin van dit draadje. De output die ik krijg is dus dit:

![is-up-to-date](https://user-images.githubusercontent.com/25422313/94365320-1b879500-00d0-11eb-87dc-03f2c21e5efd.png)

**Comment by PeterEIER** [comment]
Complete screenshot, from start to end.

![full-log](https://user-images.githubusercontent.com/25422313/94365555-45da5200-00d2-11eb-80ef-fb4267e9aa8c.png)

**Comment by xirixiz** [comment]
Kan je de output van het volgende ook sturen?

```docker images | grep dsmr```

en

```docker ps -a | grep dsmr```

Het lijkt erop dat je steeds op een oude image blijft zitten namelijk. Het design voor de 4.x images is ook veranderd, en ook dat zie ik niet terug. Maar met de bovenstaande output kan ik je vast verder helpen.

**Comment by PeterEIER** [comment]
Zie screenshot.

![grep](https://user-images.githubusercontent.com/25422313/94371984-ae3d2980-00fa-11eb-9716-c61cc5916316.png)

**Comment by xirixiz** [comment]
Ah kijk, daar staat het, 5 weken geleden is de container gemaakt. De container is dus nog aanwezig op basis van een oude docker image. De container even "afbreken" en opnieuw aanmaken zou het moeten oplossen.

**Comment by xirixiz** [comment]
De image is ook oud zie ik....

**Comment by xirixiz** [comment]
De latest tag is ongeveer een maand oud. Ik zou de images even verwijderen zodat docker-compose de image opnieuw ophaalt.

![image](https://user-images.githubusercontent.com/11210639/94372504-77691280-00fe-11eb-986a-690841cf2804.png)

**Comment by PeterEIER** [comment]
Je hebt je een grande cappuccino met een muffin verdient ;-)

![Screenshot 2020-09-27 at 20 43 53](https://user-images.githubusercontent.com/25422313/94372959-4c80bd80-0102-11eb-8568-338039e887c0.png)

**Comment by xirixiz** [comment]
Super! Mooi dat het nu werkt en uiteraard bedankt voor de heerlijke koffie met lekkernij!

**Comment by niekniek89** [comment]
> De latest tag is ongeveer een maand oud. Ik zou de images even verwijderen zodat docker-compose de image opnieuw ophaalt.
> 
> ![image](https://user-images.githubusercontent.com/11210639/94372504-77691280-00fe-11eb-986a-690841cf2804.png)
> 
> https://hub.docker.com/r/xirixiz/dsmr-reader-docker/tags?page=1

even hierop aangehaakt... ik zie ondertussen dat er al wat nieuwere versies beschikbaar zijn, echter is "latest" ruim een maand geleden. dus neem aan dat de huidige 4.4.2/4.4.3 nog gebouwd moet worden voor 'latest'?

**Comment by xirixiz** [comment]
Jawel @niekniek89, de laatste master versie update on startup. Niet echt de gedachte achter Docker, maar wel zo gemakkelijk.... was dat voor de overgang naar versie 4.x. In development werk ik weer met tags op basis van de release en dat ga ik binnenkort ook weer naar master zetten, dan is het weer meer gestructureerd. Nu is in feite de image niet statisch en is de kans groot er een verschil in bijvoorbeeld Phython libraries is tussen de installaties bij mensen thuis. Om meerdere redenen lijkt het mij iig verstandig terug te gaan op releases op basis van de dsmr release en de dsmr release dus in het image te plaatsen.

**Comment by niekniek89** [comment]
> Jawel @niekniek89, de laatste master versie update on startup. Niet echt de gedachte achter Docker, maar wel zo gemakkelijk.... was dat voor de overgang naar versie 4.x. In development werk ik weer met tags op basis van de release en dat ga ik binnenkort ook weer naar master zetten, dan is het weer meer gestructureerd. Nu is in feite de image niet statisch en is de kans groot er een verschil in bijvoorbeeld Phython libraries is tussen de installaties bij mensen thuis. Om meerdere redenen lijkt het mij iig verstandig terug te gaan op releases op basis van de dsmr release en de dsmr release dus in het image te plaatsen.

bedankt voor je snelle reactie. betekend dit dat ikzelf hiervoor iets moet aanpassen in mijn docker-compose o.i.d.? normaliter gebruik ik de recreate functie in portainer, waarbij ik de latest tag gebruik...

**Comment by xirixiz** [comment]
Nee, iedere keer wanneer je de container herstart wordt de laatste versie van DSMR gestart. Dus bij een recreate krijg je nog steeds de laatste DSMR-Reader versie.

**Comment by niekniek89** [comment]
> Nee, iedere keer wanneer je de container herstart wordt de laatste versie van DSMR gestart. Dus bij een recreate krijg je nog steeds de laatste DSMR-Reader versie.

ik kan dus gewoon een recreate uitvoeren, om de laatste versie te bezitten... super bedankt voor je hulp!
