### ISSUE TITLE
Move /release.txt to /dsmr/release.txt

### ISSUE THREAD

**Issue by brainkiller** [xirixiz/dsmr-reader-docker#131]
I've deployed the docker container on a kubernetes cluster.
The downside is that every time the container is started it's installing the dsmr-reader because /release.txt is lost.
At the moment I haven found a way to make the file persistent within kubernetes.

If you could move it to /dsmr it could be part of a single volume and no new installation is needed every time we start the container.

**Comment by xirixiz** [comment]
Good setup! I'm aready working on it. The dev release is already a static release with a tag based on the version of dsmr. Maybe I'll release it Tomorrow 👍🏻

**Comment by xirixiz** [comment]
Moved to tag based releases, so this is obsolete now.
