### ISSUE TITLE
pg_dump outdated

### ISSUE THREAD

**Issue by mlankamp** [xirixiz/dsmr-reader-docker#132]
In my docker-compose file I used `image: postgres:latest` so ended up with version 13. The pg_dump utility in the container is version 12, so my backup failes:

```
pg_dump -h dsmrdb -U dsmrreader -d dsmrreader
pg_dump: error: server version: 13.0 (Debian 13.0-1.pgdg100+1); pg_dump version: 12.3
pg_dump: error: aborting because of server version mismatch
```
Version 13 is not available, any idea how I can add version 13 to my container?

**Comment by xirixiz** [comment]
Yes, therefore is a reason I specified version 12 of Postgres 😄.

The Docker image of Alpine, which is used for DSMR in Docker, doesn't have the v13 client package available (yet).
https://pkgs.alpinelinux.org/packages?name=postgresql-client*&branch=v3.12

You could use the postgresql container itself (or a second one), mount a backup volume and make a dump 

```
docker exec --rm --name pg_dump -ti docker pull postgres:latest bash
pg_dump --version
pg_dumpall --version
```

The output:
```
root@b346e18ca3a3:/# pg_dump --version
pg_dump (PostgreSQL) 13.0 (Debian 13.0-1.pgdg100+1)
root@b346e18ca3a3:/# pg_dumpall --version
pg_dumpall (PostgreSQL) 13.0 (Debian 13.0-1.pgdg100+1)
root@b346e18ca3a3:/#
```

**Comment by mlankamp** [comment]
For now I did a backup-restore in a version 12 container.

The current alpine image for 13 uses the sources to build postgres, that's a bit of an overkill to include version 13. Looking for another solution
