### ISSUE TITLE
Ability to set pg schema?

### ISSUE THREAD

**Issue by rogierlommers** [xirixiz/dsmr-reader-docker#133]
Hey, thanks for your great image! One question though: is it possible to set the pg schema? So instead of using the public schema, I would like to explicit mention the schema using an environment var. When I look at the dsmr docs (https://dsmr-reader.readthedocs.io/nl/v4/env_settings.html) I don't see such environment var available though :(

**Comment by xirixiz** [comment]
I like your idea! I`ll dive into it upcoming week as I currently don't have much time.

**Comment by rogierlommers** [comment]
Hey Bram, also see [this issue](https://github.com/dennissiemensma/dsmr-reader/issues/1138). I don't think it's in your control (you can't do this through a Dockerfile yet).
Right?

**Comment by xirixiz** [comment]
Hey Rogier, volgens mij heb je voldoende info verkregen via Dennis. Ik kijk nog even of ik dit eenvoudig kan verwerken, maar ik verwacht het niet zonder allerhande bash "knutselwerk", al denk ik niet dat het eenvoudig is op te lossen.
