### ISSUE TITLE
Vraag: upgraden naar nieuwste versie

### ISSUE THREAD

**Issue by Calimerorulez** [xirixiz/dsmr-reader-docker#134]
Hi!

Wellicht heb ik weer wat over het hoofd gezien, maar mijn container (xirixiz/dsmr-reader-docker:latest-amd64) hangt nog op 4.4.1.

Wat kan ik doen om hem te upgraden naar 4.4.3?

**Comment by xirixiz** [comment]
Verwijderen en weer starten 😁👍🏻

Met vriendelijke groet,
Bram van Dartel

On 12 Oct 2020, at 18:44, Patrick <notifications@github.com> wrote:

﻿

Hi!

Wellicht heb ik weer wat over het hoofd gezien, maar mijn container (xirixiz/dsmr-reader-docker:latest-amd64) hangt nog op 4.4.1.

Wat kan ik doen om hem te upgraden naar 4.4.3?

**Comment by Calimerorulez** [comment]
Inderdaad :satisfied: :grin:

Ik heb wel Watchtower draaien, maar dat had dus geen zin.

Dank!
