### ISSUE TITLE
How to manually stop the DSMR_Backend?

### ISSUE THREAD

**Issue by HellStorm666** [xirixiz/dsmr-reader-docker#137]
I need to read new data by the API.
dennissiemensma advices to stop the backend prior to the import using:
`sudo supervisorctl stop dsmr_backend`
`sudo supervisorctl stop dsmr_datalogger`

But if I do this, I get unix:///run/supervisord.sock no such file

How to fix this?
I need to import old data (only electrics work, gas doesn't).

Trying to import using this method: https://github.com/dennissiemensma/dsmr-reader/issues/908#issuecomment-592456012

**Comment by xirixiz** [comment]
Hi,

Do the following, where dsmr is the name of your running DSMR Reader Docker container:
```
docker exec -ti dsmr supervisorctl -s unix:///tmp/supervisor.sock stop dsmr_backend
docker exec -ti dsmr supervisorctl -s unix:///tmp/supervisor.sock stop dsmr_datalogger
```

**Comment by MathijsG** [comment]
From within the container these commands do not work here.

``pi@domoticz:~ $ docker exec -ti dsmr bash
root@dsmr_reader_docker:/app# supervisorctl -s unix:///tmp/supervisor.sock stop dsmr_backend
bash: supervisorctl: command not found
root@dsmr_reader_docker:/app#``

Am I doint something wrong? :)

**Comment by xirixiz** [comment]
Ouch, this has changed a lot since 2020 😄 

What is the reason you want to stop dsmr_backend (important to know to come up with a solution)?

You can ofcourse login to the container, do a ```ps -ef``` and kill the process. 
I`m not sure actually how to do this with s6 init.

I believe somthing like this will work. However, I don't advice you to use it like this.
```
s6-svc -d /var/run/s6/services/dsmr_backend
```

**Comment by MathijsG** [comment]
It was in all the guides when wanting to import meter readings via the API. But today I just went ahead with importing towards a running dsmr reader, that was actively getting readings from the p1 usb logger while also being fed a lot of data via the API, and it worked fine.
