### ISSUE TITLE
Still the old environment variables being used?

### ISSUE THREAD

**Issue by michelotten** [xirixiz/dsmr-reader-docker#147]
I just created a new container with the latest image and build it with the new environment variables.
However, it seems the container is still using the old environment variables.

For example.
I set DSMRREADER_ADMIN_PASSWORD, however when I tried to login with this password I got an error.
After checking the environment variables again, I saw also the DSMR_PASSWORD got setup with the default password 'admin'.
Login with this password did work.

**Comment by xirixiz** [comment]
That's correct indeed. When you check here: https://dsmr-reader.readthedocs.io/nl/v4/env_settings.html you'll notice the variables will be removed/unsupported after release 5.0. However, it's odd that your password isn't valid after using the new variable ```DSMRREADER_ADMIN_PASSWORD```. What does it say in the logfiles?

**Comment by michelotten** [comment]
I have now removed all the 'old' variables, but now getting below error:
![image](https://user-images.githubusercontent.com/6818628/97866512-5bafe800-1d0c-11eb-9410-ea60609a1b62.png)
I did set the user and password via the new variables.

**Comment by xirixiz** [comment]
Then I`m almost certain you're using an old Docker image as this message has been altered in newer releases. What is the tag you have currently configured?

**Comment by xirixiz** [comment]
Try this one: ```xirixiz/dsmr-reader-docker:latest```

and also execute ```docker pull xirixiz/dsmr-reader-docker:latest``` manually to make sure you have the latest image.

**Comment by michelotten** [comment]
Thanks. I build the container with the latest tag earlier this morning. I just pulled the latest image again, and now my container is working with the new variables.

**Comment by xirixiz** [comment]
Yeah, sorry, that's the downside of using the same versioning as DSMR Reader, maybe I need to have a different solution in the future as I think a release should be immutable.

Anyway, glad you got it working!
