### ISSUE TITLE
New image: /bin/bash: /run.sh: No such file or directory

### ISSUE THREAD

**Issue by Xitro01** [xirixiz/dsmr-reader-docker#149]
DSMRREADER container is not starting anymore after pulling the latest image.
It used to work before upgrading.

Now it only gives the error "/bin/bash: /run.sh: No such file or directory" in the logs.

**Comment by xirixiz** [comment]
Which tag are you using? Use this tag please ```xirixiz/dsmr-reader-docker:latest```

Also perform a ```docker pull xirixiz/dsmr-reader-docker:latest``` upfront.

**Comment by Xitro01** [comment]
> Which tag are you using? Use this tag please `xirixiz/dsmr-reader-docker:latest`
> 
> Also perform a `docker pull xirixiz/dsmr-reader-docker:latest` upfront.
> 
> My guess is that you're currently using an outdated image.

Using the :latest tag, pulled the image up front.
I went back to an older image I was running and everything works just fine, going to latest again after pulling the image in front again and I’m having the exact same issue.

**Comment by xirixiz** [comment]
That's odd, but there are multiple latest tags available (need to cleanup the Docker hub). Are you sure you are using ```xirixiz/dsmr-reader-docker:latest``` and not the development one? 

Otherwise remove it with ```docker rmi xirixiz/dsmr-reader-docker:latest``` and start the container again. I`m sure this isn't related to the Docker image, but it might be caching or something. Maybe you can share the image ID? The image ID has to be: 60d742f6880f (AMD). Also you could try restart the Docker daemon.

**Comment by Xitro01** [comment]
> That's odd, but there are multiple latest tags available (need to cleanup the Docker hub). Are you sure you are using `xirixiz/dsmr-reader-docker:latest` and not the development one?
> 
> Otherwise remove it with `docker rmi xirixiz/dsmr-reader-docker:latest` and start the container again. I`m sure this isn't related to the Docker image, but it might be caching or something. Maybe you can share the image ID? The image ID has to be: 60d742f6880f (AMD). Also you could try restart the Docker daemon.

Hi, I'm using xirixiz/dsmr-reader-docker:latest with ID: 60d742f6880f. (sha256:60d742f6880f6017958f34d79c4b9662b396b76f0393952516cb0220b558ca70)
Complete restart of the machine did not work.

I highly doubt it's caching, as my friend on a completely different machine has the same issues. I will delete the image and pull it again and let you know.

**Comment by dikkeleo2** [comment]
I've got exactly the same issue. 

Question is how do I return to a previous version?

**Comment by Xitro01** [comment]
> I've got exactly the same issue.
> 
> Question is how do I return to a previous version?

If you're using portainer, you could go to your images, rename the previously working one to dsmr-reader-docker:old. Mine was called :<none>.
Then go to your container: kill it, open it, change the image name from latest to old and save + run it again.
That should do it.

**Comment by andytuinman3** [comment]
Same issue. Needed to revert back to the old version

**Comment by rogierlommers** [comment]
If you do a `docker system prune --all` first? Then download the `:laster`-tag?

**Comment by xirixiz** [comment]
```
xirixiz@nas: 
-> docker images | grep dsmr
xirixiz/dsmr-reader-docker     latest              60d742f6880f        21 hours ago        183MB
```

```
xirixiz@nas:
-> docker logs -f dsmr
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Verifying if Postgres in running...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[ INFO ] Running post configuration...
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
  No migrations to apply.

561 static files copied to '/var/www/dsmrreader/static'.
Updating password of superuser "admin"
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Starting supervisord...
[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log
2020-11-02 12:09:14,193 INFO Included extra file "/etc/supervisor.d/supervisord.ini" during parsing
2020-11-02 12:09:14,194 INFO Set uid to user 0 succeeded
2020-11-02 12:09:14,207 INFO RPC interface 'supervisor' initialized
2020-11-02 12:09:14,207 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-02 12:09:14,208 INFO supervisord started with pid 16
2020-11-02 12:09:15,212 INFO spawned: 'dsmr_backend' with pid 18
2020-11-02 12:09:15,215 INFO spawned: 'dsmr_datalogger' with pid 19
2020-11-02 12:09:15,219 INFO spawned: 'dsmr_webinterface' with pid 20
2020-11-02 12:09:15,222 INFO spawned: 'nginx' with pid 21
2020-11-02 12:09:16,721 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-02 12:09:16,722 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-02 12:09:16,723 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-02 12:09:18,930 INFO success: dsmr_webinterface entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
```

Which architecture are you using, maybe the case is that de build pipeline didn't run properly for a specific architecture. That's something I did encounter before. 

I removed the docker image and pulled it again, running like a charm, so I guess it must have something related to what I just mentioned. I`m using AMD64.

**Comment by xirixiz** [comment]
Can you share the output of ```docker images | grep dsmr```?

**Comment by michelotten** [comment]
Maybe good to know, I had the same issue yesterday when updating my existing container on a Synology DS218+ NAS.
After downloading a fresh 'latest' image and setting up a new container, the error was gone.

**Comment by dikkeleo2** [comment]
I'm running it on libreelec so it's not amd64 I think armv8

**Comment by andytuinman3** [comment]
Removed the latest image and re-download it. Still no dice. Same error

**Comment by andytuinman3** [comment]
![IMG_20201103_100913](https://user-images.githubusercontent.com/4999564/97967010-e819e380-1dbc-11eb-95e5-7e4c0f8458f4.jpg)

**Comment by xirixiz** [comment]
Currently rebuilding the images. Please try again all in about 10 minutes

**Comment by xirixiz** [comment]
You may try again.

stop and remove dsmr
docker system prune --all
start dsmr again

**Comment by andytuinman3** [comment]
Do I need to remove the container? Does that mean I have to start all over again? Removing latest and recreating the container with the newest latest still doesn't work.

**Comment by xirixiz** [comment]
Ofcourse you need to remove the container, otherwise your still starting it with the old image....

**Comment by xirixiz** [comment]
Stopping and starting doesn't apply the new image.

**Comment by andytuinman3** [comment]
I know I was on old (the tag I created to still make it work) so latest was unused. I deleted latest and re-download it. I stopped dsmr and recreated it pointing it to the new latest image. That should do the trick right? FYI I'm using portainer on my Home assistant box. So I'm afraid to use the prune command for what it *might* do to the 20 or so HA containers

**Comment by xirixiz** [comment]
Not sure how to help with your setup Andy, you shouldn't be afraid of using ```docker system prune --all``` in the first place 😉.

The point of using Docker and proper automation is that you can be up-and-running without any hassle 😃.
I`m 100% sure the images are correct now, I even verified in a clean environment in which I just installed Docker.

**Comment by dikkeleo2** [comment]
Fresh new setup was the solution. Lost data between 21:00 up to now but happy that it's working again!

**Comment by Xitro01** [comment]
Got it working, had to change COMMAND to '/bin/bash' '-c' '/app/run.sh'.
Probably you made some changes in this.

Now I have issues with connecting to the postgres DB, did you make some changes there as well?

**Comment by Xitro01** [comment]
Indeed, DB_ ENV's are no longer used, now we have to use DJANGO_DATABASE_ env's.

This solves everything!

**Comment by xirixiz** [comment]
> Got it working, had to change COMMAND to '/bin/bash' '-c' '/app/run.sh'.
> Probably you made some changes in this.
> 
> Now I have issues with connecting to the postgres DB, did you make some changes there as well?

Change COMMAND? Do you specify it somewhere? This is the default for the Docker image, so no need to specify it. Also if I change it in the future, you have to modify it again 😄

**Comment by xirixiz** [comment]
But glad eveyone got it working again 🥳

**Comment by Xitro01** [comment]
> > Got it working, had to change COMMAND to '/bin/bash' '-c' '/app/run.sh'.
> > Probably you made some changes in this.
> > Now I have issues with connecting to the postgres DB, did you make some changes there as well?
> 
> Change COMMAND? Do you specify it somewhere? This is the default for the Docker image, so no need to specify it. Also if I change it in the future, you have to modify it again 😄

Actually when using a solution like Portainer, it sets the COMMAND automatically from the image. Yet, if it's already set and you update the docker image and this changes, then it does not change it in the container automatically.
The same with ENV's, those should not be changed in your images afterwards, as you change the values in the ENV's. Those are not changing dynamically.
