### ISSUE TITLE
dsmr_datalogger (exit status 1; not expected)

### ISSUE THREAD

**Issue by f0nt4** [xirixiz/dsmr-reader-docker#15]
When running "docker-compose up -d" and watching the logs the data-logger will not repeatedly exit.
The following 2 lines keep repeating themselves:
```
dsmr | 2018-03-04 20:15:01,030 INFO spawned: 'dsmr_datalogger' with pid 139
dsmr | 2018-03-04 20:15:01,520 INFO exited: dsmr_datalogger (exit status 1; not expected)
```
I've fixed this by adding "sudo chmod 666 /dev/ttyUSB0" to entrypoint.sh and after that rebuilding.
But I guess there might be a nicer option to do this. Perhaps by adding this line to the Dockerfile.

**Comment by xirixiz** [comment]
I`ll look into this, normally these should be the lines in the Dockerfile fixing this issue:
```
    && usermod -a -G dialout root \
    && usermod -a -G dialout dsmr \
```
What is the OS you're running Docker on?

**Comment by f0nt4** [comment]
Those 2 command should indeed allow access to the usb port, but the dsmr_datalogger keeps restarting over and over untill I give this command: docker exec -t dsmr sudo chmod 666 /dev/ttyUSB0
Or apply the workaround like how I did with the entrypoint.sh.

I'm running Docker on Ubuntu 16.04.4, and did have to change the version from 3 to 2.

**Comment by xirixiz** [comment]
Oke thanks. I've added "sudo chmod 666 /dev/ttyUSB*" to entrypoint.sh
