### ISSUE TITLE
DSMR V4.5 upgrade naar latest

### ISSUE THREAD

**Issue by niekniek89** [xirixiz/dsmr-reader-docker#152]
Goedemiddag,

ik wilde vandaag mijn DSMR Reader upgraden van 4.5 naar de laatste (inmiddels 4.6.1.).
echter krijg ik een vergelijkbare melding zoals in:

https://github.com/xirixiz/dsmr-reader-docker/issues/149

moet ik toevallig aan mijn kant nog het e.a. aanpassen in mijn docker compose?
hij heeft momenteel een .old container aangemaakt, welke gelukkig werkt met de 4.5 versie.
ik gebruik tevens deze tag: xirixiz/dsmr-reader-docker:latest

alvast bedankt.

**Comment by xirixiz** [comment]
Gebruik je portainer? Heb je de stappen in het referentie issue uitgevoerd? Bijv zoals docker system prune --all?

**Comment by niekniek89** [comment]
> Gebruik je portainer? Heb je de stappen in het referentie issue uitgevoerd? Bijv zoals docker system prune --all?

Bedankt voor je reactie!
Ik gebruik inderdaad Portianer.
Bedoel je deze stappen:

stop and remove dsmr
docker system prune --all
start dsmr again

Die heb ik nog niet uitgevoerd.
Misschien een gekke vraag, maar wat trap ik deze commando’s af?

**Comment by xirixiz** [comment]
Waarschijnlijk is het dan voldoende om command aan te passen in portainer.

```Got it working, had to change COMMAND to '/bin/bash' '-c' '/app/run.sh'.```

**Comment by niekniek89** [comment]
> Waarschijnlijk is het dan voldoende om command aan te passen in portainer.
> 
> `Got it working, had to change COMMAND to '/bin/bash' '-c' '/app/run.sh'.`
> 
> Vergeet ook niet de variabelen te wijzigen volgens de documentatie: https://github.com/xirixiz/dsmr-reader-docker/blob/master/README.md

Bedankt voor je reactie.
Dit was uiteindelijk de oplossing:

stop and remove dsmr
docker system prune --all
start dsmr again

zit nu op 4.6.1, en start zonder problemen!
