### ISSUE TITLE
Feature request: SSL

### ISSUE THREAD

**Issue by Xitro01** [xirixiz/dsmr-reader-docker#153]
Could you add a new ENV to support SSL?

If SSL == True, then add the following lines to the nginx config:

```
listen 443 ssl;
ssl_certificate /etc/ssl/private/fullchain.pem;
ssl_certificate_key /etc/ssl/private/privkey.pem;
```

Requirement would be to mount your LetsEncrypt folder to /etc/ssl/private on the container (with the right privileges).

> --------------------------------------------------

**Current work-around - for people running Portainer with HomeAssistant**

I currently have this working with the LetsEncrypt add-on in HomeAssistant:

1. Copy the configuration file _dsmr-webinterface.conf_ located in the docker under _/etc/nginx/conf.d_ to _/usr/share/hassio/share/nginx_dsmr_.
2. Add the following lines to your configuration file:
```
listen 443 ssl;
ssl_certificate /etc/ssl/private/fullchain.pem;
ssl_certificate_key /etc/ssl/private/privkey.pem;
```
3. Add the following volumes to your docker container:
```
/etc/ssl/private:/usr/share/hassio/ssl
/etc/nginx/conf.d:/usr/share/hassio/share/nginx_dsmr
```
4. Deploy and go to: https://domain:7779

**Comment by xirixiz** [comment]
That would be possible to add Xitro01. I`ll look into it the upcoming week. This week I don't have much time.

**Comment by xirixiz** [comment]
I think I`m able to implement this Today

**Comment by Xitro01** [comment]
> I think I`m able to implement this Today

Great, let me know. Happy to test.

**Comment by xirixiz** [comment]
Took some time but it has been added to the master branch. Next release it will be available.

**Comment by Xitro01** [comment]
> Took some time but it has been added to the master branch. Next release it will be available.

Hi xirixiz, could you give me a headsup when it's released? Then I will test it right away.

**Comment by xirixiz** [comment]
Building now, should be available before noon :)

**Comment by Xitro01** [comment]
Tested and works perfectly! Thanks!
