### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by ronniebee** [xirixiz/dsmr-reader-docker#155]
@xirixiz 

after having trouble with a bad gateway I succeeded in installing the docker again.
but now the following shows up:

PostgreSQL Database directory appears to contain a database; Skipping initialization
2020-11-17 22:17:07.926 CET [1] FATAL:  database files are incompatible with server
2020-11-17 22:17:07.926 CET [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 12.5.

#solved by changing in the compose file : alpine from 12 to 10 👍 

I don't know if this is a proper solution but it works.

How should I upgrade to version 12.5? 

Can you advice?

**Comment by xirixiz** [comment]
I guess you mean the postgres container swtiched back from Alpine 12 to 10?

The upgrade steps I performed myself recently are mentioned here:
https://github.com/xirixiz/dsmr-reader-docker/issues/145#issuecomment-720411358

**Comment by xirixiz** [comment]
...also I just added the steps at the bottom of the README.md ;)
