### ISSUE TITLE
Environment variables readme

### ISSUE THREAD

**Issue by me1299** [xirixiz/dsmr-reader-docker#156]
I was having problems with my DATALOGGER daemon starting and then stopping because I'm only using this container for processing messages from another host.

But nowhere in the documentation could I find that I needed to use the environment variable:
`SD_AUTOSTART_DATALOGGER=false`

Maybe you could add if to the documentation along with probably more variables that are not mentioned. (such as: SD_AUTOSTART_MQTT etc)

**Comment by xirixiz** [comment]
When you read the documentation you'll indeed notice the variables aren't there anymore. But when you read further you'll also read you can setup 3 types of roles for this image. By default the container starts "standalone", meaning it spawns all processes, which now is the case in your situation. So instead of searching for a variable, it's better to look at the documentation :)

**Comment by me1299** [comment]
I should have been more clear in my post, when using the receiver mode the datalogger component is still spawned which shouldn't be the case.

Only with
SD_AUTOSTART_DATALOGGER=false was I able to silence it and stop it from exiting and looping.

**Comment by xirixiz** [comment]
Hehehe, then indeed it's different and clear 😄. ```SD_AUTOSTART_DATALOGGER``` is an old an obsolete value, so my guess is you are running on an old Docker image. Can you pull the latest Docker image?

```docker pull xirixiz/dsmr-reader-docker```

**Comment by xirixiz** [comment]
....wait, let me investigate a bit further first and get back to it.

**Comment by xirixiz** [comment]
Just verified and when I specify DATALOGGER_MODE=receiver it's working as expected, so the datalogger isn't being spawned:

```
-> docker logs -f dsmr
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Verifying if Postgres in running...
[ INFO ] Configuring DSMR in receiver datalogger mode....
[ INFO ] Running post configuration...
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
  No migrations to apply.

561 static files copied to '/var/www/dsmrreader/static'.
Updating password of superuser "admin"
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Starting supervisord...
[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log
2020-11-18 08:12:05,161 INFO Included extra file "/etc/supervisor.d/supervisord.ini" during parsing
2020-11-18 08:12:05,161 INFO Set uid to user 0 succeeded
2020-11-18 08:12:05,234 INFO RPC interface 'supervisor' initialized
2020-11-18 08:12:05,234 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-18 08:12:05,235 INFO supervisord started with pid 16
2020-11-18 08:12:06,238 INFO spawned: 'dsmr_backend' with pid 18
2020-11-18 08:12:06,242 INFO spawned: 'dsmr_webinterface' with pid 19
2020-11-18 08:12:06,246 INFO spawned: 'nginx' with pid 20
2020-11-18 08:12:07,925 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-18 08:12:07,926 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-18 08:12:09,325 INFO success: dsmr_webinterface entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
```

**Comment by me1299** [comment]
Thank you for your help! I turned out I was using the `latest` tag.
`image: xirixiz/dsmr-reader-docker:latest`

I suppose that isn't actually the latest ;)
