### ISSUE TITLE
DSMR-datalogger keeps restarting 

### ISSUE THREAD

**Issue by stevengoossensB** [xirixiz/dsmr-reader-docker#163]
Hi,

For some reason, the dsmr_datalogger only sporadically is able to read data from the smart meter. When I connect manually over the serial port, I get a constant flow of data (~=1 measurement/s).

I've noticed in the logs that the datalogger is constantly rebooting, which might have something to do with it.

My setup is using the pre-built docker containers, so I had expected this to work out of the box. Any idea whether I'm missing some configuration, ENV variable,...?

![image](https://user-images.githubusercontent.com/10197869/105099507-1352cb80-5aac-11eb-972b-4b8b82e54347.png)

```
2021-01-19 22:10:46,578 INFO exited: dsmr_datalogger (exit status 0; expected)
2021-01-19 22:10:47,590 INFO spawned: 'dsmr_datalogger' with pid 33
2021-01-19 22:10:48,597 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-01-19 22:11:33,513 INFO exited: dsmr_datalogger (exit status 0; expected)
2021-01-19 22:11:34,526 INFO spawned: 'dsmr_datalogger' with pid 34
2021-01-19 22:11:35,535 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-01-19 22:12:01,522 INFO exited: dsmr_datalogger (exit status 0; expected)
2021-01-19 22:12:02,534 INFO spawned: 'dsmr_datalogger' with pid 35
2021-01-19 22:12:03,542 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by xirixiz** [comment]
Hi, could you please tell me the following:

- What Docker image are you using?
- How does your setup look like? Is the P1 cable directly attachted to the Docker host f.e.?

Also please verify whether you have configured the Datalogger properly for your environment:
http://<dsmr host>:<dsmr port>/admin/dsmr_datalogger/dataloggersettings/

Ofcourse there is no such a thing as "running out of the box", configuration for personal requirements are always involved from my experience :). Docker makes things more easy, but doesn't solve everything.

**Comment by stevengoossensB** [comment]
Hi Bram,

The P1 cable is attached directly to the docker host and is mounted inside the Docker container. After letting it run for the night, I can now see readings every 5-15 minutes, at random moments in between. From that perspective, everything seems to work but I don't get why it doesn't read it more frequent as I get a constant stream of data with cu.

The datalogger and backend sleep times are set to 5 seconds and I did select the right serial port and the right meter type (works both for the DSMR4/5 as for the Fluvius config).

Personally, I'm suspicious about the supervisor process which isn't fully doing what it should, as I do get some errors there... But I can't get my head around why it does work every x amount of minutes then :)

![image](https://user-images.githubusercontent.com/10197869/105146626-7e2df200-5b00-11eb-9c86-25acf2254475.png)


![image](https://user-images.githubusercontent.com/10197869/105145930-a8cb7b00-5aff-11eb-8448-630e35ecf5c1.png)

**Comment by xirixiz** [comment]
I don't think it's supervisor. What you're trying to do isn't going to work within the running container. It's a long and different story, but you could google it ofcourse. However, supervisord isn't the best solution out there for Docker, I`m also looking into this for a future release. I`m planning to move to S6 or if possible to dumb-init.

However, this issue you're facing is odd indeed. Not sure what is happening here. Is anything else using the P1 port for readings?
Maybe @dennissiemensma has an idea?

**Comment by stevengoossensB** [comment]
Hi, thanks for your suggestion... Indeed something in the background from a previous attempt with different SW was still running. Cleaning this helped and I'm now getting multiple readings per minute, in line with the timeouts.

**Comment by dennissiemensma** [comment]
> I don't think it's supervisor. What you're trying to do isn't going to work within the running container. It's a long and different story, but you could google it ofcourse. However, supervisord isn't the best solution out there for Docker, I`m also looking into this for a future release. I`m planning to move to S6 or if possible to dumb-init.
> 
> However, this issue you're facing is odd indeed. Not sure what is happening here. Is anything else using the P1 port for readings?
> Maybe @dennissiemensma has an idea?

@xirixiz je zou nog kunnen overwegen om voor dit project in Docker aparte containers te gebruiken per process, waarbij je huidige opzet grotendeels een `base` container wordt (zonder supervisor) en dat je dan daar 3 containers van maakt die de base gebruiken. 

Deze draaien dan geen supervisor, maar elk 1 proces, in de trend van:
- `dsmr-reader-docker-core` -> dsmr_backend _(zou tevens degene zijn die bijvoorbeeld db-migraties uitvoert)_
- `dsmr-reader-docker-webinterface` -> dsmr_webinterface
- `dsmr-reader-docker-datalogger` -> dsmr_datalogger

Dan zou je van supervisor af zijn voor docker en maak je het ook nog aardig modulair. 

Dat zeggende hebben krijg je wel tig containers voor alle varianten die je nu al ondersteunt en zal het vast nog andere nadelen hebben natuurlijk.

**Comment by xirixiz** [comment]
@dennissiemensma klopt, dat zou ook best practice zijn vanuit Docker gezien. Alleen vind ik het een beetje overdreven een drietal containers te draaien. Ik zal er eens over nadenken om het op een andere/betere manier in te richten. Thanks!
