### ISSUE TITLE
Problem with running Docker on Synology

### ISSUE THREAD

**Issue by hemant5400z** [xirixiz/dsmr-reader-docker#166]
Hi,

I like this project very much as i'm into dockers I would like to setup DSMR in a docker.
But i'm running into issues, not sure what the exact problem is.

I use the compose file (changed to version 2), otherwise synology was complained.
All comes up but by naming conversion is as follows:
docker_dsmr_1
docker_dsmrdb_1

It dsmr crahes at start seems looking for host dsmrdb while my container name is docker_dsmrdb_1.
changed the container name to what is expected but still same issues.

Tried the other way around changing host name to docker_dsmrd_1 but same issue so not sure what is wrong?
I assume dsmrreader user and database are already created?

**Comment by hemant5400z** [comment]
Hi,

Seems firewall was blocking connections between the to dockers, i have added a firewall rule in synology which seems to works.

Cheers

**Comment by xirixiz** [comment]
Yes! I had the same thing in the past on my Syno! Can you share the firewall rules you've added? Other users might also need it. Thanks!

**Comment by xirixiz** [comment]
I believe I used this:

```
com.docker.network.bridge.enable_icc=true
```

Or this:
```
sysctl net.ipv4.conf.all.forwarding=1
sudo iptables -P FORWARD ACCEPT
```

**Comment by hemant5400z** [comment]
Hi,

It was rather simple after i figured it was the firewall.

Apperntly syno firewall effect the docker appliaction also.

In my case my docker bridge uses 172.20.0.x for dsmr.

So first disable firewall to test if that worked and yes dsmr and dsmrdb start en page login worked.

So went back to the syno security tab and enabled the firwewall application.

In the first section selected dmsr and dmsrdb.

Second section i added allows specific and 172.20.0.1
Subnet 255.255.255.0
Allow


Applied settings en restarted the dockers on syno and all worked. To double checked by disabled this rule. And dsmr connection failed so it was that rule allowing to communicate between the 2 dockers.

In my yaml file i added port 5433 to be mapped as i'm using another port because on syno 5432 is already taken by syno.

Now i can remotely connect to 5433 with pgadmin to monitor the database. Don't forget to edit the postgres.conf file and enable port=5433.

Hope this helps, let me know if you have questions.

Fijne dag!
Hemant
