### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by MRL-33** [xirixiz/dsmr-reader-docker#167]
Dag Xirixiz,
Deze melding is eigenlijk geen foutmelding, maar ik krijg de update naar de nieuwste PostgreSQL-versie niet voor elkaar.
Ik kan de huidige database niet vinden&wissen.
Ik wil... óf de database updaten óf alles wissen om weer vers te beginnen, maar dit beide lukt niet.

Ik heb de soortgelijke vraag ergens anders gesteld en jij had daar zelfs een stappenplan achtergelaten. Dank daarvoor.
Maar terug naar mijn probleem:
Ik kan dus mijn database niet vinden om te wissen.
Hieronder vind je een ZIP-bstand met mijn bestanden ".env" & "docker-compose.yaml"
Deze bestanden staan in projectmap: "/home/pi/docker-compose-files/dsmr"
en de yaml start ik in deze projectmap op met:  sudo docker-compose up -d  (let op: begint met sudo ivm rechten) 

Dit is wat ik heb genoteerd:

**Backup de database**
ga naar de juiste projectmap
`cd /home/pi/docker-compose-files/dsmr`
Stop en verwijder de DSMR-reader container:
```
sudo docker-compose stop dsmr
sudo docker-compose rm dsmr
```
Exporteer de PostgreSQL-database naar een SQL-bestand:
`sudo docker exec -t dsmrdb pg_dumpall -c -U dsmrreader > postgresql-dump.sql`
Stop en verwijder de database container:
```
sudo docker-compose stop dsmrdb
sudo docker-compose rm dsmrdb
```
Verwijder de aanwezige database:
`sudo docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader`  <--- werkt niet / gestart in projectmap

**Wis en herstel de database** 
Pas bestand “docker-compose.yaml” aan:
Ofwel: wijzig de PostgreSQL versie.
Start de database container:
`sudo docker-compose start dsmrdb`
Importeer de SQL data (zie stap 3) in de nieuwe database:
`cat postgresql-dump.sql | docker exec -i dsmrdb psql -U dsmrreader`
Start de DSMR-reader container opnieuw:
`sudo docker-compose start dsmr`

Bron: https://hub.docker.com/r/ualex73/dsmr-reader-docker

Zou je me hier meer uitleg willen geven ?
O ja... alles draait op een Raspberry Pi 3B+ met Raspberry Pi OS
(En ik ben bezig om alles achter NPM (Nginx Proxy Manager) te zetten. Heb je deze yaml bestand ook nodig?)

[docker-compose.zip](https://github.com/xirixiz/dsmr-reader-docker/files/5900431/docker-compose.zip)

**Comment by xirixiz** [comment]
Hi MRL-33,

Volgens mij moet het wel lukken met de volgende stappen:
https://github.com/xirixiz/dsmr-reader-docker#upgrade-the-postgres-container-to-a-newer-release

De bedoeling is dat je dsmr stopt en daarna een dump maakt van de database
```
sudo docker-compose stop dsmr
docker exec -t dsmrdb pg_dumpall -c -U dsmrreader > dsmrreader.sql
```

Vervolgens stop je dsmrdb en verwijder je alle data uit "./dsmrdb":
```
sudo docker-compose stop dsmrdb
```

Pas vervolgens de docker-compose aan met de image "postgres:12-alpine"

Vervolgens kan je ```sudo docker-compose down``` uitvoeren, gevolgd door ```docker-compose up -d```.
Je hebt nu weer een nieuwe/schone omgeving. Nu kan je database verwijderen en de backup van de eerste stap importeren en dan ben je klaar.

```
sudo docker-compose stop dsmr
sudo docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader
sudo docker exec -t dsmrdb createdb -O dsmrreader dsmrreader -U dsmrreader
cat dsmrreader.sql | sudo docker exec -i dsmrdb psql -U dsmrreader
sudo docker-compose start dsmr
```

Volgens mij moet het wel lukken nu. Succes!

**Comment by MRL-33** [comment]
Dag Xirixiz,

Dankjewel voor je snelle reactie.
Ik heb onderstaand gedaan, maar krijg een foutmelding:
Kan ik beter niet gewoon alles wissen en met een opgeschoonde projectmap & verwijderde database weer vers starten?

`sudo docker-compose stop dsmr`
Stopping dsmr ... done
`sudo docker-compose stop dsmrdb`
Stopping dsmrdb ... done
`sudo docker-compose down`
Removing dsmr   ... done
Removing dsmrdb ... done
Removing network dsmr_default
`sudo docker-compose up -d`
Creating network "dsmr_default" with the default driver
Creating dsmrdb ... done
Creating dsmr   ... done
`sudo docker-compose stop dsmr`
Stopping dsmr ... done
`sudo docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader`
Error response from daemon: Container ... is restarting, wait until the container is running
`sudo docker exec -t dsmrdb createdb -O dsmrreader dsmrreader -U dsmrreader`
Error response from daemon: Container ... is restarting, wait until the container is running

Verder monitor ik mijn containers via Portainer.
Kunnen we eventueel ook videochatten/beel delen via Google Meet om dit probleem op te lossen?

[_dsmr_logs.txt](https://github.com/xirixiz/dsmr-reader-docker/files/5906618/_dsmr_logs.txt)
[_dsmrdb_logs.txt](https://github.com/xirixiz/dsmr-reader-docker/files/5906621/_dsmrdb_logs.txt)

**Comment by xirixiz** [comment]
Letterlijk zie ik in de log staan "PostgreSQL Database directory appears to contain a database; Skipping initialization". Dus bij de fout "Error response from daemon: Container ... is restarting, wait until the container is running", krijg je eigenlijk in de container de fout dat de data directory al data bevat. Heb je de de mounted volume helemaal leeg gemaakt? Echt alle content moet weg zijn, alleen de folderstructuur mag bestaan.

Overigens doe ik dit op vrijwillige basis, dus een sessie tbv support wil ik niet aan beginnen, maar dat zal je begrijpen :).

**Comment by xirixiz** [comment]
Dus stop applicatie, maak db backup, stop database, verwijder alle db data, werk docker-compose bij met pg12, start de database en applicatie weer op, stop de applicatie na initialisatie, drop de db, import de db backup, start applicatie

**Comment by MRL-33** [comment]
ik denk dat ik dat deze keer vergeten ben. Ga ik morgen doen.
Dus... de map: "/home/pi/docker-compose-files/dsmr/dsmrdb" moet leeg zijn? Geen files en subfolders meer in die map?

Ik kan me herinneren dat ik dit ooit eerder heb gedaan. De inhoud kon ik niet wissen als 'pi' maar alleen als 'root'.
Klinkt dit herkenbaar?

**Comment by xirixiz** [comment]
Gewoon idd leegmaken als root zijnde.
