### ISSUE TITLE
Raspberry PI

### ISSUE THREAD

**Issue by Antonides** [xirixiz/dsmr-reader-docker#17]
Als ik hem wil draaien op een rpi dan krijg ik in de log de volgende foutmelding:

`dsmr      | standard_init_linux.go:195: exec user process caused "exec format error"`
`dsmr exited with code 1`

Zou de docker moeten werken op een rpi?

**Comment by ReadySteadyFlow** [comment]
Ik heb hetzelfde probleem. Dit heb ik kunnen verhelpen door een eigen image te builden met Debian Stretch als basis i.p.v. Ubuntu.

**Comment by xirixiz** [comment]
Op de rpi heb ik de docker image nooit gebruikt. Maar switchen naar debian stretch vind ik prima wanneer dat wel werkt. Ik zal het pull request doorvoeren. Bedankt ReadySteadyFlow!
