### ISSUE TITLE
Geen verbinding met een database in postgres container

### ISSUE THREAD

**Issue by jelbo** [xirixiz/dsmr-reader-docker#170]
Ik heb jouw laatste DMSR-reader Docker image draaien op mijn Synology DS713+ samen met een postgres Docker image. Het lukt mij niet om verbinding te maken met de database. De log zegt dan:

```
[ INFO ] Verifying Database connectivity...
None
```

Wat ik heb gedaan: in postgres volgens de DSMR-reader [instructies](https://dsmr-reader.readthedocs.io/en/v4/installation.html#option-b-install-dsmr-reader-manually-explained) als gebruiker `postgres` de gebruiker en database gemaakt:

```
createuser -DSR dsmrreader
createdb -O dsmrreader dsmrreader
psql -c "alter user dsmrreader with password 'dsmrreader';"
```
Inloggen getest met gebruiker `postgres` vanaf de console:

```
psql -d dsmrreader -U dsmrreader
psql (13.1 (Debian 13.1-1.pgdg100+1))
Type "help" for help.

dsmrreader=>
```

DSMR-reader heb ik vervolgens geconfigureerd met (o.a.) deze variabelen:

```
DJANGO_DATABASE_NAME      dsmrreader
DJANGO_DATABASE_USER      dsmrreader
DJANGO_DATABASE_PASSWORD  dsmrreader
DJANGO_DATABASE_HOST      172.17.0.9    (bridge IP?)
DJANGO_DATABASE_PORT      5432          (Container Port)
```
Verbinding met de database getest vanaf de DSMR-reader console:
```
pg_isready -h 172.17.0.9 -p 5432
172.17.0.9:5432 - accepting connections
```
Als ik de database host en port wijzig naar het IP adres van de Synology (`192.168.1.4`) en de (afwijkende, omdat `postgres` ook al lokaal op de Synology draait) Local Port `5433` krijg ik hetzelfde resultaat in de log. De verbindingstest slaagt ook:
```
pg_isready -h 192.168.1.4 -p 5433
192.168.1.4:5433 - accepting connections
```
Beide IP adressen kan ik ook pingen vanuit de DSMR-reader container.

Ik heb de configuratie gedaan met de Synology Docker app, dus ik heb geen compose file o.i.d. Wel heb ik Portainer draaien.

Alles lijkt mij correct, ik kan de fout niet ontdekken.

**Comment by xirixiz** [comment]
Goede en heldere toelichting van het probleem @jelbo!

Het probleem kan veroorzaakt worden door de volgende zaken:

- Het default bridge network van de Synology heeft (soms) problemen met communicatie tussen containers onderling. Je zou een nieuw bridge network aan kunnen maken (maar weet niet of dat netwerkt te selecteren is via de Docker UI van de Synology):
```
docker network create \
           -o "com.docker.network.bridge.enable_icc"="true" \
           -o "com.docker.network.bridge.enable_ip_masquerade"="true" \
           -o "com.docker.network.bridge.host_binding_ipv4"="0.0.0.0" \
           -o"com.docker.network.driver.mtu"="1500" \
           custom_bridge
```

- Ik zie dat de port mapping van de Synology naar de Postgres container een mapping heeft van 5433:5432. Mogelijk is dit de configuratie:
```
DJANGO_DATABASE_HOST=192.168.1.4
DJANGO_DATABASE_PORT=5433
```
Of dit wanneer je container de naam "dsmrdb" heeft en draait op poort 5432:
```
DJANGO_DATABASE_HOST=dsmrdb
DJANGO_DATABASE_PORT=5432
```

- De stappen uit de documentatie van DSMR reader zijn niet van toepassing. Ik heb het in de DSMR reader container "ingebouwd" dat allees wordt aangemaakt wanneer het om een "schone" Postgres omgeving gaat.

**Comment by xirixiz** [comment]
Misschien heb je hier iets aan om de vertaling te maken naar de Synology UI:

```
function dsmrdb() {
    NAME=dsmrdb
    IMAGE=postgres:12-alpine
    docker_rm
    docker pull "${IMAGE}"
    docker run --detach \
               --name ${NAME} \
               --restart always \
               --volume /etc/localtime:/etc/localtime:ro \
               --volume ${DOCKERHOME}/data/dsmr/data:/var/lib/postgresql/data:rw \
               --env "POSTGRES_USER=dsmrreader" \
               --env "POSTGRES_PASSWORD=dsmrreader" \
               --env "POSTGRES_DB=dsmrreader" \
               --env-file .env \
               --network ${DOCKER_NETWORK_BRIDGE} \
               ${IMAGE}
    echo "* Sleeping for 5 seconds before starting DSMR..."
    sleep 5s
}

function dsmr() {
    NAME=dsmr
    IMAGE=xirixiz/dsmr-reader-docker:latest
    #IMAGE=xirixiz/dsmr-reader-docker:development-v4.9.0-amd64
    docker exec -ti ${NAME} bash -c '/app/cleandb.sh'
    docker_rm
    docker pull "${IMAGE}"
    docker run --detach \
               --publish 7777:80 \
               --publish 7778:443 \
               --name ${NAME} \
               --restart always \
               --tty \
               --volume /etc/localtime:/etc/localtime:ro \
               --volume ${DOCKERHOME}/data/${NAME}/backups:/dsmr/backups:rw \
               --device /dev/ttyUSB0:/dev/ttyUSB0 \
               --cap-add NET_ADMIN \
               --env "SD_LOGLEVEL=info" \
               --env "DJANGO_DATABASE_HOST=dsmrdb" \
               --env "DJANGO_DATABASE_USER=dsmrreader" \
               --env "DJANGO_DATABASE_PASSWORD=dsmrreader" \
               --env "DJANGO_DATABASE_PORT=5432" \
               --env "DSMRREADER_LOGLEVEL=WARNING" \
               --env "DSMRREADER_ADMIN_USER=admin" \
               --env "DSMRREADER_ADMIN_PASSWORD=admin" \
               --env-file .env \
               --network ${DOCKER_NETWORK_BRIDGE} \
               ${IMAGE}
}
```

**Comment by jelbo** [comment]
Bedankt voor je snelle reactie. Jouw
```
DJANGO_DATABASE_HOST=192.168.1.4
DJANGO_DATABASE_PORT=5433
```
had ik al getest, met hetzelfde resultaat.

Het `custom_bridge` netwerk heb ik met je commando aangemaakt en via Portainer gekoppeld aan beide containers. Het bestaande bridge netwerk heb ik losgekoppeld.

Vervolgens in Portainer gezien dat postgres `172.18.0.2` heeft gekregen. Dit samen met poort `5432` ingevuld in de DSMR-reader variabelen en de container gestart. Ik krijg nog steeds dezelfde melding. Ook hier geeft de test met `pg_isready` een succesvol resultaat (`172.18.0.2:5432 - accepting connections`).

Vervolgens teruggegaan naar het normale bridge netwerk, geverifieerd dat postgres weer `172.17.0.9` heeft gekregen en daarna in de DSMR-reader container via Portainer een `hosts`-entry toegevoegd: `dsmrdb:172.17.0.9`. Daarna `DJANGO_DATABASE_HOST` verwijzen naar `dsmrdb`.

Helaas, nog steeds een `None` na de `[ INFO ] Verifying Database connectivity...`

Een pingtest naar `dsmrdb` geeft de verwachte `172.17.0.9` en ook de `pg_isready` test slaagt.

Ik kan nog alle combinaties qua netwerk uitproberen, maar ik verwacht daar niks van. Misschien als ik mijn postgres-container aanmaak als `dsmrdb`...

**Comment by jelbo** [comment]
> De stappen uit de documentatie van DSMR reader zijn niet van toepassing, de db en user worden aangemaakt bij het starten van de container, mits de variabelen gedefinieerd zijn.

Dus... ik moet _niet_ zelf een `dsmrreader` gebruiker en database aanmaken in postgres? Ik heb die container gecleared, de inhoud van de elders gemapte folder `/var/lib/postgresql/data` verwijderd en postgres schoon gestart. DSMR-reader blijft dan hangen en crashen op de database-check-stap.

**Comment by xirixiz** [comment]
Het is mij niet geheel duidelijk wat je precies bedoeld met "mijn POSTGRES_PASSWORD" daar is uniek. Zoals je in mijn voorbeeld komen de waarden op de PG container:

```
               --env "POSTGRES_USER=dsmrreader" \
               --env "POSTGRES_PASSWORD=dsmrreader" \
               --env "POSTGRES_DB=dsmrreader" \
```

Overeen met de waarden van de DSMR container
```
               --env "DJANGO_DATABASE_NAME dsmrreader" \
               --env "DJANGO_DATABASE_USER=dsmrreader" \
               --env "DJANGO_DATABASE_PASSWORD=dsmrreader" \
```

En matched het tussen beide containers.

Wanneer je de PG container in bridge draait zou ik ook geen poort mapping maken naar je host. Onderling moeten de containers met elkaar kunnen communiceren over bridge, zoals je in mijn voorbeeld ziet ook gewoon via de container naam.
```
               --env "DJANGO_DATABASE_HOST=dsmrdb" \
```

Kan je eens een willekeurige andere app met pg backend proberen te starten? Ik verwacht dat daar ook problemen bij zullen optreden.

Er is nog 1 ding dat ik kan bedenken, en dat is dat dit niet op jouw DSMR container staat:
```
--cap-add NET_ADMIN \
```

Ik zal de setup ook eens proberen te simuleren in de Synology Docker app, dat kan ook nog de oorzaak zijn dat het niet goed werkt.

**Comment by xirixiz** [comment]
Dit zou je ook nog kunnen doen, mijn files van een export van Synology importeren...

Je moet alleen ergens op de laatste regels van beide files het volledige pad naar jouw data folders aanpassen en een bridge netwerk aanmaken met de naam "proxy".

[dsmr.zip](https://github.com/xirixiz/dsmr-reader-docker/files/5956286/dsmr.zip)

**Comment by jelbo** [comment]
> Het is mij niet geheel duidelijk wat je precies bedoeld met "mijn POSTGRES_PASSWORD" daar is uniek.

Ik maakte in mijn postgres container geen gebruik van de optionele variabelen `POSTGRES_DB` en `POSTGRES_USER`, alleen van de verplichte `POSTGRES_PASSWORD`. Dit omdat ik de database en gebruiker zelf aanmaakte volgens de DSMR-reader documentatie.

Als je die DB en USER variabelen niet opgeeft wordt er een default database genaamd `postgres` en een default user genaamd `postgres` gemaakt, aldus de [documentatie](https://hub.docker.com/_/postgres):

> `POSTGRES_USER` This variable will create the specified user with superuser power and a database with the same name. If it is not specified, then the default user of postgres will be used.
> `POSTGRES_DB` This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of `POSTGRES_USER` will be used.

Ik heb nu de postgres container opnieuw aangemaakt met de variabelen zoals jij ze noemt. Alles gecleared, postgres data mapje leegemaakt. Ik krijg nog steeds een

```
[ INFO ] Verifying Database connectivity...
None
```
De `pg_isready` test slaagt. Ik kan op de postgres container niet meer controleren welke database er nu draait, omdat als ik de terminal start als `postgres` ik na een `psql` commando nu `psql: error: FATAL:  role "postgres" does not exist` krijg. De terminal starten met `dsmrreader` lukt niet.

Mijn variabelen voor de postgres container:
```
PATH               /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/13/bin
GOSU_VERSION       1.12
LANG               en_US.utf8
PG_MAJOR           13
PG_VERSION         13.1-1.pgdg100+1
PGDATA             /var/lib/postgresql/data
POSTGRES_DB        dsmrreader
POSTGRES_USER      dsmrreader
POSTGRES_PASSWORD  dsmrreader
```
Mijn variabelen voor de dsmr-reader container:
```
PATH                                       /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG                                       C.UTF-8
GPG_KEY                                    E3FF2839C048B25C084DEBE9B26995E310250568
PYTHON_VERSION                             3.9.1
PYTHON_PIP_VERSION                         20.3.3
PYTHON_GET_PIP_URL                         https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py
PYTHON_GET_PIP_SHA256                      6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2
DJANGO_SECRET_KEY                          dsmrreader
DJANGO_DATABASE_ENGINE                     django.db.backends.postgresql
DSMRREADER_SUPPRESS_STORAGE_SIZE_WARNINGS  True
DJANGO_DATABASE_NAME                       dsmrreader
DJANGO_DATABASE_USER                       dsmrreader
DJANGO_DATABASE_PASSWORD                   dsmrreader
DJANGO_DATABASE_HOST                       172.17.0.9
DJANGO_DATABASE_PORT                       5432
DSMRREADER_ADMIN_USER                      admin
DSMRREADER_ADMIN_PASSWORD                  admin
DATALOGGER_MODE                            standalone
SD_LOGLEVEL                                info
SD_USER                                    root
SD_GROUP                                   root
DATALOGGER_NETWORK_PORT                    8088
DATALOGGER_NETWORK_HOST                    192.168.1.20
DATALOGGER_INPUT_METHOD                    ipv4
```

**Comment by xirixiz** [comment]
Je weet dat de info vwb de db connectie klopt met de melding "none"?
https://stackoverflow.com/a/63250566

Anders zou je namelijk ook deze error krijgen:
https://github.com/xirixiz/dsmr-reader-docker/blob/f3f3ee09d8e89fc96ee91117fbaa9dc509dc8e0d/src/app/run.sh#L142

**Comment by jelbo** [comment]
Dat meen je niet, haha. Nee, dat wist ik niet. Als `None` zegt dat alles in orde is dan is heb ik nooit een probleem gehad.

Nouja, ik heb in elk geval wat meer ervaring opgedaan met postgres en Docker zal ik maar denken. Bedankt voor je hulp!

**Comment by xirixiz** [comment]
Hahaha, klopt, ineens zag ik het. Ik heb de rest inmiddels herschreven in de master branch. Dus in een volgende release krijg je duidelijk OK of NOK wanneer een DB server al dan niet beschikbaar is :)
