### ISSUE TITLE
It seems to run on postgres 13:latest?

### ISSUE THREAD

**Issue by rogierlommers** [xirixiz/dsmr-reader-docker#199]
Hey! Thanks for the nice container! I have a simple question: in the documentation, I see that postgres 12 is supported only.
Why is that? I tried running against v13 and it seems to work fine.

Curious about your thoughts...

**Comment by xirixiz** [comment]
Hey! Currently I`m using this as a base image ```python:3-alpine3.12```, and when you take a look at the package repository, you'll notice that only the Postgres 12.x client is available (https://pkgs.alpinelinux.org/packages?name=postgresql-client*&branch=v3.12)

A Postgres 13 backend will run fine with the Postgres 12 client, however backups/dumps will fail:
```
docker exec -ti dsmr bash -c 'PGPASSWORD=${DJANGO_DATABASE_PASSWORD} /usr/bin/pg_dump -h "${DJANGO_DATABASE_HOST}" -p "${DJANGO_DATABASE_PORT}" -d "${DJANGO_DATABASE_NAME}" -U "${DJANGO_DATABASE_USER}"'
```
I need to verify whether Alpine 3.13 is stable. If so, I can start implementing the Postgres 13 client.

**Comment by rogierlommers** [comment]
Ah, that explains. Indeed I have rolled my own backup strategy... thanks for all your hard work! Really appreciate it and love your image!

**Comment by xirixiz** [comment]
Thanks for the compliment, very much appreciated 👍. 

I just merged the PR for:
- Updated to Alpine 3.13 Docker base image
- Update Postgres client to version 13

So the next release (within an hour) will be based on the PG13 client.
