### ISSUE TITLE
dsmr commando's via Docker

### ISSUE THREAD

**Issue by Jeltel** [xirixiz/dsmr-reader-docker#2]
Ik wil een backup terugzetten vanaf mijn Pi en daar zijn enkele commando's voor:

http://dsmr-reader.readthedocs.io/nl/latest/faq.html#how-do-i-restore-a-database-backup

maar hoe voer ik deze uit via docker?

Bij pihole kun je het volgende commando gebruiken om te updaten:
`docker exec pihole pihole -up`
En dat commando komt aan in de container. Maar:
`docker dsmr sudo sudo -u postgres dropdb dsmrreader`
geeft geen resultaat.

Hoe moet ik te werk gaan?

**Comment by xirixiz** [comment]
Staat in de README... :)

dsmrdb in docker-compose is configured to use a docker volume. So when the application and docker containter have been removed, the postgres data still persists.

Also you could easily create a backup:
docker exec -t dsmrdb pg_dumpall -c -U postgres > /tmp/dumpdate +%d-%m-%Y""%H%M%S.sql

Or restore:
cat /tmp/<your_dump>.sql | docker exec -i dsmrdb psql -U postgres

**Comment by Jeltel** [comment]
Hmm ok.

Het leeggooien van de database ging niet zoals ik verwachtte. Het voeren van het commando 
`docker exec -i dsmrdb dropdb dsmrreader -U postgres  `
Zou de database moeten verwijderen, maar leek dat niet helemaal te doen.

Toen maar via de GUI de inhoud van de container dsmrdb gewist, opnieuw gestart en de backup teruggezet, terwijl de dsmr container uitstond:
`cat dsmrreader-postgresql-backup-Sunday.sql | docker exec -i dsmrdb psql -U postgres`

Daarna de container opnieuw gestart (via de GUI), maar helaas faalt de webinterface in een te korte tijd.

Later deze week hopelijk meer.

**Comment by xirixiz** [comment]
Nog verder gekomen?

**Comment by Jeltel** [comment]
Haha, nee. Er is een meisje geboren. Prioriteiten het, ;)

**Comment by xirixiz** [comment]
Gefeliciteerd in dat geval! Ik herken het, ik heb er twee rondlopen hier :)

**Comment by Jeltel** [comment]
Ik wil opnieuw beginnen, maar loop er tegenaan dat de database etc al bestaat in postgres. Natuurlijk handig dat als je de container weggooit de data bewaart blijft. Maar wáár staat de data dan wel? De dir /var/lib/postrgres bestaat bij mij niet.

Kortom waar staat de postgres data, zodat ik die weg kan gooien en helemaal opnieuw  beginnen?

**Comment by Jeltel** [comment]
Goed, ik ben helemaal opnieuw begonnen. Enkele aanpassingen inde docker-compose, zoals het definieren van een folder die wél bestaat.

Vervolgens de docker-compose laten starten. Alles lijkt goed te gaan. En dan de dsmr container uitzetten en via 
`cat /tmp/<your_dump>.sql | docker exec -i dsmrdb psql -U postgres`
de laatste backup van mijn pi dsrm terugzetten.

De dsmr container weer herstarten en de dsmr in de browser openen. Helaas zie ik dan geen data.

Punt is dat ik dus opnieuw wil starten, maar dat dus niet helemaal werkt.

Heb je zelf al eens een database teruggezet en wat zijn de stappen die je hebt gevolgd?

**Comment by xirixiz** [comment]
Zoals het beschreven staat heb ik ook een restore terug gezet.
Ik zal vanavond een backup maken en een restore uitvoeren om te kijken hoe dat verloopt.

Verder kun je docker volumes beheren met "docker volume <command>", bijvoorbeeld met docker volume ls. De postgres data staat namelijk in een docker volume. De fysieke data staat vaak in "/var/lib/docker/volumes".

**Comment by Jeltel** [comment]
Dat ziet eruit als een aardige beschrijving. Ga ik binnenkort proberen.

Kun je in de readme nog toevoegen dat voor synology users die priviliged op true gezet moet worden? Met de kanttekening erbij dat de dsmr docker dan root rechten heeft.

**Comment by Jeltel** [comment]
Hmm, precies jouw commando's gevolgd, maar nog steeds geen data in de interface. Vreemd. Later meer onderzoek.

**Comment by Jeltel** [comment]
Nogmaals geprobeerd met exact jouw commando's. Onderdeel van de output is:

'ERROR:  duplicate key value violates unique constraint "dsmr_weather_weathersettings_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY dsmr_weather_weathersettings, line 1
 setval
--------
      1
(1 row)

ERROR:  relation "auth_group_name_key" already exists
ERROR:  relation "auth_group_permissions_group_id_permission_id_key" already exists
ERROR:  multiple primary keys for table "auth_group_permissions" are not allowed
ERROR:  multiple primary keys for table "auth_group" are not allowed'

Oftewel niet alles is weg, klopt dat?

Helaas zie ik nog steeds geen data in de interface.
