### ISSUE TITLE
Problems with dsmrlogger network.

### ISSUE THREAD

**Issue by hemant5400z** [xirixiz/dsmr-reader-docker#204]
Hi,

I'm trying to change ip and port for the logger but logger keeps crashing.

Port and ip are ok as i can connect to them running on remote host ser2net. And output looks fine and works with domoticz and allowed for multiple connections.

Thanks,
Hemant

## Configuration

```yaml

Add your docker(-compose) config file here.

```

## Debug log

```text

Add your logs here.

```

**Comment by xirixiz** [comment]
Maybe @dennissiemensma can answer this better.

**Comment by dennissiemensma** [comment]
Ik begrijp niet helemaal wat er van ons verwacht wordt. Gisteren is de vraag ook al gesteld in dsmrreader en heb ik een mogelijke hint gegeven. Nu lijkt dat een uur later hier dan maar een issue is aangemaakt en het is mij niet duidelijk of mijn antwoord dan onvoldoende was of dat het nog niet gelezen is of dat de logfiles geen extra informatie hebben gegeven. https://github.com/dsmrreader/dsmr-reader/issues/1372#issuecomment-826115143

**Comment by hemant5400z** [comment]
Hoi,

Ik heb de vraag gesteld hier gesteld aangezien het om de docker versie ging. Omdat ik me niet realiseerde dat de andere de vraag die ik stelde over de standalone versie was.

Dus nogsmaals mijn probleem. db en applicatie beide in een docker. De remote p1 draait op een linux machine met ser2net port is bereikbaar telnet geeft de berichten die ik verwacht. Dus in de docker port en ip aangepast en de crashed de logger.

Ik zie in de docker log echter niet de reden.

Hemant

**Comment by dennissiemensma** [comment]
Ah helder, in beide gevallen zijn de logs het enige wat hier meer duidelijkheid kan geven. Sowieso over "wat" er precies crasht, want ik lees het als het `dsmr_datalogger` proces, klopt dat? En werkte het eerder wel? Want ook dat zijn goede aanwijzingen.

Als je in de logs geen duidelijke reden ziet, dan is het in dit geval goed om aan te wat er dan _wel_ in staat. Het kan zijn dat de hoofdlog van Supervisor geen details staan, maar in de sublogs van de processen zelf zou ten minste een oorzaak moeten staan. 

Had je ook deze logs bekeken? https://github.com/xirixiz/dsmr-reader-docker/issues/158#issuecomment-743008003

**Comment by hemant5400z** [comment]
Deze kan ook dicht.

Sorry was een issue met de firewall die geen verbinding naar buiten deed vanuit de docker op mijn synology.

Hemant

**Comment by dennissiemensma** [comment]
Top. Je kunt je eigen issues op Github zelf sluiten. Naast de "Comment" knop zit als het goed is ook een knop om te sluiten.

**Comment by xirixiz** [comment]
@dennissiemensma bedankt voor de verheldering. Om heel eerlijk te zijn @hemant5400z kon ik er geen touw aan vastknopen, vandaar ik @dennissiemensma om hulp heb gevraagd voor dit topic. 

Tip voor de volgende keer, geef een heldere omschrijving en lever hetgeen aan er gevraagd wordt (logfiles en configuratie bijvoorbeeld), alleen dan kunnen mensen jou goed helpen. 

Maar fijn dat het issue iig is verholpen.
