### ISSUE TITLE
Nginx ENABLE_NGINX_SSL or ENABLE_HTTP_AUTH configuration does not work anymore

### ISSUE THREAD

**Issue by arjanvanderveen** [xirixiz/dsmr-reader-docker#205]
Settings the  environment variable `ENABLE_NGINX_SSL=true` results in a startup error that the file `/etc/nginx/sites-available/dsmr-webinterface` can't be found.

Changing this filename in the /app/run.sh to **`/etc/nginx/http.d/dsmr-webinterface.conf`** solves the problem

**Comment by xirixiz** [comment]
Thanks for your input! I'll fix it Today

**Comment by xirixiz** [comment]
Fixed in 2021.05.01
