### ISSUE TITLE
DSMR_Backend continues to crash

### ISSUE THREAD

**Issue by maxxie85** [xirixiz/dsmr-reader-docker#206]
Hi Xirixiz,

I noticed increades CPU usage on my server and saw it was caused by dsm-reader-docker. Inspecting the log files shows that the dsmr_backend process exits (code 0) and then restarts about every 10 seconds.

Host is a debian 10 VM with all packages up to date (at this time of writing).

DSMR-reader-docker version is tagged to latest which now matches latest-2021.05.02-amd64
For the database I'm running the latest official postgress 11 image.

I would like to help you identify this issue if you require.

**Comment by JayOne73** [comment]
I can confirm this behaviour on two installs, one on Synology (Docker) and one on a LXC (Proxmox, Docker).

**Comment by xirixiz** [comment]
I'll look into it Tonight. Did you check the changelog of dsmr reader? Maybe it's related to the latest release (released Yesterday).

**Comment by xirixiz** [comment]
Thanks for helping out! Do you have MQTT enabled? I didn't have any issue, but maybe that's because I disabled MQTT.

**Comment by xirixiz** [comment]
You can also update it directly in the database if you'd like to:

Update:
```
echo "UPDATE dsmr_mqtt_mqttbrokersettings SET qos = 2;" | docker exec -i dsmrdb psql -U dsmrreader -d dsmrreader
```

Verify:
```
echo "SELECT * from dsmr_mqtt_mqttbrokersettings;" | docker exec -i dsmrdb psql -U dsmrreader -d dsmrreader
```
