### ISSUE TITLE
Containers fails on systems without ttyUSB0

### ISSUE THREAD

**Issue by ju5t** [xirixiz/dsmr-reader-docker#21]
https://github.com/xirixiz/dsmr-reader-docker/commit/04a76979d8749e590fa5015da91adffab3cf0994 and https://github.com/xirixiz/dsmr-reader-docker/commit/2da47a3399012a919e78caf380844e01369989c2 introduced a breaking change for those run separate servers.

This needs to be undone or there needs to be a check if it exists before trying to change permissions.

**Comment by xirixiz** [comment]
Thanks! Fixed... 
if [ -e '/dev/ttyUSB0' ] ; then sudo chmod 666 /dev/ttyUSB* ; fi
