### ISSUE TITLE
Iframe settings django

### ISSUE THREAD

**Issue by siemon-geeroms** [xirixiz/dsmr-reader-docker#211]
## Information

Hi,

I'm running dsmr using this docker img without any issue. However I would like to implement below fix to be able to run dsmr in an iframe whitin home assistant. When I alter the file via the console everything is working fine. However when recreating the container this setting is obviously lost. I tried to map this folder to a folder on my pi so it is persistent but if I do this the folder is not getting populated and as re sult dsmr will not start.  Is it possible to add optional parameters so we can set this setting via compose or make it so we can map the folder?  

https://github.com/dsmrreader/dsmr-reader/issues/344#issuecomment-315523564_

Thanks in advanced

**Comment by xirixiz** [comment]
Hi, added support, creating a new release....

**Comment by xirixiz** [comment]
Docker image ready ```xirixiz/dsmr-reader-docker:latest```

Tag:
2021.06.01

Please verify.

**Comment by siemon-geeroms** [comment]
Hi,

I can confirm this is now working! thanks for the quick fix!
