### ISSUE TITLE
Update 3.6 to latest 4.x on Raspberry Pi 3 in docker

### ISSUE THREAD

**Issue by Kees85** [xirixiz/dsmr-reader-docker#212]
After migrating my DSMR docker 3.x to latest 4.x on my NUC went fine, I am trying to upgrade another DSMR docker 3.6 to latest 4.x on a Raspberry Pi 3. 
After several attempts, I am not sure anymore if I understand the needs correctly, so I would like to clarify some things for myself:

- I am not sure which newer image I should use. Using now: xirixiz/dsmr-reader-docker:arm32v6-v3.6.0. As it runs on a Raspberry Pi 3, I guess xirixiz/dsmr-reader-docker:latest should should work?
- Should updating the docker image in the docker compose and recreate the container enough to update DSMR 3.x to latest 4.x ?
- Can I still use Postgres 10.5? If not, how to upgrade? Simply pull 13 image?

**Comment by xirixiz** [comment]
Appologies for the late reply, I missed it completely:

- Use xirixiz/dsmr-reader-docker:latest. It auto picks the correct Docker image for your architecture
- Updating the Docker image and destroy and create a new container should update your environment properly. However, please read the DSMR Reader documentation to make sure no "special" actions are required. My guess is that it will all upgrade fine.
- You can still use postgres 10.5, but it would be better to upgrade that as well. I would do that only after updating DSMR reader. Notes on how to upgrade Postgres can be found in the README.md in this repository.

Good luck!
