### ISSUE TITLE
Run container in docker host network nginx (exit status 1; not expected)

### ISSUE THREAD

**Issue by michelotten** [xirixiz/dsmr-reader-docker#213]
Hi,

I'm trying to run this docker container in the docker host network instead of bridge network.
Using following settings in my docker compose file.
I manually changed postgres port in the postgres settings file to 5433.
Connection to Postgres seems to work according to DSMR log. But I get error message that nginx is exiting over and over again. See below copy-paste of logs. I'm not able to reach DSMR via port 777. Any idea what could be wrong?
```
# Postgres
  Postgres2:
    container_name: Postgres2
    image: postgres:12.4
    restart: unless-stopped
    network_mode: host
    volumes:
      - /volume1/docker/postgres2:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_db=dsmrreader
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=xxxxxx
# DSMR
  DSMR2:
    container_name: DSMR2
    image: xirixiz/dsmr-reader-docker:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /volume1/docker/dsmr2:/dsmr/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      # - DSMRREADER_ADMIN_USER=admin
      # - DSMRREADER_ADMIN_PASSWORD=xxxxxx
      - DJANGO_DATABASE_NAME=dsmrreader
      - DJANGO_DATABASE_USER=dsmrreader
      - DJANGO_DATABASE_PASSWORD=xxxxxx
      - DJANGO_DATABASE_HOST=127.0.0.1
      - DJANGO_DATABASE_PORT=5433
      # - DJANGO_TIME_ZONE=Europe/Amsterdam
      # - VIRTUAL_HOST=localhost
    # devices:
      # - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - Postgres
```
```
[ INFO ] DSMR release: v4.16.3,

[ INFO ] Removing existing PID files...,

[ INFO ] Creating log directory...,

[ INFO ] Setting architecture requirements...,

[ INFO ] X64 Architecture,

[ INFO ] Enable IFrame.,

[ INFO ] Fixing /dev/ttyUSB* security...,

[ INFO ] Verifying if the DSMR web credential variables have been set...,

[ INFO ] Verifying database connectivity to host: 127.0.0.1 with port: 5433...,

[ INFO ] Database connectivity successfully verified!,

[ INFO ] Running post configuration...,
Operations to perform:,
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions,
Running migrations:,
  No migrations to apply.,
,
0 static files copied to '/var/www/dsmrreader/static', 562 unmodified.,
Updating password of superuser "admin",
Deactivating any other existing superusers,

[ INFO ] Checking for NGINX SSL configuration...,

[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...,

[ INFO ] Checking for HTTP AUTHENTICATION configuration...,

[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...,

[ INFO ] Configuring DSMR in standlone datalogger mode....,

[ INFO ] Starting supervisord...,

[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log,
2021-08-29 16:12:52,882 INFO Set uid to user 0 succeeded,
2021-08-29 16:12:53,196 INFO RPC interface 'supervisor' initialized,
2021-08-29 16:12:53,198 INFO supervisord started with pid 19,
2021-08-29 16:12:54,201 INFO spawned: 'dsmr_backend' with pid 21,
2021-08-29 16:12:54,205 INFO spawned: 'dsmr_datalogger' with pid 22,
2021-08-29 16:12:54,209 INFO spawned: 'dsmr_webinterface' with pid 23,
2021-08-29 16:12:54,212 INFO spawned: 'nginx' with pid 24,
2021-08-29 16:12:55,232 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-08-29 16:12:55,233 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-08-29 16:12:55,233 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-08-29 16:12:56,733 INFO exited: nginx (exit status 1; not expected),
2021-08-29 16:12:56,737 INFO spawned: 'nginx' with pid 26,
2021-08-29 16:12:57,281 INFO success: dsmr_webinterface entered RUNNING state, process has stayed up for > than 3 seconds (startsecs),
2021-08-29 16:12:57,781 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by xirixiz** [comment]
Hi,

Currently I cannot tell why nginx exits. You have two choices here:
- Put the container in debug mode
- Check the nginx logfiles (login to the container `docker exec -ti DSMR2 bash`). 

The path for logfiles are shown on container startup.

**Comment by michelotten** [comment]
Thanks for the feedback.
I've tried enabling debug mode by adding variable 'DSMRREADER_LOGLEVEL=DEBUG'.

Logfiles are stored within my container here: /var/log/supervisor, there I can find three files:
- DSMR_backend.log
- DSMR_datalogger.log
- DSMR_webinterface.log
Both in none of these log files there seems to be anything logged related to NGINX, correct?

**Comment by xirixiz** [comment]
Sorry, this is the correct location

bash-5.1# ls -al
total 8
drwxr-xr-x    2 nginx    nginx         4096 Jun  7 11:33 .
drwxr-xr-x    5 root     root          4096 Jun 29 18:34 ..
lrwxrwxrwx    1 root     root            11 Jun  7 11:33 access.log -> /dev/stdout
lrwxrwxrwx    1 root     root            11 Jun  7 11:33 error.log -> /dev/stderr
bash-5.1# pwd
/var/log/nginx

**Comment by xirixiz** [comment]
I see a new release comming :). Let me check some things whether this is easy to implement.

**Comment by Caroga** [comment]
@michelotten The way you could achieve this, on paper, is as follows:

- Create a network outside of your compose file, e.g.:  `docker network create dsmr-mqtt` 
- In your compose files for DSMR reader, and Mosquitto, you add the network as an external network (example below): https://docs.docker.com/compose/compose-file/compose-file-v3/#networks 
- At the individual services you must add the network as well.
- You must expose the service port of Mosquitto.

Example files (I wrote this just now, so I skipped a lot but the basics should be in okay):

home-assistant docker file:
```
version: '3.8'
services:
  homeassistant:
    image: homeassistantimage
    # network mode host, so no port configuration and no internal docker network. 
    # this won't be a problem because in theory you can resolve the mqtt server with localhost:1883
    network_mode: host
```

```
version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto
    # Network definition is referring to the mosquitto network under the networks key further down below.
    # This configuration removes the default internal network, so if you have other services in this file than they should
    # get a new default network assigned manually. 
    networks:
      - mosquitto
      # - default
    ports:
      - "1883:1883"
      - "9001:9001"
networks:
  # default:
  mosquitto:
    external: true
```

```
version: '3.8'
services:
  mqtt:
    image: dsmrdockerimage
    # Same as above, this service is now connecting to the externally defined mosquitto network. Any default networks 
    # are now removed so should be added manually if needed.
    networks:
      - mosquitto
networks:
  mosquitto:
    external: true
```

The above configuration should make your dsmr instance able to connect with MQTT via `mqtt:1883` where `mqtt` is the service name from mosquitto. Home assistant should be able to connect with MQTT via localhost:1883 or externalip:1883. I also run Home Assistant on network mode host due to mDNS resolve issues. 

I wrote this pretty quick so if it doesn't work instantly then please feel free to reply and I can help you look into this. 

Good luck, hope this works!

**Comment by michelotten** [comment]
Thanks a lot @Caroga, will try this out soon!

**Comment by Caroga** [comment]
Hi @michelotten, any luck with this? If not, my offer stands to help you out. I suspect you are from the Netherlands as well, so I could do a "live" session with you if you'd like.

**Comment by michelotten** [comment]
Correct, I'm from NL. Currently enjoying a holiday, so I don't have access to my computer. During next weekend I'll try your suggestion and let you know the outcome.
Thanks a lot! ;)

**Comment by xirixiz** [comment]
Let me know if you need my assistance as well once you're back 👍

**Comment by michelotten** [comment]
With the help of @Caroga I've been able to connect everything together!
DSMR is now connected to my MQTT broker and also HomeAssistant can read these messages.
Now waiting for some hours for the Energy dashboard in HA to fill :)

Thanks again guys!
