### ISSUE TITLE
Update interval to Homeassistant changes

### ISSUE THREAD

**Issue by Ivar247** [xirixiz/dsmr-reader-docker#214]
Hi All,

## Problem definition
After integrating DSMR Reader Docker in The supervisor of Home Assistant  all sensor integrations in HA is updating every 5 seconds. After a couple of days the update interval changes resulting in wrong calculations combining different sensor data.

After 1) Rebuilding DSMR Reader and 2) Restarting TimescaleDB the sensor update every 5 seconds again.
You can this happening in the attached screenshot. (please don't mind the units of each variable they are not labelled correctly)

How can i make sure the sensor update interval stays within 5 seconds ? With previous builds i didn't have this issue of intervals changing.

Thanks a lot for your support.

Best regards,
Ivar Engel

-->

## Setup/Architecture information
ODROID-N2+
-->

## Version of the Docker image
-DSMR Reader Current version: 0.5.0
-TimescaleDB Current version: 1.1.6
-Running in Supervisor in Home Assitant Versioncore-2021.8.8

## Debug log

![Screenshot 2021-09-08 131834](https://user-images.githubusercontent.com/79230092/132500289-6ebcacb4-4766-4ec5-b2f2-b5a0a61d1fd8.png)

Add your logs here.

```

**Comment by xirixiz** [comment]
Hi, there are multiple components involved.

I've created the DSMR Reader Docker image, which doesn't have an intergration with Home Assistant.
There is another component that intergrates DSMR Reader Docker in Home Assistant (https://github.com/sanderdw/hassio-addons/tree/master/dsmr_reader).

I`m closing this issue as this is related to the intergration with Home Asisstant, which I didn't develop and  don't know anything about :). Good luck!

**Comment by Ivar247** [comment]
Thanks for you prompt feedback ! Will follow up there
