### ISSUE TITLE
Run DSMR docker on Raspberry Pi Zero W - ARM32v6

### ISSUE THREAD

**Issue by Caroga** [xirixiz/dsmr-reader-docker#215]
## Information
I tried deploying the dsrm image on a RPI Zero W but the arm32v6 builds are deprecated. It would really be helpful to bring these back. I kindly ask your consideration for this but also respect your decision if you would like to keep this deprecated.

**Comment by xirixiz** [comment]
Hi Caroga, I`ll try to create a dev release so you can test it.

You could also try to build it yourself if you'd like to. It's not that hard, but some knowledge and Linux / Mac OS is required.

**Comment by xirixiz** [comment]
docker pull xirixiz/dsmr-reader-docker:latest-2021.09.01-arm32v6

**Comment by Caroga** [comment]
Thank you for this!
