### ISSUE TITLE
Latest tag niet bijgewerkt, andere wel?

### ISSUE THREAD

**Issue by niekniek89** [xirixiz/dsmr-reader-docker#217]
Goedemorgen,

Ik zie dat inmiddels 4.17 een aantal dagen uit is.
Kan het zijn dat alleen de "latest" tag niet is bijgewerkt, of doe ik iets verkeerd?
![latest](https://user-images.githubusercontent.com/48858098/134485784-5a5524fc-8cae-4412-a756-7d55e311b61e.jpg)

**Comment by xirixiz** [comment]
Klopt :). latest is nog steeds latest. Maar de laatste latest is eigenlijk een development release. Domme fout van mij tijdens het mergen van branches. Lang verhaal, maar ik heb 4.17 nog niet getriggerd... al dacht ik van wel. Ik ga dat nu meteen doen en dan zou 4.17 over een uurtje beschikbaar moeten zijn.

**Comment by niekniek89** [comment]
Helemaal top!

**Comment by xirixiz** [comment]
Done

**Comment by niekniek89** [comment]
> Done

Dat is snel, getest en werkt!
![dsmr](https://user-images.githubusercontent.com/48858098/134491914-3e722671-9b5b-4c26-80b3-9edd15f10f8a.jpg)

**Comment by xirixiz** [comment]
Grotendeels geautomatiseerd  ;)
