### ISSUE TITLE
Upgrade Postgres database from version 10 to version 13

### ISSUE THREAD

**Issue by poerlemans** [xirixiz/dsmr-reader-docker#218]
## Setup/Architecture information

Dsmr and dsmrdb are in docker container. Procedure as described by xirixiz.

## Version of the Docker image

I,m applying the most recent versions.

## Configuration

```yaml

Add your docker(-compose) config file here.

```
Docker-compose file:

  dsmr:
    image: xirixiz/dsmr-reader-docker 
    container_name: dsmr 
    depends_on: 
      - dsmrdb 
    cap_add: 
      - NET_ADMIN 
    links: 
      - dsmrdb 
    restart: always 
    volumes: 
      - /etc/localtime:/etc/localtime:ro 
      - ./dsmr_backups:/dsmr/backups
    environment: 
      - SD_LOGLEVEL=info 
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - DJANGO_DATABASE_HOST=dsmrdb
      - DJANGO_DATABASE_PORT=5432 
      - DJANGO_DATABASE_USER=dsmrreader 
      - DJANGO_DATABASE_PASSWORD=dsmrreader 
      - DJANGO_DATABASE_NAME=dsmrreader 
      - SD_USER=root 
      - SD_GROUP=root 
      - DSMR_USER=admin 
      - DSMR_EMAIL=root@localhost 
      - DSMR_PASSWORD=admin 
      - VIRTUAL_HOST=localhost
      - ENABLE_IFRAME=true
    ports: 
      - "7777:80" 
      - "7779:443" 
    devices: 
      - /dev/serial/by-id/usb-FTDI_P1_Converter_Cable_P1YPKTMO-if00-port0:/dev/serial/by-id/usb-FTDI_P1_Converter_Cable_P1YPKTMO-if00-port0 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  dsmrdb:
    image: postgres:10.5-alpine (in case of postgres 13 this is adapted
    container_name: dsmrdb 
    restart: always 
    volumes: 
      - ./dsmrdb:/var/lib/postgresql/data 
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - TZ=Europe/Amsterdam 
      - PG_TZ=Europe/Amsterdam 
      - POSTGRES_USER=dsmrreader 
      - POSTGRES_PASSWORD=dsmrreader 
      - POSTGRES_DB=dsmrreader 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

## Describe the bug
For upgrading from version 10 to 13 I'm following the explanation in the readme:
- stop the dsmr reader container ONLY
- backup the dsmrdb database (see "Backup and restore mechanism" in the README.md)
COMMAND: docker exec -t dsmrdb pg_dumpall -c -U dsmrreader > dsmrreader.sql
- validate the dsmrdb backup!
- you could also consider to "vacuum" the database following "DSMR Reader - Database cleanup/vacuum" in the README.md.
- stop and remove the dsmrdb container
- rename the db folder that is mounted in the Docker container, containing the database data, to something else (.old, or whatever you like)
- create a new db folder with the name used to mount the folder in the Docker container (so, the folder name just before you renamed it in the previous step)
- update docker-compose or your docker run command with the new postgres version
- be aware the client package has to be compatible with the postgres version you're going to use. Check here which version is within the dsmr image. The Docker bas image is based on python:3-slim-buster.
- start dsmrdb (it's an empty but valid postgres db now).
- restore the database backup created in step 2 (see "Backup and restore mechanism" in the README.md)
COMMAND: cat dsmrreader.sql | docker exec -i dsmrdb psql -U dsmrreader
- restart the dsmrdb container
- start the dsmr container

I observe that the database can be read by DSMR-reader (also data from the past can be read) but that actual data are not written in the database.
In the Windows program WinSCP I observed that the owner of the old (version 10) database is: "70" and that the owner of the new database is "systemd-coredump".
What can be the reason that data are not written in the new (version 13) database??
## Debug log

```text



```

**Comment by xirixiz** [comment]
Sounds you executed all steps correctly. Did you also take a look at the postgres and/or dsmr container logfiles?
I suppose in one of the logfiles it should show what the error is, most probably on the dsmr container side.

**Comment by xirixiz** [comment]
Currently upgrading from 12 to 13, I`ll let you know the outcome

**Comment by xirixiz** [comment]
Working like a charm at my side. I suppose the problem is permissions.
For me with PG13 the user is still id 70...

Do you use: postgres:13-alpine?

**Comment by poerlemans** [comment]
Problem solved!
Changing "image: postgres:13" to "image: postgres:13-alpine" in the docker-compose file did the trick. I was a little bit confused by the docker-compose example file in the code-section.

**Comment by xirixiz** [comment]
Hehehe, yes, images could use a different UID/GID based on the distro used or set by the creator of an image.
Anyway could it has been solved.
