### ISSUE TITLE
Tip: Formulieren voor Github issues!

### ISSUE THREAD

**Issue by dennissiemensma** [xirixiz/dsmr-reader-docker#220]
Hey, ik kwam er net achter dat er blijkbaar deze feature van Github (al [een tijdje](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) blijkbaar) beschikbaar is voor publieke repo's. 

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Net doorgevoerd voor DSMR-reader en ik denk dat het jou ook wel kan helpen, gezien jij net als ik ook vaak dezelfde informatie aanbiedt als hulp en/of achtergrondinformatie zoekt bij (nieuwe) issues hier.

Dit is precies wat ik zelf al langere tijd zocht, namelijk:
- Statische content kunnen tonen bij issues, inclusief links, zonder dat het half in een codetaal staat voor de gebruiker.
- Gestructureerd informatie kunnen vragen (je kunt zelfs checkboxes maken die verplicht zijn oid).

### Voorbeeld
- https://github.com/dsmrreader/dsmr-reader/issues/new/choose

### Testresultaten van issues aanmaken via formulieren
- https://github.com/dennissiemensma/playground/issues?q=is%3Aissue+is%3Aclosed

Wellicht ook leuk voor jou om keertje zelf mee te spelen!

**Comment by xirixiz** [comment]
Hoi Dennis, een wat late reactie maar dat ziet er inderdaad goed uit, bedankt voor het delen!
Ik ga er komend weekend eens induiken!
