### ISSUE TITLE
Te veel onverwerkte telegrammen

### ISSUE THREAD

**Issue by niekniek89** [xirixiz/dsmr-reader-docker#222]
### Issue

Hallo,

Sinds eind van de middag krijg ik de melding:

Te veel onverwerkte telegrammen: 1135   (3 uur geleden)
Beide containers (DSMR & DSMRDB) herstart, lijkt helaas niet terug te lopen.
Zie ook geen errors o.i.d. in de logs
Inmiddels ook dit verwijderd uit de docker compose file (en daarna beide containers weer uitgerold):

etc/localtime:/etc/localtime:ro

het is gekomen nadat de VM (waarop docket draait) +- 1 uur is uit geweest.

![45F96191-2C2F-4EBE-86CD-7150E8642F2E](https://user-images.githubusercontent.com/48858098/138922018-d2d9a7a4-0ced-4fd4-a553-a5c56f3bf3f2.jpeg)

Of ben ik te ongeduldig (na 2 uur)? Of word dit alsnog verwerkt?

### Which version has the issue?

DSMR-reader v4.19

### What was the last working version?

DSMR-reader v4.19

### What type of installation are you running (architecture)?

Linux VM met docker (docker compose)

**Comment by niekniek89** [comment]
Ik dacht dat het opgelost was, maar komt steeds vaker voor.
Nu is dit getriggerd door een reboot van mijn Linux server (waar docker op draait).
Is het nog iets wat ik kan checken wat er fout gaat?
![DSMR1](https://user-images.githubusercontent.com/48858098/139810453-58e97d93-ec47-41db-a725-b66e32e1fbba.jpg)
![DSMR2](https://user-images.githubusercontent.com/48858098/139810456-083f372e-3702-4910-864a-53bdf2e4a507.jpg)

**Comment by xirixiz** [comment]
Het is vreemd dat de datalogger een herstart vereist. Is de logging van de container ook de logging wanneer de melding in DSMR reader staat?

Je kan ook even kijken of de data ook echt netjes binnen blijft komen (wat zo te zien wel het geval is)
```
sudo apt-get install cu minicom
sudo cu -l /dev/ttyUSB0 -s 9600 --parity=none
```

Kan je de output van "lsusb" ook eens delen?

Verder zie ik het loglevel op ERROR staan, kan je dat eens op DEBUG zetten?

**Comment by niekniek89** [comment]
De melding uit de logging kwam naar voren toen ik de dsmr container herstart had.
Dit bood geen oplossing.
Er komt wel daadwerkelijk data binnen (dat zie ik inderdaad gebeuren).

Inmiddels heb ik heel de VM herstart, en zijn alle foutmeldingen weer verdwenen (en heeft hij alle niet-verwerkte telegrammen alsnog verwerkt).

root@vm02:/home/docker# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 0403:6001 Future Technology Devices International, Ltd FT                                                                                          232 Serial (UART) IC
Bus 002 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 002 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
root@vm02:/home/docker#

**Comment by xirixiz** [comment]
Het lijkt ook meer op een issue met de VM of het host OS van de VM. 
Wat ik begrijp is namelijk dat een eenvoudige herstart van de container het issue niet oplost, alleen wanneer de volledige VM herstart wordt, maar goed dat kan dan vanalles zijn vrees ik...

**Comment by xirixiz** [comment]
Late reactie, maar wanneer tijden niet goed staan kan dat zeker voor vreemde problemen zorgen.
Laten we even afwachten wat het resultaat is en weer verder kijken wanneer dat nodig is :)

**Comment by niekniek89** [comment]
Ook een late reactie vanuit mij.
Inmiddels draaien de containers (dsmr & dsmrdb) 8 dagen continu.
Elke dag om 21:00 maakt Nakivo nog steeds een backup van de Linux VM naar mijn NAS.
Zie vooralsnog het issue niet meer terug komen, alles lijkt netjes verwerkt te worden.

Ik heb dan ook de VM niet meer uit gehad (wel de tijd settings aangepast, direct na de laatste issue).
We gaan het zien, zal het issue voor nu sluiten.
Mocht het terug komen, zal ik hem aanvullen.
Bedankt voor je hulp tot nu toe!!!
