### ISSUE TITLE
Latest still not working

### ISSUE THREAD

**Issue by canedje** [xirixiz/dsmr-reader-docker#233]
### Issue

Hello Bram.

I don't know if your reading remarks on closed items.
If you do: sorry for this issue

But ons issue #230 
The latest repository still not working. (see issue 230)

the: xirixiz/dsmr-reader-docker:amd64-development
is still working.

### Which version has the issue?

latest

### What was the last working version?

xirixiz/dsmr-reader-docker:amd64-development

### What type of installation are you running (architecture)?

AMD64

### Anything in the logs that might be useful?

```txt
see #230
```

**Comment by xirixiz** [comment]
This is a bit odd as currently you're the only one still facing this issue :).

However, I`m rebuilding a development image with a lot of security related items adjusted/removed.
Please pull the image in about half an hour (development one) and check if it's working. If so, I`ll merge it to "production"

**Comment by canedje** [comment]
Strange indeed.
I will check.

**Comment by canedje** [comment]
I just installed the newest amd64-development.
It is working fine

**Comment by canedje** [comment]
Bram. 
I just tried your newest latest again.
It don't work. I realy don't understand.
![image](https://user-images.githubusercontent.com/23150947/146687032-b17def3a-a1f3-457b-8602-657ac557e37a.png)

![image](https://user-images.githubusercontent.com/23150947/146687052-ca5460bd-d6ad-46fc-9fc0-701564f27e12.png)

Do you see something wrong in my Docker build?

**Comment by canedje** [comment]
There must be something wrong with my docker setup.
I can remember the last time trying going back from a fixed release to latest also didn’t work
