### ISSUE TITLE
Aantal vraagjes

### ISSUE THREAD

**Issue by Martinvdm** [xirixiz/dsmr-reader-docker#24]
Superproject, dat eerst gezegd. een aantal vraagjes:

1. Ik krijg geen readings te zien. Dit terwijl als ik met docker exec de container in ga en een cu doe dan zie ik met v2 readings voorbij komen. ttyUSB0 is netjes doorgezet, toch geen readings.

2. restore van een backup geeft een error op de laatst import met cat.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/dsmrdb/json: dial unix /var/run/docker.sock: connect: permission denied

dus met docker exec de container in gegaan en hier de imort gedaan middels:
cat ./dsmrreader-postgresql-backup-Monday.sql | psql -U postgres
dit werkt wel, maar na reboot, geen gegevens.

3. de configuratie in DSMR reader lijkt niet onthouden. is het niet handig een volume te mappen voor de config file?

thanks

**Comment by Martinvdm** [comment]
Het lijkt er op dat in de dsmrdb iets niet goed gaat.
````
2018-07-05 21:25:42.734 UTC [24] LOG:  database system was shut down at 2018-07-05 21:25:31 UTC,
2018-07-05 21:25:42.745 UTC [1] LOG:  database system is ready to accept connections,
2018-07-05 21:26:09.772 UTC [31] FATAL:  password authentication failed for user "-d",
2018-07-05 21:26:09.772 UTC [31] DETAIL:  Role "-d" does not exist.,
	Connection matched pg_hba.conf line 95: "host all all all md5",
````

**Comment by xirixiz** [comment]
Helaas is de opbouw van de Dockerfile (zeer) rommelig. Ik zal eens kijken of ik dat kan verbeteren. Zelf gebruik ik DSMR reader eerlijk gezegd ook niet meer, dus vandaar ik er ook minder aandacht aan schenk. Ik gebruik Home Assistant met een component om de waarden uit te lezen.

Maar goed, ik kom iig nog terug op jouw vragen en probeer het te verbeteren/fixen voor je.

**Comment by Martinvdm** [comment]
Zou super zijn. Mooiste is als ik het iig werkend kan krijgen. Meermaals de container opnieuw aangemaakt maar blijf maar 0 readings krijgen terwijl middels cu wel readings in de container doorkomen. Tevens de database -d error zoals bovenstaand. Wellicht heeft dat ook iets met de readings te maken omdat die geen database connectie heeft wellicht?

Ook een mogelijkheid om, bijv via een environment variabele de Timezone vand e container goed te zetten zou handig zijn denk ik. Maargoed eerst maar eens werkend krijgen ;)

Bedankt

**Comment by Martinvdm** [comment]
Ik heb het iig werken nu. CRC uitgezet in de data Reading. Blijft over de user -d error en idd wellicht verbeteringen van de docker file. Voor oa Timezone en volume voor de config wellicht. 
Bedankt

**Comment by ju5t** [comment]
2. Hoe doe je de restore? Volg je de handleiding op [readthedocs](https://dsmr-reader.readthedocs.io/nl/latest/faq.html?highlight=restore#how-do-i-restore-a-database-backup)? In principe heeft het Docker-image geen invloed op hoe de backup wordt aangeroepen. Als je database geen connectie heeft kun je dit zien in de logs `docker logs -f dsmr`. Als er geen verbinding is start de container niet.
3. Welke configuratie bedoel je precies? De verbinding naar de database wordt geconfigureerd via je environment: [docker-compose.yaml#L11](https://github.com/xirixiz/dsmr-reader-docker/blob/master/docker-compose.yaml#L11). Alle andere instellingen staan in de database en de database staat in de voorbeeld `docker-compose.yml` in een volume.
4. Je kunt de timezone al instellen met de `TZ` environment variabele. Dit werkt voor de meeste Docker images. In `docker-compose.yml` is het een kwestie van `- TZ=Europe/Amsterdam` toevoegen.

**Comment by Martinvdm** [comment]
Het gaat al stukken ter inmiddels. Config blijft idd in de db staan. TZ zal ik definiëren. Krijg wel af en toe errors dat supervisord niet meer wil starten omdat te vaak opnieuw gestart is. Moet de container dan opnieuw builden en dan weekt het weer
