### ISSUE TITLE
/app/run.sh: No such file or directory

### ISSUE THREAD

**Issue by SanderGit** [xirixiz/dsmr-reader-docker#242]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Same issue as #149 since yesterday night the container was updated.

```
/bin/bash: line 1: /app/run.sh: No such file or directory
[cmd] /bin/bash exited 127
```

Recreating the container (with tag being Latest) does not help.

### Expected behaviour

That it keeps running, obviously

### Actual behaviour

Stops trying to start

### Steps to reproduce

1. Try to start the container again

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc version: 31cc25f16f5eba4d0f53e35374532873744f4b31
 init version: ed96d00 (expected: de40ad0)
 Security Options:
  apparmor
 Kernel Version: 4.4.180+
 Operating System:  (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.54GiB
 Name: SynologyDiskStation
 ID: 4FD3:SEYV:VKHB:CIW5:2VU4:TXIN:BOLW:A622:4JEZ:VZKM:BRXL:6C7U
 Docker Root Dir: /volume1/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Version

* Docker compose version (type `docker-compose --version`):  docker-compose version 1.28.5, build 324b023a
* System info (type `uname -a`): Linux SynologyDiskStation 4.4.180+ #42218 SMP Fri Sep 24 02:41:48 CST 2021 x86_64 GNU/Linux synology_geminilake_920+

### Docker compose

```yaml
N/A
```

### Container logs

```
Starting DSMR Reader - webinterface...
[services.d] done.
/bin/bash: line 1: /app/run.sh: No such file or directory
[cmd] /bin/bash exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by xirixiz** [comment]
Hi, maak je ook gebruik van portainer? Ik heb de laatste versie zonder problemen draaien op een Syn 918+.
Mogelijk dat portainer dus het issue veroorzaakt.

```
Actually when using a solution like Portainer, it sets the COMMAND automatically from the image. Yet, if it's already set and you update the docker image and this changes, then it does not change it in the container automatically.
The same with ENV's, those should not be changed in your images afterwards, as you change the values in the ENV's. Those are not changing dynamically.
```

Zag dit. Anders even de config uit portainer verwijderen en opnieuw aanmaken.

```
COMMAND, of eigenlijk het ENTRYPOINT is nu namelijk
```
ENTRYPOINT ["/init"]
```

**Comment by SanderGit** [comment]
Rolled back to amd64-2021.12.05 provides a workaround.

**Comment by SanderGit** [comment]
Inderdaad gebruik ik ook portainer, maar de update is door Ouroboros binnengehaald.
Na een rollback naar 2021.12.05 zag ik dat het entrypoint wijzigde naar /init. Ik kan nu weer 'latest' draaien. Issue is verholpen, dank voor de snelle reactie!
