### ISSUE TITLE
DEBUG logging enabled

### ISSUE THREAD

**Issue by JPJJansen** [xirixiz/dsmr-reader-docker#245]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Since the latest version the debug logging is enabled. I cannot find how to turn it off. 

Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html

### Expected behaviour

Debug logging is turned off

### Actual behaviour

Debug logging is turned on

### Steps to reproduce

Updated to the latest image

### Docker info

```yaml
-
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):
-

### Docker compose

```yaml
-
```

### Container logs

Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html

**Comment by xirixiz** [comment]
Can you share your logile and the docker run / docker-compose file.
I don't think it's running in debug mode as the logging level is set to error by default, which it shows.

Since last release the logging output is appended to stdout for nginx, so output from that logfile is being shown with docker logs. My guess that is what you've noticed.

**Comment by JPJJansen** [comment]
Ahh sorry my mistake then. I noticed a lot of information about web visits in the docker logs and i thought this was caused by the error log level. I will close this issue

**Comment by xirixiz** [comment]
No problem, thought so. Thanks, and luckily no issue 👍 !
