### ISSUE TITLE
Can’t install the addon

### ISSUE THREAD

**Issue by Rocker20** [xirixiz/dsmr-reader-docker#248]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Since i restored a snapshot of home assistant dsmr was broken so i had delete the addon. When i wanna install the addon the following error shows up: 

manifest for xirixiz/dsmr-reader-docker:latest-2021.10.02-amd64 not found: manifest unknown: manifest unknown

### Expected behaviour

Install the addon

### Actual behaviour

Shows error

### Steps to reproduce

Remove and install the addon

### Docker info

```yaml
Unknown
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):

### Docker compose

```yaml
None
```

### Container logs

Same error

**Comment by xirixiz** [comment]
You are not using the proper Docker image. That tag is old and doesn't exist anymore. Please use:
```
xirixiz/dsmr-reader-docker:latest
```
