### ISSUE TITLE
DSMR-reader docker on Raspberry Pi

### ISSUE THREAD

**Issue by erwindemoel** [xirixiz/dsmr-reader-docker#25]
Hi, I'm trying to run this container on my Raspberry Pi within Docker. I successfully downloaded the image using:
`docker pull xirixiz/dsmr-reader-docker`

However when I try to run:
`sudo docker run xirixiz/dsmr-reader-docker`

I get the following error:
`standard_init_linux.go:178: exec user process caused "exec format error"`

What am I doing wrong?

**Comment by xirixiz** [comment]
Raspberries use ARM and not x86_64 processors. You can only run images created for that architecture. Try searching for ARM or ARMv7 on docker hub. There is a Debian image for ARM, you could try to use that image.

**Comment by erwindemoel** [comment]
Sorry @xirixiz, I don't quite understand. Is there an ARM or ARMv7 version of the DSMR-Reader on Docker hub? Or do you mean I should try and install a Debian image for ARM on my Raspberry Pi 3 and then try running the previously mentioned Docker container for DSMR-Reader again?

**Comment by erwindemoel** [comment]
Just to clarify, I did install the DSMR-Reader successfully on my Raspberry Pi 3, but am now trying to run the same thing inside a docker container.

**Comment by xirixiz** [comment]
Did it work to run it on the Pi? If not, maybe I can help.

**Comment by erwindemoel** [comment]
I was able to install the DSMR reader software itself on the Raspberry Pi Zero W. However I was unable to get the Docker container working on a Raspberry Pi. If you can help with this, I would really appreciate it!

**Comment by xirixiz** [comment]
Ok, I just changed all used images to use alpine as the base image, which should be enough to get things working in docker on a Raspberry Pi, could you please verify? You should use the docker-compose file attached to this project on the master branch.

**Comment by xirixiz** [comment]
> I'm trying to test this, after installing docker and docker-compose using pip ([tutorial](https://withblue.ink/2017/12/31/yes-you-can-run-docker-on-raspbian.html)) I've run the following commands:
> 
> ```
> sudo docker pull xirixiz/dsmr-reader-docker
> sudo docker-compose start dsmr
> ```
> The last one gives this error:
> 
> ```
> ERROR: 
>         Can't find a suitable configuration file in this directory or any
>         parent. Are you in the right directory?
> 
>         Supported filenames: docker-compose.yml, docker-compose.yaml
> ```
> What am I doing wrong?

You don't have a docker-compose.yml file after pulling the image. Try to do the following:

- git clone https://github.com/xirixiz/dsmr-reader-docker.git
- cd dsmr-reader-docker
- docker-compose up

It will pull the necessary images and start dsmr with dsmrdb. Make sure all values in the docker-compose.yml file are suitable for your (hardware) needs.

**Comment by xirixiz** [comment]
Any update?

**Comment by erwindemoel** [comment]
We found out that the Dsmr Reader software conflicts with our own, so we have stopped pursuing the installation into a docker image. Instead we have installed our own software to read the Dsmr port. Thanks for all your help!
