### ISSUE TITLE
Static files are not found with latest image

### ISSUE THREAD

**Issue by citizen-stig** [xirixiz/dsmr-reader-docker#256]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

# Intro

After updating to latest image all static files are not found:

<img width="1918" alt="Screenshot 2022-01-09 at 22 29 04" src="https://user-images.githubusercontent.com/3115300/148701780-ae59c85f-b7c2-41e7-aad2-ed74b6cef8b2.png">

Folder `/var/www/dsmrreader/static/` is empty.

Running following command in the container solved the issue:

```bash
root@dsmr_reader_docker:/app# cp -r dsmr_frontend/static/dsmr_frontend /var/www/dsmrreader/static/
```

it would be great if image can be updated. I believe having symling should help.

### Expected behaviour

All CSS are displayed

### Actual behaviour

No CSS or javascript is fetched.

### Steps to reproduce

Start dsmr container with command below

### Docker info

```
docker run -d \
  --name dsmr \
  --restart always \
  -p 8080:80 \
  -p 7777:7777 \
  -p 7779:7779 \
  -e TZ=Europe/Amsterdam \
  -e DB_HOST=172.17.0.1 \
  -e DB_USER=dsmr \
  -e DB_PASS=hunter2 \
  -e DB_NAME=dsmr \
  -e VIRTUAL_HOST=localhost \
  -e DSMR_PASSWORD=hunter2\
  -e DSMR_EMAIL=admin@example.com \
  -e SD_AUTOSTART_DATALOGGER=false \
  -e SD_AUTORESTART_DATALOGGER=false \
  -e DATALOGGER_MODE=receiver \
  xirixiz/dsmr-reader-docker:latest
```  

### Version

* Docker compose version (type `docker-compose --version`): Docker version 20.10.12, build e91ed5707e
* System info (type `uname -a`): `uname -a
Linux gezellig 5.10.90-1-lts #1 SMP Wed, 05 Jan 2022 13:07:40 +0000 x86_64 GNU/Linux`

### Container logs

```
[23:18:22] gezellig in ~/Documents ▸ docker logs dsmr | head -200
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------
User UID: 803
User GID: 803
-------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-app-defaults: executing...
[ INFO ] DSMR Reader release: 4.19.0
[ INFO ] DSMR Reader Docker release: 2022.01.02
[ INFO ] Ensure permissions...
[ INFO ] Setting architecture requirements...
[ INFO ] X64 Architecture
nc: getaddrinfo: Name does not resolve
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying database connectivity to host: dsmrdb with port: 5432...
nc: getaddrinfo: Name does not resolve
nc: getaddrinfo: Name does not resolve
nc: getaddrinfo: Name does not resolve
[ FAIL ] Database connectivity couldn't be verified! Please verify your settings. Exiting...
[cont-init.d] 20-set-app-defaults: exited 1.
[cont-init.d] done.
[services.d] starting services
Starting DSMR Reader - nginx...
Starting DSMR Reader - backend...
Starting DSMR Reader - webinterface...
[services.d] done.
2022/01/09 22:04:35 [crit] 384#384: *1 connect() to unix:///var/tmp/gunicorn--dsmr_webinterface.socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /about HTTP/1.1", upstream: "http://unix:///var/tmp/gunicorn--dsmr_webinterface.socket:/about", host: "127.0.0.1"
127.0.0.1 - - [09/Jan/2022:22:04:35 +0100] "GET /about HTTP/1.1" 502 150 "-" "curl/7.79.1" "-"
[2022-01-09 22:04:35 +0100] [363] [INFO] Starting gunicorn 20.1.0
[2022-01-09 22:04:35 +0100] [363] [INFO] Listening at: unix:/var/tmp/gunicorn--dsmr_webinterface.socket (363)
[2022-01-09 22:04:35 +0100] [363] [INFO] Using worker: sync
[2022-01-09 22:04:35 +0100] [393] [INFO] Booting worker with pid: 393
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
192.168.178.20 - - [09/Jan/2022:22:04:38 +0100] "POST /api/v1/datalogger/dsmrreading HTTP/1.1" 500 4256 "-" "python-requests/2.21.0" "-"
127.0.0.1 - - [09/Jan/2022:22:04:41 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
127.0.0.1 - - [09/Jan/2022:22:04:46 +0100] "GET /about HTTP/1.1" 200 14772 "-" "curl/7.79.1" "-"
```

### Additional info

....

**Comment by xirixiz** [comment]
Hi, can you please tell me more about your setup by following what is being asked during issue creation? Currently I`m mainly interested in the startup logs. 

However no one else is exeperiencing such issue. The copy process hasn't changed and I can confirm the copy process is still part of the startup process.

**Comment by citizen-stig** [comment]
Updated the description. Also, fix I've provided do not help with Django admin static.

**Comment by xirixiz** [comment]
There it is, there's a database connectivity issue causing the problems you're facing:
```
[ FAIL ] Database connectivity couldn't be verified! Please verify your settings. Exiting...
```
It seems the dsmr container is unuable to resolve the db host.

**Comment by xirixiz** [comment]
Anyway, added a new image so the container exits properly if an error in the initialization face is faced.
https://github.com/xirixiz/dsmr-reader-docker/pull/257

https://github.com/just-containers/s6-overlay#read-only-root-filesystem

```
S6_BEHAVIOUR_IF_STAGE2_FAILS
```

This doens't solve the issue you're facing, but at least the container exits properly when the database (host/container) cannot be found.
