### ISSUE TITLE
MQTT support needs upgrade

### ISSUE THREAD

**Issue by koelkast88** [xirixiz/dsmr-reader-docker#26]
With the update to 1.23, MQTT doesn't work anymore. it [needs an update](http://dsmr-reader.readthedocs.io/nl/latest/faq.html#how-do-i-retain-mqtt-support-when-upgrading-to-v1-23-0-or-higher)
```

sudo cp /home/dsmr/dsmr-reader/dsmrreader/provisioning/supervisor/dsmr-reader.conf /etc/supervisor/conf.d/

sudo supervisorctl reread

sudo supervisorctl update
```

But, it doesn't work in your Docker version. Which command / directories do I need for updating the supervisor?

**Comment by Baseje** [comment]
It also didnt work on my installation!

**Comment by xirixiz** [comment]
I`ll fix this issue Today... Cheers

**Comment by ualex73** [comment]
I fixed it in my fork already:
https://github.com/ualex73/dsmr-reader-docker/blob/master/rootfs/supervisord.conf

Don't forget the restart option, otherwise the WebGUI will stop the MQTT process, but it will not start automatically.

**Comment by xirixiz** [comment]
Thanks for your help ualex73! Copied your version of supervisord.

**Comment by Baseje** [comment]
How to update this file, i tried to recreate my docker by the new image and restore my database but no result :(

**Comment by ualex73** [comment]
@Baseje : what type of error are you getting?

Also if you do a "ps -ef | grep dsmr_" what do you see?

My output looks like:
ps -ef | grep dsmr_ | grep -v timeout
dsmr      6528  6516  1 aug07 ?        00:11:21 python3 -u /home/dsmr/app/manage.py dsmr_mqtt
dsmr      6530  6516  8 aug07 ?        01:00:18 python3 -u /home/dsmr/app/manage.py dsmr_datalogger
dsmr      6533  6516  6 aug07 ?        00:42:50 python3 -u /home/dsmr/app/manage.py dsmr_backend

**Comment by Baseje** [comment]
I didn’t receive an error.
When I enter the command in mij DSMR container I receive;

root        26    22  0 09:01 ?        00:00:00 /usr/bin/python3 /usr/local/bin/gunicorn dsmrreader.wsgi --user dsmr --timeout 60 --max-requests 500 --bind unix:/var/tmp/gunicorn--dsmr_webinterface.socket --pid /var/tmp/gunicorn--dsmr_webinterface.pid
dsmr        27    22  0 09:01 ?        00:00:19 python3 -u /home/dsmr/app/manage.py dsmr_datalogger
dsmr        28    22  2 09:01 ?        00:00:50 python3 -u /home/dsmr/app/manage.py dsmr_backend
dsmr        37    26  0 09:01 ?        00:00:04 /usr/bin/python3 /usr/local/bin/gunicorn dsmrreader.wsgi --user dsmr --timeout 60 --max-requests 500 --bind unix:/var/tmp/gunicorn--dsmr_webinterface.socket --pid /var/tmp/gunicorn--dsmr_webinterface.pid
root        45    39  0 09:43 pts/0    00:00:00 grep dsmr_


Van: Alexander <notifications@github.com>
Verzonden: woensdag 8 augustus 2018 11:08
Aan: xirixiz/dsmr-reader-docker <dsmr-reader-docker@noreply.github.com>
CC: Bas Jongeneel <Bas@Jongeneel.IT>; Mention <mention@noreply.github.com>
Onderwerp: Re: [xirixiz/dsmr-reader-docker] MQTT support needs upgrade (#26)


@Baseje<https://github.com/Baseje> : what type of error are you getting?

Also if you do a "ps -ef | grep dsmr_" what do you see?

My output looks like:
ps -ef | grep dsmr_ | grep -v timeout
dsmr 6528 6516 1 aug07 ? 00:11:21 python3 -u /home/dsmr/app/manage.py dsmr_mqtt
dsmr 6530 6516 8 aug07 ? 01:00:18 python3 -u /home/dsmr/app/manage.py dsmr_datalogger
dsmr 6533 6516 6 aug07 ? 00:42:50 python3 -u /home/dsmr/app/manage.py dsmr_backend

**Comment by ualex73** [comment]
Ok, the dsmr_mqtt isn't running ...

Can you compare inside the Docker the file "/etc/supervisor/conf.d/supervisord.conf" with the following one:
https://github.com/xirixiz/dsmr-reader-docker/blob/master/app/supervisord.conf

You should see the additional section:
[program:dsmr_mqtt]
command=/usr/bin/nice -n 15 python3 -u /home/dsmr/app/manage.py dsmr_mqtt
pidfile=/var/tmp/dsmrreader--%(program_name)s.pid
user=dsmr
group=dsmr
autostart=true
autorestart=true
startsecs=1
startretries=100
stopwaitsecs=5

**Comment by Baseje** [comment]
I’ve copied it, it looks like it work!
Thanks!

Van: Alexander <notifications@github.com>
Verzonden: woensdag 8 augustus 2018 11:58
Aan: xirixiz/dsmr-reader-docker <dsmr-reader-docker@noreply.github.com>
CC: Bas Jongeneel <Bas@Jongeneel.IT>; Mention <mention@noreply.github.com>
Onderwerp: Re: [xirixiz/dsmr-reader-docker] MQTT support needs upgrade (#26)


Ok, the dsmr_mqtt isn't running ...

Can you compare inside the Docker the file "/etc/supervisor/conf.d/supervisord.conf" with the following one:
https://github.com/xirixiz/dsmr-reader-docker/blob/master/app/supervisord.conf

You should see the additional section:
[program:dsmr_mqtt]
command=/usr/bin/nice -n 15 python3 -u /home/dsmr/app/manage.py dsmr_mqtt
pidfile=/var/tmp/dsmrreader--%(program_name)s.pid
user=dsmr
group=dsmr
autostart=true
autorestart=true
startsecs=1
startretries=100
stopwaitsecs=5
