### ISSUE TITLE
How to change default port 80

### ISSUE THREAD

**Issue by dataegg** [xirixiz/dsmr-reader-docker#261]
### Request

I'm using this image in a podman (docker alternative) configuration and I am using pods. I already have a container running on port 80, how can I change the internal port of this container so I can run it in the same pod as the other container already using port 80?

**Comment by xirixiz** [comment]
Hi, I believe with podman there is the ability to do something like this to publish ports:

```podman run -dt -p 8080:80/tcp docker.io/library/httpd```

**Comment by dataegg** [comment]
> Hi, I believe with podman there is the ability to do something like this to publish ports:
> 
> `podman run -dt -p 8080:80/tcp docker.io/library/httpd`

Yes, this is correct but this way the container will still run on port 80 but the port will be publisched to the outside on port 8080. I need the DSMR container to use something else then port 80 because I already have a container running on port 80 in the same pod.

with podman a pod can be compared to a hosts, It will have an ip etc. Containers run inside a pod  so I have:
1- a POD with name POD1
2. I added an HTTP server to POD1 on port 80
3. Now I want do add DSMR reader but internal I need something then port 80.
Is it possible to configure this DSMR image to use something elke then port 80 and how can I do this.

Thanks for your help.

Kind regards,
Martin

**Comment by xirixiz** [comment]
Ok, so this means within a POD you're running everything sort of "host" based.
I think I can manage something to fix this in an upcoming release 👍 .

**Comment by dataegg** [comment]
> Ok, so this means within a POD you're running everything sort of "host" based. I think I can manage something to fix this in an upcoming release 👍 .

Yes indeed. At the moment I have my own pod for the DSMR reader container but I would like to put it in another pod to group a set of applications. It would be nice if the port is configurable.

**Comment by xirixiz** [comment]
Created a development tag which has the option to set a custom port. 
You need to set ```NGINX_LISTEN_PORT``` to for example ```8090``` to run nginx within the container on port 8090

So like this as an environment variable at the startup of your container:
```
NGINX_LISTEN_PORT=8090
```

If it's working properly, I`ll merge it to the master branch and draft a new release.

**Comment by dataegg** [comment]
> Created a development tag which has the option to set a custom port. You need to set `NGINX_LISTEN_PORT` to for example `8090` to run nginx within the container on port 8090
> 
> So like this as an environment variable at the startup of your container:
> 
> ```
> NGINX_LISTEN_PORT=8090
> ```
> 
> If it's working properly, I`ll merge it to the master branch and draft a new release.

I tested it and it works great. Thanks for picking it up so quickly.

Here you can see nx-ing is now listening on port 8090 (just like your example) and I created the podman container like this:

podman run -d \
  --pod=Energie \
  --name=dsmr \
  --device /dev/ttyUSB0:/dev/ttyUSB0 \
  -e DSMRREADER_ADMIN_USER=admin \
  -e DSMRREADER_ADMIN_PASSWORD=<admin password> \
  -e DJANGO_TIME_ZONE=Europe/Amsterdam \
  -e DJANGO_DATABASE_HOST=<database ip> \
  -e DJANGO_DATABASE_PORT=5432 \
  -e DJANGO_DATABASE_USER=dsmrreader \
  -e DJANGO_DATABASE_PASSWORD=<database password> \
  -e VIRTUAL_HOST=localhost \
  -e NGINX_LISTEN_PORT=8090 \
  docker.io/xirixiz/dsmr-reader-docker:development

inside the container I see this:

podman exec -it dsmr /bin/bash

root@dsmr_reader_docker:/app# netstat -anp | grep 8090
tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN      286/nginx -g daemon

I think you can merge it into the master branch. Thanks again.

**Comment by dataegg** [comment]
No rush, but maybe you forgot to push it to master?

**Comment by xirixiz** [comment]
Nope, also fixed another issue in the same branch :)....

https://github.com/xirixiz/dsmr-reader-docker/issues/262

Waiting for input.

**Comment by dataegg** [comment]
> Nope, also fixed another issue in the same branch :)....
> 
> #262
> 
> Waiting for input.

If I understand well it should now be in master branch? (#263)...but it doesn't work the port remains on 80.
