### ISSUE TITLE
DSMRReader container - verminder logging

### ISSUE THREAD

**Issue by puijken** [xirixiz/dsmr-reader-docker#268]
### Request

Ik heb zonet een nieuwe 5.0 container uitgerold en het viel me op dat elke connectie gelogd wordt, dit zowel in de SENDER container als de RECEIVER container. Zie screenshot.

Sender:
![image](https://user-images.githubusercontent.com/77811176/153852855-68decd47-2406-45c7-bbe0-8527db3dbb58.png)

Receiver:
![image](https://user-images.githubusercontent.com/77811176/153854914-ecbea101-984f-4962-bf60-d727b3ea50fc.png)

Ik kan me helaas niet herinneren of dit bij 4.x ook zo was maar dit lijkt me niet per se nodig en veroorzaakt veel extra I/O richting de logfiles. Ik heb geprobeerd volgende parameters bij te plaatsen in de docker-compose file maar het resultaat blijft hetzelfde:

```
    environment:
      - DSMRREADER_REMOTE_DATALOGGER_DEBUG_LOGGING=false
      - DSMRREADER_LOGLEVEL=WARNING
```

Tenzij ik verkeerd ben is WARNING het laagst mogelijke logging level maar dit produceert blijkbaar nog steeds veel logging in de sender container. (weet niet of dit ook het geval is in een standalone container). Het zou fijn zijn om dit te kunnen uitschakelen en werkelijk alleen bij WARNING een melding te maken in de logs.

UPDATE: info toegevoegd ivm receiver container en titel aangepast.

**Comment by xirixiz** [comment]
Bij versie 4 werd de logging naar een logfile weggeschreven voor het http(s) deel (nginx), dat was dus niet zichtbaar bij het volgen van de logs op de container. De config heb ik aangepast zodat het juist niet meer naar een logfile gaat maar naar stdout, wat beter is, en zodat het zichtbaar is wanneer je de container logs bekijkt. Dit is "INFO" logging en dat kan inderdaad nog niet worden aangepast met environment variabelen. Lijkt mij wel mooi om dat aan te kunnen passen, dus ik zal er eens naar kijken. 

Hoe dan ook is het voor nu dus normaal gedrag en niets om je zorgen over te maken.

**Comment by puijken** [comment]
Nee inderdaad, vandaar ook een feature request. Niks dringend natuurlijk maar in elk geval bedankt!!

**Comment by dennissiemensma** [comment]
@puijken voor de datalogger-logging zal ik het loglevel aanpassen. Ik had niet door dat dit standaard gelogd werd, omdat DSMR-reader zelf standaard `debug` en `info` logs mute, tenzij debug-logging aanstaat. 
Voor de remote datalogger is dat nog niet zo, maar het lijkt me goed dat ik dat gelijktrek. Standaard hoeven we alleen errors te zien.

- De melding: https://github.com/dsmrreader/dsmr-reader/blob/v5/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py#L29-L34
- Defaults: https://github.com/dsmrreader/dsmr-reader/blob/v5/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py#L96-L99

**Comment by dennissiemensma** [comment]
Ik heb het aangepast voor DSMR-reader v5.1: https://github.com/dsmrreader/dsmr-reader/commit/a8086465e9bce474c538f663d2fa1c3ce2053bbc

**Comment by xirixiz** [comment]
Super 👌🏻

**Comment by puijken** [comment]
Geweldig, bedankt! Wat een responsetijd :)

**Comment by dennissiemensma** [comment]
Uitgebracht in https://github.com/dsmrreader/dsmr-reader/releases/tag/v5.1.0

**Comment by xirixiz** [comment]
Docker image released as well for 5.1.0.
