### ISSUE TITLE
Use version specific tags

### ISSUE THREAD

**Issue by Janoz-NL** [xirixiz/dsmr-reader-docker#271]
### Request

Today I found out the hard way that using tag latest isn't always handy. I accidently upgraded DSMR from v4 to v5 which broke my setup (new ENV variables and dropped support voor InfluxDB 1.x). I wanted to rollback, but I couldn't find the right version.

It would be nice if you could also provide a v4 and v5 tag so people can safely update their docker image whitout accidently triggering a major version update.

I'll take my loss for now :) so if it's complicated to add a v4 it's completely understandable, but this would be a nice moment to introduce a v5 tag.

**Comment by xirixiz** [comment]
i can imagine! I`ll add a tag/version for upcoming releases.

**Comment by xirixiz** [comment]
Fixed in upcoming release
