### ISSUE TITLE
Wrong user for health check in Docker-Compose template

### ISSUE THREAD

**Issue by bikeymouse** [xirixiz/dsmr-reader-docker#274]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,

Ik heb net de upgrade gedaan van 4.19 naar 5.1. Dat verliep probleemloos, dus top en dank voor al het werk wat je in deze Docker versie stopt!

Ik heb de upgrade ook gebruikt om de health-check op de Containers toe te voegen en had daarvoor het stukje code uit de Docker-Compose template gebruikt[ hier](https://raw.githubusercontent.com/xirixiz/dsmr-reader-docker/master/examples/docker-compose.example.yaml).
Voor de DSMRDB container is dat dit stukje:

`
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
`

### Expected behaviour

Health check zonder errors.

### Actual behaviour

Foutmeldingen in de log in de trant "postgres No such user".

### Additional info

Ik heb het opgelost door de user aan te passen naar dsmrreader.
Het stukje code in de Docker-Compose wordt dan dus:

`
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dsmrreader" ]
      interval: 60s
      timeout: 5s
      retries: 10
`

**Comment by xirixiz** [comment]
Klopt inderdaad, de default user is postgres, maar voor dsmrreader wordt meestal dsmrreader gebruikt. Ik zal de compose file bijwerken in de development branch en later meenemen richting een nieuwe release! Bedankt voor jouw bijdrage!

**Comment by xirixiz** [comment]
https://github.com/xirixiz/dsmr-reader-docker/blob/development/examples/docker-compose.example.yaml
