### ISSUE TITLE
Can't start container after update

### ISSUE THREAD

**Issue by bobvmierlo** [xirixiz/dsmr-reader-docker#275]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Container won't start after pulling the latest container.
Running on Synology NAS DS1821+ with the P1 logger connected via network.

### Expected behaviour

Container should start, has been running fine for years and has had multiple updates in the past

### Actual behaviour

Doesn't start, no clear errors in the log

### Steps to reproduce

1. Update docker container by pulling the latest image from dockerhub
2. dsmr container won't start, see log below:

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

### Version

* Docker compose version (type `docker-compose --version`): docker-compose version 1.28.5, build 324b023a
* System info (type `uname -a`): Linux DS1821 4.4.180+ #42218 SMP Mon Oct 18 19:15:51 CST 2021 x86_64 GNU/Linux synology_v1000_1821+

### Docker compose

```yaml
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

### Container logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------
User UID: 803
User GID: 803
-------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-app-defaults: executing... 
[ INFO ] DSMR Reader release: 5.1.0
[ INFO ] DSMR Reader Docker release: 2022.02.03
[ INFO ] Ensure permissions...
[ INFO ] Setting architecture requirements...
[ INFO ] X64 Architecture
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying database connectivity to host: dsmrdb with port: 5432...
[ INFO ] Database connectivity successfully verified!
[ INFO ] Running post configuration...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by xirixiz** [comment]
Hi, this is a bit of odd logging.

- The Docker daemon isn't reachable
- The docker-compose file cannot be found

... but the you're able to start it and get the container logs, which even look fine :).

Can't dive into it Tonight, but please try to provide some more details about what is actually happening. Decribe what you're doing and what's happening, step-by-step.

**Comment by bobvmierlo** [comment]
I've created a complete fresh container with the old database container attached and it's working fine now. I guess it could be related to environment settings that I used that didn't work on newer versions of your Docker container?
