### ISSUE TITLE
Use of Alpine-3.15 for Postgresql 14

### ISSUE THREAD

**Issue by sanderdw** [xirixiz/dsmr-reader-docker#278]
### Request

Hi Bram,

Is it possible to switch Alpine-3.15? 

In https://alpinelinux.org/posts/Alpine-3.15.0-released.html is Postgresql 14 included. It should be backwards compatibel to older Postgresql server versions but i don't know if you need other dependencies.

Question is due many users of the addon are using a specific Postgresql addon which is now at this version.

### Additional information

https://github.com/sanderdw/hassio-addons/issues/36

**Comment by GentleGiantSoftware** [comment]
This would be great, just moved from a Raspberry Pi to docker on my synology nas, only discovering after a few days that the backup is not working because I installed the latest postgresql (version 14). So please update or can you otherwise explain how to get the newer pg_* tools on this image?

**Comment by xirixiz** [comment]
Sure, not a problem! Will develop a new release Today!

**Comment by GentleGiantSoftware** [comment]
😊 Very much appreciated.
Ben

**Comment by xirixiz** [comment]
Will be updated in the upcoming release Today.

**Comment by xirixiz** [comment]
* Switch to Alpine 3.15. Makes is possible to use Postgres 14
* Add DSMR release to Docker tag (master)
* Fix pgsql user in health check (#276) - Update docker-compose.example.yaml

# Breaking change
* nginx is using /etc/nginx/http.d by default now. In this release a symbolic link has been added (/etc/nginx/conf.d), so everything will remain as it is. However in a future release this link shall be removed.
