### ISSUE TITLE
Configure Postgres storage location

### ISSUE THREAD

**Issue by DennisVredeveld** [xirixiz/dsmr-reader-docker#284]
### Request

The non-Docker installation of DSMR reader offers the option to change the postgres configuration to use a different data storage location (see https://dsmr-reader.readthedocs.io/nl/v5/how-to/database/postgresql-change-storage-location.html). This requires manually editing the postgres.conf file to set this location.
Could this be a DB-related setting/environment parameter? Or is there a different way of using this feature in a Docker installation of DSMR reader?

**Comment by DennisVredeveld** [comment]
Het ging me er eigenlijk vooral om te weten of dit mogelijk is.... de crash course komt wel goed maar ik wilde niet aan een docker-based installatie beginnen zonder te weten in hoeverre dit zou gaan werken.

**Comment by DennisVredeveld** [comment]
De PG versies zijn gelijk, want het werkt zonder problemen als ik een lokale map gebruik. Wanneer ik echter een volume gebruik met een via NFS gedeelde map op mijn NAS, werkt dit enkel voor de backups. De dsmrdb container start niet op een geeft 
`ERROR: for dsmrdb  Cannot create container for service dsmrdb: failed to chmod on /var/lib/docker/volumes/pi_database/_data: chmod /var/lib/docker/volumes/pi_database/_data: operation not permitted`
Dus ja, ik denk wel dat ik tegen een rechtenissue aanloop :)

**Comment by xirixiz** [comment]
Dat is eenvoudig op te lossen 😁. Ik kom er morgen even op terug.

**Comment by DennisVredeveld** [comment]
Ok, ik ben benieuwd!
Misschien sowieso goed om dat een plek in de documentatie te geven? Als iedereen op de een of andere manier een volume voor de DB moet maken, kan ik me voorstellen dat meer mensen tegen dit probleem aanlopen.

**Comment by xirixiz** [comment]
Please check the --user section:
https://hub.docker.com/_/postgres

Summary:
Make sure to match the UID:GID of the owner of your nfs share the same UID:GID used inside the container to run Postgres.

And: use a volume instead of bind-mounts. If the nfs share becomes stale, the container will remedy the problem byitself. If the nfs mount on the host becomes stale things usualy get weird.

https://stackoverflow.com/questions/39922161/mounting-nfs-shares-inside-docker-container

Hope this provides some usefull information.

**Comment by DennisVredeveld** [comment]
Het Volume is volgens mij niet het probleem, dit heb ik werkend:
`  database:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.12,rw,nolock,soft,nfsvers=4"
      device: ":volume1/piDatabase"`

De opmerking m.b.t. UID/GID had ik gezien maar eerlijk gezegd is niet precies duidelijk hoe je daar dan voor zorgt en hoe ik weet welke gebruikt worden aan de NFS kant en in de container. Lijkt me dat meer beginnende docker-gebruikers daar tegenaan lopen, vandaar de suggestie voor iets uitgebreidere documentatie :)

**Comment by DennisVredeveld** [comment]
@xirixiz any updates yet?
