### ISSUE TITLE
Docker installation guide Synology

### ISSUE THREAD

**Issue by josdegroot** [xirixiz/dsmr-reader-docker#288]
### Request

Is is possible to make a manual to install the DSMR docker on a synology. For me it's not clear now wich volumes i have to map for example.

Hopefully someone can help me with the installation. Like this for example: https://github.com/koush/scrypted/wiki/Installation:-Docker-Synology-NAS

**Comment by xirixiz** [comment]
Hi Jos, to be honest, not really :). It's more related to Docker and how to use Docker.

To get you started:
- Docker works with images. Docker images are static. 
- Running a Docker image will create a Docker container. 
- A Docker image is static, a Docker container isn't. So each time you start a Docker container you can modify stuff within that container. However, when you restart the container, it'll use the Docker image, so the Docker container starts "clean" again. So all settings and modifications will be lost.

- Now volumes come into play. You can map/mount folders and/or volumes into your Docker container from the Docker host (Synology in your case). So eacht time you start your container you mount the folder/volume in your container so settings will be stored to that location. So when restarting a container, the data from your Synology will be mounted again so you still have the same data available (persistent storage).

So in case of DSMR it requires two Docker containers. One for the application and one for the database. You most probably would like to keep settings and data from the database each time you restart the DSMR Docker database container, so therefor you mount the data folder from your Synology to that container. This can be either a simple folder or you can use Docker volumes (both heb pros and cons).

I hope this will help you. There is also a docker-compose example in the repo btw.

Besides that search for the terms I mentioned and follow some Docker tutorials on youtube, that way you'll learn the quickest and you should be able to have DSMR up and running in no time. Ofcourse, if you have any questions, don't hesitate to ask.

**Comment by xirixiz** [comment]
Het lijkt erop dat de DSMR container de Postgres container niet kan resolven. Dit hangt weer af van op wat voor manier je de ccontainer start. Gebruik je een bridge netwerk, host netwerk...welke naamgeving gerbuik je voor de container, etc? Dat is belangrijk om te weten om ervoor te zorgen dat ze zichtbaar zijn voor elkaar. Je hoeft overigens geen db te maken, dat regelt DSMR voor jou wanneer de connectie tot stand is gekomen ;).
