### ISSUE TITLE
View version of DSMR reader

### ISSUE THREAD

**Issue by YLKersloot** [xirixiz/dsmr-reader-docker#291]
### Request

Have an easy way to know which version of DSMR reader it is providing, so I know if I can upgrade it

### Additional information

Could be on the documentation of your gitrepo, in a source file or perhaps with a tag or something. Perhaps it is already there and I'm overlooking it :)

**Comment by xirixiz** [comment]
Hi, currently it's always the latest release of DSMR :). So if you look for the latest release of DSMR, then that release is currently being used in this Docker release. Hope it's clear 👍🏻✌🏻

**Comment by xirixiz** [comment]
The release can be found here https://github.com/dsmrreader/dsmr-reader
