### ISSUE TITLE
DSMR remote logger as separate container

### ISSUE THREAD

**Issue by Wouter1702** [xirixiz/dsmr-reader-docker#300]
### Request

Hello,

I run my DSMR in docker on a synology and i am using the USB port to connect the serial cable the the P1 port. Synology does not support the use of USB in DSM7 so before i can upgrade to DMS7, i need to move the DSMR data logger function to an other host.
I prepared a RPi with docker and want to run the DSMR remote data logger on the RPi in a docker container.
I found a very old container (3 year old script). This container does not contain the latest remote logging script and does not uses the .env variables mentioned in the DSMR reader documentation.

Is it posible to create a separate container of the remote data logger function only and maintain it next to the DSMRreader container so remote datalogger and DSMR reader always using the same version of the source code

Thanks,
Kind regards,
Wouter Iliohan.

**Comment by xirixiz** [comment]
Hi Wouter, I just checked the documentation, and I don't see outdated things in the Docker image.

https://dsmr-reader.readthedocs.io/nl/latest/how-to/installation/remote-datalogger.html

You can use the Docker container environment variables, which overrules the .env file settings, like the documentation says.

If you have additional info, or you'd like to have some additional info, please let me know.

**Comment by xirixiz** [comment]
Check the README.MD as well, there is info regarding this topic available.

**Comment by Wouter1702** [comment]
Hello Bram,

How can i use your docker image as a remote logger.
I can not find any examples on how to do that.
I use your image on my Synology as a logger and app in 1.
How can i seperate those.
Can i use your docker image as a remote logger only?

**Comment by xirixiz** [comment]
Hi Wouter, you can start reading from here (sender, receiver, standalone)....
https://github.com/xirixiz/dsmr-reader-docker#dsmr-datalogger-related

**Comment by Wouter1702** [comment]
OK, so on the RPi i only use the dsmr container and no database.
and i have to put the correct information in the environment variables.

I have made a docker-compose example.

version: '3.7'

networks:
  default:
    driver: bridge

services:
  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    cap_add:
      - NET_ADMIN
    networks:
      - default
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DSMRREADER_REMOTE_DATALOGGER_MODE=sender
      - DSMRREADER_REMOTE_DATALOGGER_API_HOSTS=http://12.34.56.78:7777
      - DSMRREADER_REMOTE_DATALOGGER_API_KEYS=0987654321HGFEDCBA
      - DSMRREADER_REMOTE_DATALOGGER_INPUT_METHOD=serial
      - DSMRREADER_REMOTE_DATALOGGER_SERIAL_PORT=/dev/ttyUSB0
      - DSMRREADER_REMOTE_DATALOGGER_SERIAL_BAUDRATE=115200
      - DSMRREADER_REMOTE_DATALOGGER_SERIAL_BYTESIZE=8
      - DSMRREADER_REMOTE_DATALOGGER_SERIAL_PARITY=N
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

Could you please check if this is a correct way.
Thanks,
Kind regards,
Wouter Iliohan

**Comment by xirixiz** [comment]
Hi Wouter, never used it myself before, but it seems to be looking good. Most probably @dennissiemensma can tell  whether the env vars match the setup you're trying to have.

**Comment by dennissiemensma** [comment]
@Wouter1702 if available on the host reading the USB, you can consider simply installing `ser2net` there instead (which should be working on Raspbian). 
Then configure DSMR-reader to read by netwerk instead, so the other way around. This should be way easier than the remote datalogger.

----

> Could you please check if this is a correct way.
I think it's best to just try it. The settings required should prompt an error when missing.

**Comment by dennissiemensma** [comment]
@Wouter1702 any progress?

**Comment by Wouter1702** [comment]
Hello Dennis,

Yes i have mad progress. I installed a RPi with docker and installed the ser2net container.
The RPi now sends the P1 data to the DSMR container on my Synology.

Here is the compose file of my ser2net container

version: "3.7"

networks:
  default:
    driver: bridge

services:
    ser2net:
        image: jbouwh/ser2net:latest
        environment:
            - TZ=${TZ}
        volumes:
            - $DOCKERHOME/$COMPOSE_PROJECT_NAME/ser2net.conf:/etc/ser2net.conf:ro
            - /etc/localtime:/etc/localtime:ro
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        networks:
            - default
        ports:
            - "3333:3333"
        restart: always


I switched the USB-P1 cable from the Synology to the RPi and then i changed the data logging mode in DSMR to use the network socket, put in the IP and port of the ser2net and the readings came in.
I made the changes via the UI but Is it also possible to set this parameters on start of the container with environment variables or does that only apply to new installations?

**Comment by bikeymouse** [comment]
> @Wouter1702 if available on the host reading the USB, you can consider simply installing `ser2net` there instead (which should be working on Raspbian). Then configure DSMR-reader to read by netwerk instead, so the other way around. This should be way easier than the remote datalogger.
> 
> > Could you please check if this is a correct way.
> 
> I think it's best to just try it. The settings required should prompt an error when missing.

I was wondering, what is the use case of the remote datalogger, if you can use ser2net to forward the P1-port to any host?
Does the remote datalogger use less bandwidth?

**Comment by dennissiemensma** [comment]
Ser2net or a direct usb connection is always preferred, since it allows DSMR-reader to _pull_ data from either source. It's also way easier to configure and debug/maintain as user. The remote datalogger should only be used for technical reasons as workaround, to _push_ data. E.g. when the source cannot be reached by network. Like running DSMR-reader outside your home network etc.

**Comment by xirixiz** [comment]
Thanks for the additional notes Dennis. I wasn't aware. Maybe I need to double check the Docker settings and provide a ser2net docker-compose example.

**Comment by bikeymouse** [comment]
Yes, thanks for explaining, makes good sense.
And for both of you kudos for making this great software easily available!
