### ISSUE TITLE
LOG:  invalid length of startup packet

### ISSUE THREAD

**Issue by mupsje** [xirixiz/dsmr-reader-docker#302]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Alles werkt perfect maaaaar ik krijg een hoop foutmeldingen.

All works prefectly, but I get allot log about:
```
LOG:  invalid length of startup packet
```

### Expected behaviour

geen foutmelding

### Actual behaviour

zoals boven beschreven

### Steps to reproduce

nvt

### Docker info

```yaml
latest
```

### Version

version: '3'

services:
  dsmrdb:
    # When using Postgres, release 13.x is supported only
    # due to the limited availability of client packages, especially for arm32v7
    image: postgres:14-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /share/docker/dsmrdb:/var/lib/postgresql/data
    networks:
      vlan86:
        ipv4_address: 33333333333333
    mac_address: 33333333333333
    environment:
      - PUID=502
      - PGID=100
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=3333333333
      - POSTGRES_PASSWORD=333333333333
      - POSTGRES_DB=33333333333
    healthcheck:
      # postgres is the default user, please update with
      # the DJANGO_DATABASE_USER used for dsmr-reader-docker
      # default for DSMR Reader is 3333333333333
      test: [ "CMD-SHELL", "pg_isready -U 33333333333r" ]
      interval: 10s
      timeout: 5s
      retries: 10

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    depends_on:
      dsmrdb:
        condition: service_healthy
    container_name: dsmr
    links:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/docker/dsmr_backups:/app/backups
    networks:
      vlan86:
        ipv4_address: 33333333333
    mac_address: 3333333333333
    environment:
      - PUID=502
      - PGID=100
      - TZ=Europe/Amsterdam
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=333333333333
    ports:
      - 7777:80
      - 7779:443
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    # healthcheck:
    #   disable: true
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-Lsf",
          "http://127.0.0.1/about",
          "-o",
          "/dev/null",
          "-w",
          "HTTP_%{http_code}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  
networks:
  vlan86:
    name: qnet-static-vlan86
    external: true

### Docker compose

```yaml
nvt
```

### Container logs

PostgreSQL Database directory appears to contain a database; Skipping initialization
2022-12-06 16:20:27.039 CET [1] LOG:  starting PostgreSQL 14.6 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 32-bit
2022-12-06 16:20:27.039 CET [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-12-06 16:20:27.042 CET [1] LOG:  listening on IPv6 address "::", port 5432
2022-12-06 16:20:27.340 CET [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-12-06 16:20:27.437 CET [21] LOG:  database system was shut down at 2022-12-06 16:20:19 CET
2022-12-06 16:20:27.473 CET [1] LOG:  database system is ready to accept connections
2022-12-06 16:20:31.562 CET [29] LOG:  invalid length of startup packet

**Comment by xirixiz** [comment]
Hi, this seems to be an issue on the Postgres side (not related to DSMR).

**Comment by mupsje** [comment]
okidoki, ik ga kijken of ik een monitoring op de Qnap heb staan draaien ;)

**Comment by xirixiz** [comment]
@mupsje Is het nog gelukt om het issue op te lossen?

**Comment by mupsje** [comment]
nee , ben  nog aan het onderzoeken.
Als ik het gevonden heb dan laat ik iets weten.

**Comment by mupsje** [comment]
Opgelost,

Het had te maken met mijn CF Tunnel  :)

Dank voor het geduld,

meteen een ander vraagje.......  als het mag uiteraard
Kan ik oude gegevens van bijv.  Umeter importeren, of vanuit de oude HA omgeving?

groetjes en fijn  weekend

**Comment by xirixiz** [comment]
Lees het nu pas 😄. Mooi dat het opgelost is, en bedankt voor het delen.
