### ISSUE TITLE
Disable access logs

### ISSUE THREAD

**Issue by rogierlommers** [xirixiz/dsmr-reader-docker#304]
### Request

Hey! Still using your docker-compose file. Love it!
I have one question though: I see a lot of access logs.
Is it somehow possible to disable them?

```
dsmr-app      | 127.0.0.1 - - [07/Dec/2022:21:36:14 +0100] "GET /about HTTP/1.1" 200 13006 "-" "curl/7.83.1" "-"
dsmr-app      | 127.0.0.1 - - [07/Dec/2022:21:36:29 +0100] "GET /about HTTP/1.1" 200 13006 "-" "curl/7.83.1" "-"
dsmr-app      | 127.0.0.1 - - [07/Dec/2022:21:36:44 +0100] "GET /about HTTP/1.1" 200 13006 "-" "curl/7.83.1" "-"
```

I guess they come from [this](https://github.com/xirixiz/dsmr-reader-docker/blob/892588197808a458dea683afb95a8fba8741d28a/Dockerfile#L90), right? Simply disabling the healthchecks would fix them.

But what about the "normal" access logs? I'm not interested in them, since I get access logs from my reverse proxy. Is it possible to disable access logs in general?

**Comment by rogierlommers** [comment]
Hey @xirixiz , not sure if you accept merge requests.
But here you have one: https://github.com/xirixiz/dsmr-reader-docker/pull/305

**Comment by xirixiz** [comment]
Ofcourse I do! I like contributions/PR's! Thanks!

Will take a look at it later Today.

**Comment by xirixiz** [comment]
Released!

**Comment by rogierlommers** [comment]
> Released!

I [see](https://hub.docker.com/layers/xirixiz/dsmr-reader-docker/latest/images/sha256-a4cf2ee3636c247b34b6c78f1916f343caf63db899d3507a597b835a8e048056?context=explore), thanks! /me runs docker pull

**Comment by rogierlommers** [comment]
hmz.. it doesn't seem to work though:

```
root@dsmr_reader_docker:/app# cat /etc/nginx/conf.d/dsmr-webinterface.conf
upstream dsmr-webinterface {
    server unix:///tmp/gunicorn--dsmr_webinterface.socket fail_timeout=0;
}

server {
    listen      80;
    server_name _;  # No hostname available? Just use the default underscore here for wildcard matching.

	# Uncomment these lines below to force additional authentication on application access.
	# NOTE: Alter the IP-range '192.168.1.0/24' if you are using a different one (i.e.: 10.0.x.x)!
    # WARNING: Do not forget to generate a password first in '/etc/nginx/htpasswd' and then RELOAD nginx (TEST IT)!
##    satisfy    any;
##    allow      192.168.1.0/24;
##    deny       all;
##    auth_basic "Restricted application";
##    auth_basic_user_file /etc/nginx/htpasswd;

    location /static {
        alias /var/www/dsmrreader/static;
    }

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://dsmr-webinterface;
    }
}
```

**Comment by rogierlommers** [comment]
I would expect a line that says: `access_log off`

Can I somehow validate that [this function](https://github.com/xirixiz/dsmr-reader-docker/blob/master/rootfs/etc/cont-init.d/20-set-app-defaults#L320) has been executed?

**Comment by xirixiz** [comment]
The function hasn't been executed :). The function you created doesn't work unfortunatly.

-z should be -n .... fixing it now.

**Comment by xirixiz** [comment]
New release ready. Seems to work.

**Comment by rogierlommers** [comment]
yup, just re-deployed and indeed it works.
Thanks!
