### ISSUE TITLE
migrate seperate DSMR to docker DSMR

### ISSUE THREAD

**Issue by trekker25** [xirixiz/dsmr-reader-docker#31]
i used a dropbox backup file to migrate my standalone dsmr to dsmr running from docker.

used these steps:

docker-compose stop dsmr
docker exec -t dsmrdb dropdb dsmrreader -U postgres
docker exec -t dsmrdb createdb -O dsmrreader dsmrreader -U postgres
cat /tmp/<your_dump>.sql | docker exec -i dsmrdb psql -U postgres
docker-compose start dsmr

But in dsmr docker, my settings are not restored nor is there any previous data to be found.

The postgress file is about 180MB large. But i'm curious if my data is really restored??

**Comment by xirixiz** [comment]
Hi trekker, if I understand correctly you created a sql dumpfile in dropbox and you're trying to restore it to a volume of the docker postgres container?

**Comment by trekker25** [comment]
Yes indeed. 

Verstuurd vanaf mijn iPhone

**Comment by xirixiz** [comment]
Was the name of your old database also dmsrreader?

**Comment by trekker25** [comment]
I followed the default installation instructions so I assume it is. 
But the 180mb sql import only takes 30 seconds on a intel Nuc. 
And at the end gives lots of messages with “already exists”. 

Verstuurd vanaf mijn iPhone

**Comment by xirixiz** [comment]
Thanks for the extra info. I`ll verify the steps Tonight, I haven't used those for a while :)

**Comment by trekker25** [comment]
Ok thanks!

 

I’m curious about how the connection is made between dsmr docker and the dsmr-db docker?

 

Currently my dsmr docker is running, i imported the sql file, but the settings where missing (not sure if they are stored in a backup) and the data history was missing.

 

 

 

Van: Bram van Dartel <notifications@github.com> 
Verzonden: woensdag 26 september 2018 11:20
Aan: xirixiz/dsmr-reader-docker <dsmr-reader-docker@noreply.github.com>
CC: trekker25 <jhj.kempen@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [xirixiz/dsmr-reader-docker] migrate seperate DSMR to docker DSMR (#31)

 

Thanks for the extra info. I`ll verify the steps Tonight, I haven't used those for a while :)

**Comment by Martinvdm** [comment]
I have tried te do the same without succes. Migrated from pi to docker dsmr and tried to restore a dump from the Dropbox. All data is set in de dB but not content is visable in dsmr GUI. This thread was opened by me: https://github.com/dennissiemensma/dsmr-reader/issues/490

**Comment by xirixiz** [comment]
I haven't got time to look into this issue this weekend, I`ll look into it tomorrow evening.

**Comment by xirixiz** [comment]
Ok. I verified backup and restore Today. I supose you're using the default database and user environment variables as defined in the docker-compose file. If so, you can use the following steps to restore your sql dump file.

docker-compose stop dsmr
docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader
docker exec -t dsmrdb createdb -O dsmrreader dsmrreader -U dsmrreader
cat <your_dump>.sql | docker exec -i dsmrdb psql -U dsmrreader
docker-compose start dsmr

**Comment by xirixiz** [comment]
> I have tried te do the same without succes. Migrated from pi to docker dsmr and tried to restore a dump from the Dropbox. All data is set in de dB but not content is visable in dsmr GUI. This thread was opened by me: [dennissiemensma/dsmr-reader#490](https://github.com/dennissiemensma/dsmr-reader/issues/490)

I've update the mentioned issue as well with the info I've just provided to @trekker25

**Comment by xirixiz** [comment]
@trekker25 it's correct it doens't differ, because I've modified the documentation at https://github.com/xirixiz/dsmr-reader-docker :)

If you import your dropbox backup with the steps mentioned, you should see all your data again. Docker or non docker doesn't matter.
