### ISSUE TITLE
Volume dsmrdb?

### ISSUE THREAD

**Issue by JeeKee80** [xirixiz/dsmr-reader-docker#314]
### Request

Hi xirixiz,

allereerst bedankt voor alle effort om een docker image beschikbaar te stellen voor dsmr. Ik heb m al een tijd draaien en na een update enige tijd geleden viel me op dat de dsmrdb volume niet meer gebruikt werd (via portainer). Nu opnieuw alles geinstalleerd op een nieuwe pi met de standaard yaml voor t gemak en nu zie ik uberhaupt het volume niet meer. 

Doe ik nu iets verkeerd of is er iets veranderd? Of had ik iets moeten veranderen in de yaml?

thanks voor alle tijd en moeite!

**Comment by JeeKee80** [comment]
Oke, ben d'r achter. De relatieve locatieverwijzing voor de volumes maakt volgens mij dat ie niet standaard als volume lijkt te worden aangemerkt maar "gemapt" wordt naar je lokale data map en niet als volume wordt gezien. Hoe dan ook, nu als absolute locatieverwijzing in yaml gemaakt en werkt,

**Comment by mupsje** [comment]
> Oke, ben d'r achter. De relatieve locatieverwijzing voor de volumes maakt volgens mij dat ie niet standaard als volume lijkt te worden aangemerkt maar "gemapt" wordt naar je lokale data map en niet als volume wordt gezien. Hoe dan ook, nu als absolute locatieverwijzing in yaml gemaakt en werkt,

kun jij mij deze yaml eens delen aub.
Groet Remco
