### ISSUE TITLE
💡 HTTP redirect & HSTS

### ISSUE THREAD

**Issue by D1StrX** [xirixiz/dsmr-reader-docker#317]
### Request

Feature request for the Docker container nginx part;
- HTTP redirect to HTTPS environment variable
_Example:_ ENABLE_NGINX_SSL_REDIRECT=true
- Enable HSTS (Just additional security)
_Example:_ ENABLE_NGINX_ENABLE_HSTS=true

**Comment by xirixiz** [comment]
I`ll put it on the roadmap. Expect it somewhere in the end of Feb / beginning of March.

**Comment by xirixiz** [comment]
Finally 😄

https://github.com/xirixiz/dsmr-reader-docker/commit/5e33796af75e0cec68c6c788cfece5d448b5dbbb

**Comment by D1StrX** [comment]
Nice 😀
Should the hsts max age also be set to something you're own preference?
Just a minor details 😅

**Comment by D1StrX** [comment]
Heb de laatste image gepulled, maar de ENV lijkt nog niets te doen. Kan dat kloppen?

**Comment by xirixiz** [comment]
Klopt. Ik moet de image nog releasen.... doe ik morgen even. Mocht er iets mis zijn, dan heb ik de tijd om het weer te fixen ;)

**Comment by xirixiz** [comment]
Released! hsts max age voeg ik later nog wel een keer toe. Ik wil het ook niet overdrijven allemaal voor een tool als DSMR Reader.

**Comment by D1StrX** [comment]
Heb mn binnen gehaald, maar lijkt nog niet te redirecten. HSTS uitgelaten voor de eerste test.
Heb de ENV onder de DSMR container in `environment:` gezet
      - ENABLE_NGINX_SSL_REDIRECT=true
      - ENABLE_NGINX_ENABLE_HSTS=false
docker-compose down -> pull -> up
Mis ik nog iets?

**Comment by xirixiz** [comment]
Ja je mist inderdaad iets.... maar dat ligt aan mij. Ik heb iets niet goed gedaan, domme fout.
Fix ik vanavond even.... morgenochtend een werkende release

**Comment by D1StrX** [comment]
Geen probleem, zie het wel verschijnen 👍

**Comment by xirixiz** [comment]
Fixed... hopefully. De bakkerij is aan het werk. De nieuwe release is ongeveer over een half uur beschikbaar.

**Comment by D1StrX** [comment]
Helaas niet werkende voor mij, https werkt nu helemaal niet meer. Http wel nog, met geen redirect.

**Comment by xirixiz** [comment]
Ja, ik denk dat ik het hele nginx config stuk eruit ga slopen. Het is denk ik beter dat wanneer je een specifieke config wenst, dat je die dan mount in de container. Het geknip en geplak met bash is onbetrouwbaar helaas.

**Comment by D1StrX** [comment]
Zou je niet gewoon met de true/false input comment of uncomment van `redirect 301 https://$host$request_uri;` kunnen doen?
False -> var `# redirect 301 https://$host$request_uri;`
True -> var `redirect 301 https://$host$request_uri;`

**Comment by xirixiz** [comment]
Helaas is het wat complexer dan dat. Standaard staan de waarden niet in de config file.
Ik zal het er eens met Dennis Siemensma over hebben om dat in DSMR Reader op te nemen zodat het ook eenvoudig en bruikbaar is in Docker.

Hoe dan ook was het een geknoei op deze manier en daar hou ik niet van 😄 
Ik kom er nog op terug maar dan waarschijnlijk met een betere oplossing. Lukt dat niet dan is in mijn optiek een eigen config mounten nog het beste.
