### ISSUE TITLE
Consider alternate image registry to Docker Hub

### ISSUE THREAD

**Issue by bjw-s** [xirixiz/dsmr-reader-docker#324]
### Request

Since Docker Hub has been applying rate limits on image pulls for a while now, and their more recent move to scrap free teams I feel that Docker Hub is becoming more and more hostile towards the OSS/hobbyist community.

I would like to propose providing GitHub Container Registry as an alternative (or completely switching over to it) for the project.

Would you be open to this? If so, I'd be willing to write up a PR to help implement.

### Additional information

Additional CI improvement suggestions:
- Perhaps moving the build to use `docker buildx` to create an integrated manifest instead of writing and pushing separate manifests
- Use the native Github Actions concurrency feature (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) to cancel previous workflows

**Comment by xirixiz** [comment]
Open for this?? I love it and fully agree with you on this!

**Comment by bjw-s** [comment]
That's awesome! :) I'll see if I can whip up a PR somewhere today or tomorrow
