### ISSUE TITLE
Empty environment variable DOCKER_TARGET_RELEASE

### ISSUE THREAD

**Issue by hoorna** [xirixiz/dsmr-reader-docker#328]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/main/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The last published docker image contains the empty DOCKER_TARGET_RELEASE environment variable. I don't know if this variable existed before in previous image releases, but at least it wasn't empty then.

After creating an new DSMR container with a last update and published image (using docker-compose over an SSH connection), I always change the value of one of the environment variables using the Synology Docker package. Since the last release, this is no longer possible because the Synology Docker package does not accept empty variables. In the past I had no problem with that.

I don't know how to fix this. As a workaround, can I remove the DOCKER_TARGET_RELEASE environment variable with impunity or is it a bug in the docker image?

### Expected behaviour

-

### Actual behaviour

-

### Steps to reproduce

-

### Docker info

```yaml
-
```

### Version

-

### Docker compose

```yaml
-
```

### Container logs

-

**Comment by xirixiz** [comment]
HI, the ```DOCKER_TARGET_RELEASE``` is only used in the build proces and not required (should even not be defined!)  on starting a container. Please do not set this variable and you are fine. 

The variable is only meant to set a certain version on the docker image, so there is a distinction between the DSMR Reader version and the Docker image version.

**Comment by xirixiz** [comment]
Ah, I see now :).

```DSMR Reader Reader Docker release: ``` during startup. Something is wrong in the build process.

**Comment by xirixiz** [comment]
Ja, ik begrijp het issue. De variabele wordt gedefinieerd in het build proces en alleen gebruikt tijdens het run proces. Ik heb ook een Synology, maar heb dat issue niet eerlijk gezegd. Ik krijg gewoon bij het starten een lege regel te zien.

**Comment by hoorna** [comment]
Dankjewel voor het compliment. Fijn om te horen dan er een nieuwe build komt. Want dit issue was voor mij wel lastig.

Voor jou informatie: ik gebruiker docker-compose via SSH om de container te maken en daarna gebruik ik de GUI voor het monitoren van de container en voor eventuele aanpassingen.

**Comment by xirixiz** [comment]
Fixed: 
```
[ INFO ] DSMR Reader Reader release: 5.10.3
[ INFO ] DSMR Reader Reader Docker release: 2023.03.02
```

**Comment by hoorna** [comment]
It's working again as normal. Thank you for the very quick (with a few hours) service.
