### ISSUE TITLE
Postgresql v11 werkt niet meer.

### ISSUE THREAD

**Issue by koelkast88** [xirixiz/dsmr-reader-docker#33]
Voor de dsmrdb pakt hij nu (latest) postgres versie 11, die niet compatible is. Ik heb nu maar versie 10.4 genomen, daar doet 'ie het perfect mee. Moet de applicatie geupdate worden?

**Comment by Martinvdm** [comment]
Nee de documentatie bijgewerkt; je moet dit gebruiken als image:

image: postgres:10.5-alpine

**Comment by xirixiz** [comment]
Correct. Vandaar de compose file een tijd geleden is aangepast:
https://github.com/xirixiz/dsmr-reader-docker/blob/master/docker-compose.yaml

Desondanks, bedankt voor de melding :+1:

**Comment by koelkast88** [comment]
Aha! Dank! Ik gebruikte nog de oude compose file, containers worden automatisch bijgewerkt met watchtower. Dat ook maar even uitgezet trouwens, zo automatisch hoeft het allemaal niet te gaan :)
