### ISSUE TITLE
Some observations on the docker implementation

### ISSUE THREAD

**Issue by gctwnl** [xirixiz/dsmr-reader-docker#330]
### Request

Security improvements.

1. The UID for the DSMR nginx is hardcoded 100. That means the process runs as a user which may clash with another (it usurps the permissions of that user, e.g. _apt on ubuntu). While it is containerised, it is less secure than running as some separate guaranteed non-privileged user. Having the container work well with --user (or docker compose user: setting) would be an improvement.
2. The nginx config contains both conf.d and http.d of which only the latter is used
3. The nginx config accepts TLS v1.1. Time to be more strict.

**Comment by xirixiz** [comment]
Hi, thanks for your remarks! 

1. The user/uid used for DSMR is by default app/803. This default can be modified: https://github.com/xirixiz/dsmr-reader-docker#settings
2. Correct. This changed in the last release and will be fixed next release.
3. I agree and will fix it in the next release.

**Comment by xirixiz** [comment]
Updated the main branch for 2 and 3.
