### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by gctwnl** [xirixiz/dsmr-reader-docker#337]
### Request

I've setup a trial of DSMR Reader using this container. I first set this up simply to see if it would work, in as most vanilla/simple/default setup possible (keep everything as is), running it with compose. That means my env is:
```
# cat dsmr.env 
TZ=Europe/Amsterdam
DJANGO_TIME_ZONE=Europe/Amsterdam
DB_HOST=dsmrdb
DSMR_USER=dsmrreader
DSMR_PASSWORD=dsmrreader
DSMR_EMAIL=root@localhost
VIRTUAL_HOST=localhost
```
and
```
# cat postgres.env
TZ=Europe/Amsterdam
PG_TZ=Europe/Amsterdam
POSTGRES_USER=dsmrreader
POSTGRES_PASSWORD=dsmrreader
POSTGRES_DB=dsmrreader
```
This means I am using everything default including credentials. That is not an enormous problem as my setup is not exposed to the outside world. But it is something that needs to be fixed. I am looking for information on how in this setup to introduce better security (i.e. not using the standard credentials, for instance, and maybe add my (wildcard) certificate and use https (out of the box, http on 7777 is available, https on 7779 is not configured in nginx in the container, so probably is not possible?). Instructions on how to do this without losing existing data would be nice because I have no idea what to do in what order and where (GUI, env).

**Comment by xirixiz** [comment]
Hi, thanks for your request. Reading the things you desire it's more related to Docker itself and how to use it (port mapping for example). Within the README file on this page there is information on how to use certificates. It could be that it's missing important information, and if there is, please let me know so I can update it accordingly.
