### ISSUE TITLE
Upgrade the PostgreSQL client portion to version 15 in the docker-image

### ISSUE THREAD

**Issue by carhukem** [xirixiz/dsmr-reader-docker#340]
### Request

Hello,
Unfortunaly after upgrading the promoted and related integration Timescaledb in Home-Assistant one of the most imported features is not working anymore: the scheduled backup function. This because of an version difference between the DSMR reader docker-image package (Postgres version 14.5) and the upgraded TimescaleDB to PGSQL version 15.3

I'm aware of the fact that this problem is raised after the upgrade of another package. But after days searching and trying to communicate about this matter I see this question for help as a last resort ... before rubbing everything.

Although the solution seems to be easy: upgrade the PostgreSQL version from 14.5 to at least 15.3 in the docker image for DSMR reader I am aware of the fact that this is maybe not so simple as been written.

Is there anyway that, within the Home-Assistant context (running on Intel NUC, all dockers, supervised), the image portion for PostgresSQL can be updated easy? Docker-compose with alternate compose file? If there was an Home-Assistant driven solution to downgrade the TimescaleDB intergration the version 2.1.1 again, I allready had performed that.

Kind Regards.

**Comment by xirixiz** [comment]
It seems to be available. I`ll create a new release later Today.

https://pkgs.alpinelinux.org/packages?name=postgresql15-client&branch=v3.17&repo=&arch=&maintainer=
