### ISSUE TITLE
Missing docs / install & configure

### ISSUE THREAD

**Issue by bockelaar** [xirixiz/dsmr-reader-docker#342]
### Request

I am missing a step to step manual/guide to installing DSMR/docker. I get the dockerinstances running, but am not expierenced enough to get a postgresql docker running and connect it, let alone import my DB backup into it.

Is there any step by step guide to guide me to the end? :)

### Additional information

old DSMR on RPI4 crashed, reinstall leads to newer postgresql version with an AUTH incompatibility on django/website. So reinstall and restore is not working. Since docker is the future path i want to switch over but fail to find some guided helps.

**Comment by marcovn** [comment]
I recently moved my PI based install to the Docker version. Might be able to give you some guidance.

So you have a previous postures dump (*.sql file) AND a running docker setup including dsmr and dsmrb running?

**Comment by bockelaar** [comment]
thanks! 
Yes i have a dsmr backup. This backup is OK as i imported it into a new DSRM install and worked well. 
I have a PI4, setup with docker and can start the DSMR containers. I have no clue on howto start a postgresql container, which one (!?) and connect the 2, let alone howto restore the DB into that container :)
how to open up the dsmr interface to the LAN so i can connect to theDSMR GUI is another 'thingy' :)

**Comment by marcovn** [comment]
OK so this is about restoring the backup in a Docker based DSMR install.

First of all you want the docker compose stack of DSMR (includes both DSMR and postgresql). That is the easiest approach.

Follow the instructions at https://github.com/xirixiz/dsmr-reader-docker#run-with-docker-compose

Mind you that you can setup this environment NEXT to your existing DSMR first to test.

**Comment by bockelaar** [comment]
thanks! missed that in the instructions page, perhaps better paragraph that... running now through docker-compose. next try to import the backup :)

**Comment by bockelaar** [comment]
solved
