### ISSUE TITLE
Update path

### ISSUE THREAD

**Issue by kroona** [xirixiz/dsmr-reader-docker#349]
### Request

Ik krijg binnen DSMR reader meldingen over updates. Als je de link volgt kom je op readthedocks.io uit. Daar vind ik niks over de docker update, wat is hierin het juiste pad te volgen?

**Comment by xirixiz** [comment]
I`ll have a look and get back to it today

**Comment by kroona** [comment]
Ik gebruik de 5.11 image binnen DSMR reader.
Deze image. ghcr.io/xirixiz/dsmr-reader-docker:latest 

Ik zie met starten niet welke versie het is.

**Comment by xirixiz** [comment]
Dan moet het goed zijn :). Krijg je alsnog een update melding?
Kan je anders voor de zekerheid de image zelf eens pullen? Of nog beter, verwijderen en pullen:  
ghcr.io/xirixiz/dsmr-reader-docker:latest

**Comment by kroona** [comment]
Na afgelopen week niet meer. Is er een handleiding qua backups en updaten?

**Comment by xirixiz** [comment]
https://github.com/xirixiz/dsmr-reader-docker?tab=readme-ov-file#backup-and-restore-mechanism-1
