### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by Geertvdc** [xirixiz/dsmr-reader-docker#35]
Hi,

I tried running your docker container on a raspberry pi and of course this didn't work because your solution is based on a x86/x64 base image. 

I took the liberty to adjust some stuff so it works on ARM architectures in my fork: https://github.com/Geertvdc/dsmr-reader-docker 

What do you think. Do you want to merge it? (the script is quite different now that you run alpine) or shall i keep it in my own repository and support it there?

**Comment by xirixiz** [comment]
Hi Geert,

Good job! I`ll look into it Tonight. Perhaps we can arrange something together.

**Comment by Geertvdc** [comment]
I found an arm based alpine image yesterday evening so now everything looks identical to your code except for the base image.

**Comment by xirixiz** [comment]
I've been quiete busy lately, but I'll make some time soon...

**Comment by xirixiz** [comment]
Hi Geert, Today I've spent some time in automating/creating ARM32 and ARM64 based Docker images. As I type this the images are being pushed to the Docker Hub. 

See https://hub.docker.com/r/xirixiz/dsmr-reader-docker/tags/ for the available images.

I'm planning to automate the build pipeline in the future (like the default architecture image), but in the meanwhile the bash script with a Dockerfile template should do the trick.

Cheers
