### ISSUE TITLE
For you documentation: Homewizard P1 meter integration

### ISSUE THREAD

**Issue by mchangsp** [xirixiz/dsmr-reader-docker#363]
### Request

I wrote a post how to use your DSMR Reader Docker setup and DSMR Reader plugins to get Homewizard P1 meter data. This information was buried in Git issues from more than a year ago. You may wish to include it in your documentation https://community.home-assistant.io/t/dsmr-reader-docker-and-homewizard-p1-meter-integration/747265

**Comment by xirixiz** [comment]
Super! Added it to the docs. Thanks for your contribuion.

**Comment by mchangsp** [comment]
Graag gedaan! Waar heb je het gezet?

**Comment by mchangsp** [comment]
I see it: https://github.com/xirixiz/dsmr-reader-docker?tab=readme-ov-file#dsmr-reader---docker-and-homewizard-p1-meter-integration
