### ISSUE TITLE
Old Docker images uploaded to Docker Hub

### ISSUE THREAD

**Issue by jbrunink** [xirixiz/dsmr-reader-docker#38]
Hoi, 

It seems that (at least) for the amd64 version an old version has been uploaded to the Docker Hub registry.

```
$ docker pull xirixiz/dsmr-reader-docker
Using default tag: latest
latest: Pulling from xirixiz/dsmr-reader-docker
Digest: sha256:666af253003500d45242ee4f0f0eef4a315dd7077972cced39deb4246ae09275
Status: Image is up to date for xirixiz/dsmr-reader-docker:latest
```
`xirixiz/dsmr-reader-docker   latest              e8a6676a3c7c        3 weeks ago         204MB`

Thoughts on this?

Thank you.

best regards, Jurgen

**Comment by xirixiz** [comment]
Hi Jurgen,

Thanks! Something went wrong indeed. Not sure what yet, but I`m working on it....
