### ISSUE TITLE
DSMR 5 inlees interval

### ISSUE THREAD

**Issue by zoeperman** [xirixiz/dsmr-reader-docker#39]
Is het mogelijk om een variabele aan de docker toe te voegen met welke frequentie hij data in leest.
DSMR 5 leest iedere seconde data in, wat meestal overkill is en hoge cpu load geeft.
in DSMR is het in de config aan te passen, kan dat ook in de docker?

https://github.com/dennissiemensma/dsmr-reader/issues/413

**Comment by xirixiz** [comment]
Hi Zoeperman, I just created a new release. If you add docker environment variables like

DSMRREADER_BACKEND_SLEEP=60
DSMRREADER_DATALOGGER_SLEEP=60

The settings will be appended to the settings.py file at startup. I haven't tested it, but it should work.

**Comment by zoeperman** [comment]
I did this:

- editted the docker-compose.yaml and added 
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
      - DSMRREADER_BACKEND_SLEEP=60
      - DSMRREADER_DATALOGGER_SLEEP=60

- sudo docker-compose stop dsmr
- sudo docker-compose up -d
  * dsmrdb is up-to-date
  * Recreating dsmr ... done

but I still get a reading every second  (changed the vallue also to 10 and didn't have any effect)

**Comment by xirixiz** [comment]
Sorry, forgot to push the images hehehe....ready in an hour or so. 😄

**Comment by zoeperman** [comment]
hehe :)
no problem, will test it tomorrow then

**Comment by zoeperman** [comment]
i did this:

- sudo  docker pull xirixiz/dsmr-reader-docker
  * Status: Downloaded newer image for xirixiz/dsmr-reader-docker:latest

- added these 2 lines in the docker compose
  *  - DSMRREADER_BACKEND_SLEEP=60
  * - DSMRREADER_DATALOGGER_SLEEP=60

- sudo docker-compose stop dsmr
- sudo docker-compose up -d

now i get this on the website:
502 Bad Gateway
nginx

if i remove the 2 lines it works again

i don't see the variables in the docker file as well  (i think they should be there?)
https://hub.docker.com/r/xirixiz/dsmr-reader-docker/dockerfile

**Comment by xirixiz** [comment]
I`ll test it first before releasing again 😄. i`ll get back to you Tomorrow.

**Comment by zoeperman** [comment]
I did a new pull and it looks like it works now 👍 
setting the vallue to 60 results in 1 telegram in a minute.
Now setting the vallue to 5 giving me 10 results in a minute  (I thought it would be 12, but maybe thee is a delay or something > 60/5=12 ?)

now need to figure out what refreshrate is good enough to get good readings
in other words how many readings a second or is 1 per minute enough

**Comment by xirixiz** [comment]
The settings are only injected once, so once you stop a container and restart it, it will not modify the existing settings. I just modified the script so this is done every time a container is restarted. I`ll verify the image later Today and push it Tonight. For now, if you want to make sure new settings are applied just remove and recreate the dsmr container.
