### ISSUE TITLE
Splitsen van de interface en logger

### ISSUE THREAD

**Issue by ju5t** [xirixiz/dsmr-reader-docker#4]
Is het een idee om de interface en de logger te splitsen? Vooral omdat de kleine RPi die op de P1 poort aangesloten zit het anders wat zwaar voor z'n kiezen krijgt.

**Comment by xirixiz** [comment]
Goed idee! Ik had je pull request gemerged, maar helaas heb ik de dsmr-reader daarna niet werkend gekregen. Ik heb jouw aanpassingen in de brach ju5t geplaatst. Ik ga even onderzoeken wat er mis gaat. Waar heb jij de Docker container(s) op draaien (Synology, andere nas)?
