### ISSUE TITLE
DSMRREADER_BACKEND_SLEEP: unbound variable

### ISSUE THREAD

**Issue by SaturnusDJ** [xirixiz/dsmr-reader-docker#40]
Getting this error `DSMRREADER_BACKEND_SLEEP: unbound variable`.
This happens with and without passing the vars.

Back to v1.27.0 and problems gone.

At this time of the day no time to reproduce yet in a test environment. 😀
Oh and good thing these vars are being added. 👍 
Maybe add `DSMRREADER_MQTT_SLEEP` too?

**Comment by xirixiz** [comment]
Sorry, my bad....I pushed images untested. Fixed it this morning.
