### ISSUE TITLE
Ongeldige directory voor dsmr backups

### ISSUE THREAD

**Issue by ramondeklein** [xirixiz/dsmr-reader-docker#41]
Ik [zie dat in het docker-compose script](https://github.com/xirixiz/dsmr-reader-docker/blob/master/docker-compose.yaml#L9) de `/dsmr/backup` wordt geëxposed op de `dsmrdb` container. Ik zag daar ook geen backups verschijnen, maar ik zag dat er wel een dergelijke directory bestaat in de `dsmr` container. Kan het zijn dat je die directory bij de andere container moet exposen?

**Comment by xirixiz** [comment]
Hmm, daar heb je helemaal gelijk in 👌🏻. Ik ga dat van de week aanpassen, thanks!
