### ISSUE TITLE
Error while running update_image.sh

### ISSUE THREAD

**Issue by L2v2P** [xirixiz/dsmr-reader-docker#42]
I want to run your docker image on an Raspberry Pi 3. If I do **./update_images.sh --local --arch arm64v8 --debug** it fails at some point with the following error (in Dutch, translation is mine):

> sed: kan s|__QEMU_ARCH__|aarch64|g niet lezen: Bestand of map bestaat niet

>(sed: cannot read s|__QEMU_ARCH__|aarch64|g: File or folder does not exist)

Any idea on how to fix this?

**Comment by xirixiz** [comment]
Hi, why do you want to build the docker images yourself? The images are availbale on the Docker hub. However, I think the error might have something to do with the sed command. I use the script on a macbook, and I know sed differs from sed used on Linux systems.

```sed -i '' "s|__QEMU_ARCH__|${qemu_arch}|g" Dockerfile."${docker_arch}"```

I think the quotes have to be removed after -i for all sed commands, like this for example:
```sed -i "s|__QEMU_ARCH__|${qemu_arch}|g" Dockerfile."${docker_arch}"```

**Comment by L2v2P** [comment]
I don't want to build the images myself, but I interpreted "_You can create specific architecture files by running the update_hub_images.sh file. Dockerfile.cross is being used as input (template)._" as necessary to run things on a RPi.

If I just run **docker-compose up** it results in a continuously failing dsmr container: "standard_init_linux.go:207: exec user process caused "exec format error"". I thought this had something to do with the architecture, hence my building of images.

Any idea on how to solve this then?

**Comment by xirixiz** [comment]
That's correct. The docker-compose file is an example, you should modify the image of dsmr to the correct tag used for rpi.

for example:
```
xirixiz/dsmr-reader-docker:arm64v8-v1.28.0
```
or
```
xirixiz/dsmr-reader-docker:arm64v8-latest
```

Also you should modify the postgres image:
```
arm64v8/postgres:10-alpine
```

Then it should work out of the box

**Comment by L2v2P** [comment]
Ok. I guess my lack of Docker skills start to show. I've modified the **docker-compose.yaml** file as shown below, but still get the _"standard_init_linux.go:207: exec user process caused "exec format error""_ error. Am I still doing something wrong?

`version: '3.6'

services:
  dsmrdb:
    image: arm64v8/postgres:10-alpine
    container_name: dsmrdb
    volumes:
      - ./dsmrdb:/var/lib/postgresql/data
      - ./dsmrdb_backups:/dsmr/backups
    restart: always
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:arm64v8-latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    restart: always
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

#volumes:
#   dsmrdb:
#   dsmrdb_backups:`

**Comment by laurensvp** [comment]
Installing both 32 bit version of both the reader and postgres resulted into something that worked. Unfortunately it seems that I cannot use both this software and Domoticz in conjunction.
