### ISSUE TITLE
what does adding docker user to dialout group do?

### ISSUE THREAD

**Issue by RezzZ** [xirixiz/dsmr-reader-docker#45]
Hi, want to try out this docker but would like to understand what you mean with:

> You should first add the user you run Docker with on your host file system to the dialout group:
`sudo usermod -aG dialout $(whoami)`

Can you explain what this does and why it is required?

**Comment by xirixiz** [comment]
Connect/read/write to serial port as a non root user...

You could have found the answer just by googling the code 😉
