### ISSUE TITLE
Dubbele installatie Python requirements

### ISSUE THREAD

**Issue by ju5t** [xirixiz/dsmr-reader-docker#5]
In de `Dockerfile` worden de requirements voor de applicatie geïnstalleerd maar in `entrypoint.sh` gebeurt dit nog een keer. Alleen deze keer in een eigen virtualenv. Volgens mij is dat aan de ene kant dubbelop maar aan de andere kant ook overbodig. Je hebt voor alle applicaties dezelfde requirements en in supervisor wordt er verwezen naar dezelfde virtualenv. 

Zou het handiger zijn om virtualenv te laten vallen en alles gewoon globaal te installeren? Dat is wat ik meestal doe maar misschien is dat niet logisch.

Ik kan dit trouwens zelf wel recht trekken als je wilt. Dan zorg ik er gelijk voor dat de applicatie onder een unprivileged user draait. Het mag dan wel een container zijn maar dan nog wil je liever niet alles als root draaien.

**Comment by xirixiz** [comment]
Waarschijnlijk heb je gelijk. Nu er in de dsmr reader docs een verwijzing staat naar deze repo was ik sowieso van plan "het knutselwerk" te fatsoeneren. Ik ben nu even op vakantie, maar ik ga er van de week mee aan de slag.

**Comment by xirixiz** [comment]
Nice! Ik zie nu dat je al eea gedaan hebt in een fork. Ik check het van de week even.
