### ISSUE TITLE
Hoe te updaten?

### ISSUE THREAD

**Issue by remb0** [xirixiz/dsmr-reader-docker#51]
Ik draai met volle tevredenheid jou dockers dmv een dockercompose file.
Toch heb ik een vraag: ik wil namelijk antwoord kunnen geven op: 
https://github.com/dennissiemensma/dsmr-reader/issues/613
DSMRreader maakt namelijk wel backups maar niet naar mijn dropbox.
In de dockercompose heb ik:
    volumes:
      - ./Docker/dsmrdb:/var/lib/postgresql/data
      - ./Docker/dsmr_backups:/dsmr/backups    
waar ze inderdaad netjes staan.

Mijn idee is daarom: updaten (gelukt door de latest tage te gebruiken), logs aanpassen en kijken of het aan mijn docker config ligt of aan iets anders.  Als ik in portainer een console open ben ik niet de goede user.
als ik via putty inlog op de host weet ik vervolgens niet hoe via de docker commando's uit te voeren.

kan je me misschien wat tips geven?

**Comment by xirixiz** [comment]
Hoi remB0, ik maak ook backups naar Dropbox, dus als het goed is zou het bij mij ook niet goed moeten gaan. Ik zal het eens uitzoeken en dan post ik wat ik heb uitgezocht/gedaan om het te fixen.
