### ISSUE TITLE
No connection from DSMR with Mosquitto MQTT broker

### ISSUE THREAD

**Issue by JBS5** [xirixiz/dsmr-reader-docker#52]
Using Mosquitto MQTT broker as a Hass.io add-on and created a login for DSMR reader, but there will be no connection (request) from DSMR to Mosquitto MQTT. Also when using a wrong username/passwor in the DSMR configuration, there will be nothing in the Mosquitto MQTT log.  

Running this docker with docker dompose and using the newest version v2.0.2.

Any suggestions what could be the issue? Other application are able to connect to the same Mosquitto MQTT broker.

**Comment by xirixiz** [comment]
Hi JBS5, the docker-compose.yaml file has been renamed to docker-compose.example.yaml. The file is just an example how you could use dsmr reader. I think you might need to compare it to another docker-compose file you need which is able to connect to the Mosquitto MQTT broker.

Perhaps Mosquitto is running on a different Docker network, or host network?

**Comment by JBS5** [comment]
Thanks for your suggestion of a differrent Docker network @xirixiz. 
I checked the connection settings of MQTT.fx on my desktop and there is another port used which is configured at the Network settings of the Mosquitto MQTT Hass.io add-on. Using this port in DSMR Reader does fix the problem.
