### ISSUE TITLE
Hoe veilig te updaten naar laatste Docker-image?

### ISSUE THREAD

**Issue by bikeymouse** [xirixiz/dsmr-reader-docker#53]
Hi, ik gebruik momenteel met veel plezier DSMR-reader via jouw Docker image. 
Momenteel gebruik ik de image met DSMR 1.28 op een RPI2. E.a. gestart met Docker-compose met koppeling naar een volume voor behoud van de data, en ik gebruik Portainer voor het Docker-beheer.

Ik zou graag upgraden, maar lijkt me niet verstandig om gewoon de nieuwste Docker-image op te starten aangezien de database mogelijk van de nieuwe versie mogelijk niet backwards compatible is.

Hoe kan ik dit het beste aanpakken? Eerst op een of andere manier zorgen dat deploy.sh binnen de huidige Docker-container wordt uitgevoerd?

(excuus als dit niet de goede plek is voor dit soort vragen en mijn beperkte kennis van Docker, maar ik kon geen andere zinvolle plek vinden).

**Comment by xirixiz** [comment]
In de Documentatie heb ik beschreven op wat voor manier je een backup/dump kan maken voor de database. Ik weet niet precies hoe de docker-compose file eruit ziet, maar wanneer je een versie hebt ingesteld voor een specifieke Postgres versie, dan levert dat iig geen problemen op. Ik maak eerlijk gezegd nooit een backup, omdat ik een backup volume gemount heb op mijn nas waar Docker gebruik van maakt. Ik start dus altijd de laatste versie van de DSMR-reader Docker image en heb daar eerlijk gezegd nooit problemen mee gehad. 

Mocht je nog vragen hebben of niet helemaal begrijpen wat ik bedoel, stel gerust nog een vraag.

**Comment by bikeymouse** [comment]
Hi, dank voor je snelle reactie.

Ik ben een beetje beducht van het zomaar opstarten van de nieuwste Docker-image aangezien deze dan (al of niet met een nieuwe Postgress-Versie) connect met de oude database. 
Als er in de nieuwe DSMR-versie uitgegaan wordt van een andere database-structuur (i.e. niet bakcards compatible), kun je wellicht je database corrupt maken. Blijkbaar is dat tot nu toe niet gebeurd ;-)

Als je DSM-Reader direct op je OS installeert (dus buiten Docker), dan is de [upgrade procedure](url=https://dsmr-reader.readthedocs.io/en/latest/faq.html?highlight=upgrade#how-can-i-update-my-application) om daarvoor het script ./deploy.sh aan te roepen. Volgens de documentatie zou deze ook eventuele database-migraties uitvoeren. 

Ik weet niet of dat kan (ben geen Docker-deskundige), maar zou mogelijk zijn (en verstandig) om dat ook dat ook als stap in de Docker-image op te nemen? 
Of kan ik dat zelf op een of andere manier eerst in de "oude" Docker-container draaien, voordat ik de nieuwe opstart?

**Comment by xirixiz** [comment]
Wanneer je kijkt wat het deploy.sh/post-deploy.sh script doet heb ik een deel ondergebracht in een bash script, en een deel in de Dockerfile. Wanneer Docker start wordt er dus altijd een upgrade op de db uitgevoerd wanneer dat nodig is.

https://github.com/xirixiz/dsmr-reader-docker/blob/master/app/run.sh

Wanneer er dus een nieuwe release komt, dan breng ik een nieuwe Docker image uit, en wanneer je die dan start worden eventuele db migraties ook doorgevoerd.

**Comment by bikeymouse** [comment]
Ah, ik zie het, heel mooi, dus veilig upgraden. Heb het meteen uitgevoerd en zit nu weer op de laatste versie, dus het werkt prima, thanks!
