### ISSUE TITLE
X-Frame-Options sameorigin uitzetten in Django of filteren in NGINX?

### ISSUE THREAD

**Issue by search-tool** [xirixiz/dsmr-reader-docker#54]
Niet zozeer een issue maar een vraag;

Wil graag de dsmr-reader embedden in een iframe panel in HASS, nu ben ik tegen gekomen dat  het framework deze header meestuurt echter kom ik niet veel config tegen of dat nu vanuit de app of default enabled is.

Heeft iemand een idee hoe ik dit kan uitzetten in Django en of kan filteren in NGINX.
Het gaat iedergeval om de clickjacking module in Django.
daarnaast kan het natuurlijk ook zo zijn dat dit vooral in de dsmr reader app zelf aangepast moet worden ipv hier in de docker image.

Groet!

**Comment by xirixiz** [comment]
Misschien heb je hier iets aan:
https://github.com/dennissiemensma/dsmr-reader/issues/344

Ik kan de optie opnemen in Docker zodat het bij het starten gezet wordt in settings.py. Laat maar weten of het werkt, dan kan ik het daarna opnemen in Docker.

**Comment by search-tool** [comment]
Aah die hadden we kunnen googelen! :)

Beide opties in de docker container getest, `dsmrreader/settings.py` aangepast en ze werken!
```
X_FRAME_OPTIONS = 'ALLOWALL'
X_FRAME_OPTIONS = 'ALLOW-FROM http://hassio.local/'
```
optie als environment variabele zou handig zijn, tot die tijd kun je de file makkelijk vinden met `find / -name settings.py`

Thanks!

**Comment by cyberjunky** [comment]
Is er nu een manier om X_FRAME_OPTIONS = 'ALLOWALL' ergens persistant te definieren als je de docker image gebruikt?
Excuses als ik er eventueel overheen gelezen.

**Comment by vdbrink** [comment]
kan dit ondertussen al via de docker-compose file?

**Comment by vdbrink** [comment]
Het kan inderdaad!

docker-compose.yaml
```
...
dsmr:
....
  environment:
    - DJANGO_X_FRAME_OPTIONS=ALLOWALL
```
