### ISSUE TITLE
Run as different user?

### ISSUE THREAD

**Issue by rsenden** [xirixiz/dsmr-reader-docker#55]
I have a docker-compose file that starts (among others) the dsmr-reader-docker container. 

For most containers, I can specify the user id/group used to run the main processes within the container:

* Most containers that use supervisord can be configured with the `PUID` and `PGID` environment variables, telling supervisord to start processes with the given user/group. 
* Most containers that just run a single process (i.e. not using supervisord) can be started using the `- user: someUser:someGroup` docker-compose option.

Neither of these approaches work with dsmr-reader-docker; with the `- user: someUser:someGroup` option supervisord fails to start up, and the PUID/PGID environment variables don't seem to be taken into account for this container. In fact, `/etc/supervisor.d/supervisord.ini` has the root user hardcoded.

Would it be possible to update the container to use the PUID/PGID environment variables if defined, falling back to `root` if these variables have not been defined?

**Comment by xirixiz** [comment]
Hi,

I have several more improvements which I'd like to apply. I`ll also implement this, as I would like to have it myself as well.

Probable next weekend I`m going to release a new Docker image with a lot of extra configuration features.

Regards

**Comment by rsenden** [comment]
Thanks a lot, looking forward to the new image.

**Comment by xirixiz** [comment]
Hi, could you please test with this image: test-latest and use the following environment variables in your docker-compose file (adjust the values to your need):

```
    environment:
      - TZ=Europe/Amsterdam
      - LOGLEVEL=info # debug, warn, trace.
      - AUTORESTART_DATALOGGER=true
      - DB_HOST=dsmrdb
      - DAEMON_USER=root
      - DAEMON_GROUP=root
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
```
