### ISSUE TITLE
TimeZone not being picked up

### ISSUE THREAD

**Issue by jorkzijlstra** [xirixiz/dsmr-reader-docker#56]
Hoi Bram,

Ik probeer dus de timezone hetzelfde te krijgen als de server waarop de docker instantie draait.

In mijn docker compose heb ik nu het volgende staan
```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Amsterdam
```
Het commando `date` geeft alleen nog steeds aan dat het UTC is.

Het gaat werken wanneer ik de package `tzdata` installeer in de docker image.
`apk add --no-cache tzdata`. `date` heeft nu aan dat het CEST is.

Doe ik nog iets verkeerd in de docker compose of is het probleem idd de missende package?

Grt, Jork

**Comment by ju5t** [comment]
Je hebt `tzdata` nodig als je de `TZ` environment variabele wilt gebruiken. Je hoeft dan geen volumes mee te geven. Lijkt mij een prima reden voor een PR.

**Comment by jorkzijlstra** [comment]
heb deze geopend: #57

**Comment by xirixiz** [comment]
tzdata voeg ik toe aan de image. Ik zag het pull request pas later dus had lokaal de code al aangepast. Hoe dan ook, bedankt voor de bijdrage @jorkzijlstra
