### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by daansan** [xirixiz/dsmr-reader-docker#59]
I'm trying to run your docker image but when using the docker compose file I'm getting a 502 Bad Gateway error from Nginx. It appears that the dsmr application itself is not running. Would you have any idea why this could be the case?

**Comment by xirixiz** [comment]
Could you share the logfiles please? Thanks!

**Comment by daansan** [comment]
Which logfiles would you want to see?

**Comment by xirixiz** [comment]
/tmp/supervisord.log
/var/log/nginx/error.log

or maybe docker logs -f <container>

**Comment by daansan** [comment]
/tmp/supervisord.log : https://pastebin.com/tQSZnDbj
/var/log/nginx/error.log : empty file
docker logs -f dsmr: https://pastebin.com/3NgmmjvG

**Comment by daansan** [comment]
fyi: restarted the docker container and copied the logs post-restart

**Comment by xirixiz** [comment]
Thanks! The process seems to be running fine, however I noticed custom_logging being set. Can you provide the docker-compose content  or docker run command you're using?

**Comment by daansan** [comment]
Below are the services within my docker-compose file I use for DSMR.. Currently i'm exposing postgres to my local network but I previously used docker dependencies (commented out). That also worked fine.

When I go to the console of the DSMR container and invoke curl localhost:80 this also gives me the same 502 error

  dsmrdb:
    container_name: dsmrdb
    image: postgres:10.5-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    container_name: dsmr
    image: xirixiz/dsmr-reader-docker
#    depends_on:
#      - dsmrdb
#    links:
#      - dsmrdb
#    networks:
#      - dsmr
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmr_backups:/dsmr/backups
    environment:
      - TZ=${TZ}
      - DSMR_LOGLEVEL=WARNING
      - DB_HOST=192.168.6.220
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 2506:80
      - 2507:443

**Comment by xirixiz** [comment]
I`m missing the device, and maybe the loglevel isn't allowed, I should make a verification on it. However, the below config should work, well if you're using /dev/ttyUSB0, otherwise you have to change that. Could you please test the below compose file?

`
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmrdb:/var/lib/postgresql/data
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker
    container_name: dsmr
    network_mode: bridge
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmr_backups:/dsmr/backups
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - DSMR_LOGLEVEL=DEBUG
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 2506:80
      - 2507:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
`

**Comment by daansan** [comment]
do I need the device? I want to use a remote logger on a Raspberry Pi to feed the data to my dsmr-reader on my server, that is why I left it out.. The cable as such is also not connected to this server

**Comment by xirixiz** [comment]
Ah, ok, then you won't need it indeed.

**Comment by daansan** [comment]
Jus tested below config and still get the 502 bad gateway error.

i believe the only difference is the device and nothing else. Is the device required for the docker image to work or not?

` dsmrdb:
    container_name: dsmrdb
    image: postgres:10.5-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - dsmr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    container_name: dsmr
    image: xirixiz/dsmr-reader-docker
    depends_on:
      - dsmrdb
    links:
      - dsmrdb
    networks:
      - dsmr
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/docker/dsmr_backups:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - DSMR_LOGLEVEL=DEBUG
      - DB_HOST=dsmrdb
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 2506:80
      - 2507:443

networks:
  dsmr:
    driver: bridge
`

**Comment by xirixiz** [comment]
I think so when looking at the code for Docker as well as DSMR Reader. You could mount just a device as /dev/ttyUSB0 and give it a try ofcourse.

**Comment by daansan** [comment]
I can make it work by giving 'others' write access to the sock file:
chmod 777 /var/tmp/gunicorn--dsmr_webinterface.socket

However, when I reboot, the write flag is removed again, probably because the /var/tmp folder isn't mounted as a volume.

My docker does not run as the root user on my host, on another installation where I do run docker as 'root' on the host, I notice that the o=w flag always is enabled by default and the dsmr dashboard as such will be working.

Would you have any clue why in my installation o=w is automatically disabled for the sock file?

Thanks.
