### ISSUE TITLE
cannot start after upgrade

### ISSUE THREAD

**Issue by zoeperman** [xirixiz/dsmr-reader-docker#63]
after upgrading to new version docker won's start.
any idea? also did add SDgroup as root and my own user but didn't help

zoeperman@zoepermanhs:~/docker/DSMR$ sudo docker-compose up
Starting dsmrdb ... done
Recreating dsmr ... done
Attaching to dsmrdb, dsmr
[ INFO ] Checking if the DSMR web credential variables have been set...
dsmrdb    | 2019-08-11 13:35:16.313 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dsmrdb    | 2019-08-11 13:35:16.313 CEST [1] LOG:  listening on IPv6 address "::", port 5432
dsmrdb    | 2019-08-11 13:35:16.326 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dsmrdb    | 2019-08-11 13:35:16.361 CEST [18] LOG:  database system was shut down at 2019-08-11 13:34:40 CEST
dsmrdb    | 2019-08-11 13:35:16.371 CEST [1] LOG:  database system is ready to accept connections
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Verifying if Postgres in running...
[ INFO ] Adding setting DSMRREADER_BACKEND_SLEEP...
[ INFO ] Adding setting DSMRREADER_DATALOGGER_SLEEP...
[ INFO ] Running post configuration...
dsmr      | Operations to perform:
dsmr      |   Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_frontend, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
dsmr      | Running migrations:
dsmr      |   No migrations to apply.
dsmr      |
dsmr      | 2046 static files copied to '/var/www/dsmrreader/static'.
dsmr      | admin already exists
[ INFO ] Starting supervisord...
dsmr      | /usr/lib/python2.7/site-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
dsmr      |   'Supervisord is running as root and it is searching '
dsmr      | Error: Format string '%(ENV_DAEMON_USER)s' for 'supervisord.user' contains names ('ENV_DAEMON_USER') which cannot be expanded. Available names: ENV_AUTORESTART_DATALOGGER, ENV_DB_HOST, ENV_DB_NAME, ENV_DB_PASS, ENV_DB_PORT, ENV_DB_USER, ENV_DSMRREADER_BACKEND_SLEEP, ENV_DSMRREADER_DATALOGGER_SLEEP, ENV_DSMR_EMAIL, ENV_DSMR_PASSWORD, ENV_DSMR_USER, ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_PATH, ENV_PWD, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_QEMU_EXECVE, ENV_SD_AUTORESTART_DATALOGGER, ENV_SD_GROUP, ENV_SD_LOGLEVEL, ENV_SD_USER, ENV_SHLVL, ENV_TZ, ENV_VIRTUAL_HOST, ENV__, here
dsmr      | For help, use /usr/bin/supervisord -h

`version: '3.6'

services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:test-latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - SD_LOGLEVEL=info
      - SD_AUTORESTART_DATALOGGER=true
      - DB_HOST=dsmrdb
      - DB_USER=dsmrreader
      - DB_PASS=dsmrreader
      - DB_PORT=5432
      - SD_USER=root
      - SD_GROUP=root
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
      - DSMRREADER_BACKEND_SLEEP=5
      - DSMRREADER_DATALOGGER_SLEEP=5
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

#volumes:
#   dsmrdb:
#   dsmrdb_backups:
`

**Comment by xirixiz** [comment]
You’re using te latest test image, please use another tag or just latest, then it’ll work 😁👍🏻

**Comment by ju5t** [comment]
The update hasn't been particularly flawless. We had to manually remove the dsmr container for it to work. We're also seeing dsmr_mqtt crashing constantly.

```
[2019-08-12 10:07:07,672] WARNING  MQTT | No hostname found in settings, restarting in a minute...
```

What are we missing? Perhaps one of the undocumented environment variables?

**Comment by zoeperman** [comment]
i get this error in logging, seems also configurable something to add in conf?

`
2019-08-12 10:47:17,575 INFO success: dsmr_mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2019-08-12 10:48:18,310 INFO exited: dsmr_mqtt (exit status 1; not expected),
2019-08-12 10:48:19,314 INFO spawned: 'dsmr_mqtt' with pid 2347`

https://github.com/dennissiemensma/dsmr-reader/issues/543

**Comment by xirixiz** [comment]
dsmr_mqtt issue has been there for a while already, I`ll add a solution it in the next release (enable or disable mqtt).

@ju5t The message you receive I haven't seen before and doesn't seem to be related to the latest release.

**Comment by ju5t** [comment]
@xirixiz I think it's the same error as @zoeperman is seeing. I don't think it is related either but I never noticed it before as I never had issues upgrading the containers until this release.
