### ISSUE TITLE
New required environment variables

### ISSUE THREAD

**Issue by adebree** [xirixiz/dsmr-reader-docker#66]
I just upgraded and the container kept restarting. 

```
 INFO ] Starting supervisord...
/usr/lib/python2.7/site-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Error: Format string '%(ENV_SD_USER)s' for 'supervisord.user' contains names ('ENV_SD_USER') which cannot be expanded. Available names: ENV_AUTORESTART_DATALOGGER, ENV_DB_HOST, ENV_DB_NAME, ENV_DB_PASS, ENV_DB_USER, ENV_DSMR_EMAIL, ENV_DSMR_LOGLEVEL, ENV_DSMR_PASSWORD, ENV_DSMR_USER, ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_PATH, ENV_PWD, ENV_PYTHON_GET_PIP_SHA256, ENV_PYTHON_GET_PIP_URL, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_QEMU_EXECVE, ENV_SHLVL, ENV_TZ, ENV_VIRTUAL_HOST, ENV__, here
```

After adding the following to starting the container it worked again. Could these be documented?

```
      - SD_USER=root
      - SD_GROUP=root
      - SD_LOGLEVEL=info
      - SD_AUTORESTART_DATALOGGER=true
```

**Comment by xirixiz** [comment]
It's in the docker-compose example file. However, In the future I`ll document all required and all optional vars. I`ll think I`ll release it in the upcoming version.

**Comment by adebree** [comment]
Awesome! Thanks for the work :)

Unfortunately they are not in the example file: https://github.com/xirixiz/dsmr-reader-docker/blob/master/docker-compose.example.yaml (or did you reference another example?)

**Comment by xirixiz** [comment]
I just updated the compose example. I should have created a new branch but I didn't...

**Comment by RezzZ** [comment]
Hi @xirixiz, the updated file still doesn't show these four required variables. Also the README.md file is still mentioning these variables as optional

**Comment by xirixiz** [comment]
Hi Rezz, see the last comment...

**Comment by RezzZ** [comment]
I did, and the variables:
```
      - SD_USER=root
      - SD_GROUP=root
      - SD_LOGLEVEL=info
      - SD_AUTORESTART_DATALOGGER=true
```
are not included in your example file. Just mentioning this so others don't have problems when using your docker image.

**Comment by xirixiz** [comment]
That's what I mentioned :D. The docu has already been updated for the next release, but the next release hasn't been uploaded yet, therfor the variables aren't noted as mandatory in the documentation anymore, as they aren't in the upcoming release 😄

**Comment by RezzZ** [comment]
ahh ok. so you updated your local files. not pushed the files to git yet. That wasn't clear to me. Thanks and keep up the good work!
