### ISSUE TITLE
Docker container keeps restarting

### ISSUE THREAD

**Issue by bart1604** [xirixiz/dsmr-reader-docker#67]
`[ INFO ] Checking if the DSMR web credential variables have been set...,

[ INFO ] Fixing /dev/ttyUSB* security...,

[ INFO ] Removing existing PID files...,

[ INFO ] Verifying if Postgres in running...,

[ INFO ] Running post configuration...,
Operations to perform:,
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_frontend, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions,
Running migrations:,
  No migrations to apply.,
,
2046 static files copied to '/var/www/dsmrreader/static'.,
admin already exists,

[ INFO ] Starting supervisord...,
/usr/lib/python2.7/site-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.,
  'Supervisord is running as root and it is searching ',
Error: Format string '%(ENV_DAEMON_USER)s' for 'supervisord.user' contains names ('ENV_DAEMON_USER') which cannot be expanded. Available names: ENV_AUTORESTART_DATALOGGER, ENV_DB_HOST, ENV_DB_NAME, ENV_DB_PASS, ENV_DB_USER, ENV_DSMR_EMAIL, ENV_DSMR_PASSWORD, ENV_DSMR_USER, ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_PATH, ENV_PWD, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_QEMU_EXECVE, ENV_SD_AUTORESTART_BACKEND, ENV_SD_AUTORESTART_DATALOGGER, ENV_SD_AUTORESTART_MQTT, ENV_SD_AUTOSTART_BACKEND, ENV_SD_AUTOSTART_DATALOGGER, ENV_SD_AUTOSTART_MQTT, ENV_SD_GROUP, ENV_SD_LOGLEVEL, ENV_SD_USER, ENV_SHLVL, ENV_TZ, ENV_VIRTUAL_HOST, ENV__, here,
For help, use /usr/bin/supervisord -h,`

Hi,

I've used your own docker-compose.yaml which we can find at:
https://raw.githubusercontent.com/xirixiz/dsmr-reader-docker/master/docker-compose.example.yaml

My container keeps "rebooting", above you can find the logs -> which i find in portainer.

Thanks for any help!

**Comment by xirixiz** [comment]
https://github.com/xirixiz/dsmr-reader-docker/issues/63
