### ISSUE TITLE
Docker container can't start

### ISSUE THREAD

**Issue by jorkzijlstra** [xirixiz/dsmr-reader-docker#68]
I just updated to the latest image `xirixiz/dsmr-reader-docker:arm64v8-latest` by pulling the latest image with the command `docker-compose pull` and then executing `docker-compose up -d` and the docker keeps restarting with the following exception.

```
  'Supervisord is running as root and it is searching '
Error: Format string '%(ENV_SD_USER)s' for 'supervisord.user' contains names ('ENV_SD_USER') which cannot be expanded. Available names: ENV_AUTORESTART_DATALOGGER, ENV_DB_HOST, ENV_DB_NAME, ENV_DB_PASS, ENV_DB_USER, ENV_DSMR_EMAIL, ENV_DSMR_LOGLEVEL, ENV_DSMR_PASSWORD, ENV_DSMR_USER, ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_PATH, ENV_PWD, ENV_PYTHON_GET_PIP_SHA256, ENV_PYTHON_GET_PIP_URL, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_QEMU_EXECVE, ENV_SHLVL, ENV_VIRTUAL_HOST, ENV__, here
For help, use /usr/bin/supervisord -h
```

I saw that the `SD_USER` is specified a ENV so I'm not sure what the problem is.

my docker-compose file contains:
```
  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:arm64v8-latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - /home/dsmr-reader/dsmrdb:/var/lib/postgresql/data
      - /home/dsmr-reader/dsmr_backups:/dsmr/backups
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp:/tmp
      - /var/log/nginx:/var/log/nginx
    environment:
      - DB_HOST=dsmrdb
      - DSMR_USER=dsmrreader
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=dsmrreader
      - DSMR_LOGLEVEL=DEBUG
      - VIRTUAL_HOST=localhost
    ports:
      - 80:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```

Any idea what the problem might be?

**Comment by xirixiz** [comment]
https://github.com/xirixiz/dsmr-reader-docker/issues/63

**Comment by jorkzijlstra** [comment]
#63 says the issue is using a wrong tag, but I'm using the latest here and did just pulled the latest image. Removing the image and recreating it didn't help.

**Comment by xirixiz** [comment]
Read about the variables...

**Comment by jorkzijlstra** [comment]
I will, according to the readme the SD variables are optional so I thought I didn't need to ad them

**Comment by xirixiz** [comment]
Ah, true, I updated the docs today already for the upcoming release. Sorry

**Comment by jorkzijlstra** [comment]
after adding them it works. Thnx

**Comment by jorkzijlstra** [comment]
> Ah, true, I updated the docs today already for the upcoming release. Sorry

Ah, this is why I saw they where defined in the Dockerfile.cross and thought this couldn't be the issue.

Great work maintaining this repo
