### ISSUE TITLE
 Error: Format string '%(ENV_SD_USER)s' for 'supervisord.user' contains names ('ENV_SD_USER') which cannot be expanded.

### ISSUE THREAD

**Issue by SaturnusDJ** [xirixiz/dsmr-reader-docker#69]
Upgraded from arm32v6-v2.2.1 to arm32v6-v2.2.3:

`Error: Format string '%(ENV_SD_USER)s' for 'supervisord.user' contains names ('ENV_SD_USER') which cannot be expanded. Available names: ENV_AUTORESTART_DATALOGGER, ENV_DB_HOST, ENV_DB_NAME, ENV_DB_PASS, ENV_DB_USER, ENV_DSMRREADER_BACKEND_SLEEP, ENV_DSMRREADER_DATALOGGER_SLEEP, ENV_DSMRREADER_MQTT_MAX_MESSAGES_IN_QUEUE, ENV_DSMRREADER_MQTT_SLEEP, ENV_DSMR_EMAIL, ENV_DSMR_PASSWORD, ENV_DSMR_USER, ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_PATH, ENV_PWD, ENV_PYTHON_GET_PIP_SHA256, ENV_PYTHON_GET_PIP_URL, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_QEMU_EXECVE, ENV_SHLVL, ENV__, here`

Of course not sure if this is error due to the Docker image or the application itself.

By the way, how come the docker image is 220MB while the extracted dsmr-reader-master is 35MB?

**Comment by xirixiz** [comment]
https://github.com/xirixiz/dsmr-reader-docker/issues/62

**Comment by SaturnusDJ** [comment]
I had to specify all of the SD env vars to get it working again. I don't know why since it should have reverted to default.
