### ISSUE TITLE
 dsmr_datalogger (exit status 1; not expected)

### ISSUE THREAD

**Issue by daemenseth** [xirixiz/dsmr-reader-docker#7]
When I start the docker images I see the following:

dsmr          | 2017-11-30 07:57:01,030 INFO spawned: 'dsmr_datalogger' with pid 139
dsmr          | 2017-11-30 07:57:01,520 INFO exited: dsmr_datalogger (exit status 1; not expected)

The webinterface does also not come online.
What can be the issue?

**Comment by xirixiz** [comment]
I just checked and I've got the same issue. I`ll fix it and come back to you later Today.

**Comment by xirixiz** [comment]
Could you please retry. I rolled back the latest pull request.
I will first verify and fix any issues that occur with the ju5t branch.

**Comment by ju5t** [comment]
Are you guys running this on Synology?

I'm running this on a system with multiple web-facing containers. Web traffic is orchestrated through 1 container called `jwilder/nginx-proxy`. This picks up the `VIRTUAL_HOST` environment variable set on all other containers and sets up virtual hosts for them. The `dsmr-reader-docker` container exports all static content for the `nginx-proxy` container to serve. 

It could be that Synology has its own or a different solution to this. I can imagine something is not right with my implementation. I'll come up with a solution for this in the next few days probably.

**Comment by daemenseth** [comment]
Now I get:

ERROR: Cannot locate specified Dockerfile: Dockerfile

**Comment by xirixiz** [comment]
I`m running Manjaro Linux Ju5t...

@daemenseth: Did you clone this github repo? As you can see the Dockerfile is available.
You should run docker-compose up --build within the project directory.

**Comment by ju5t** [comment]
`docker-compose.yml` was missing the `devices` configuration. I've also made sure the default external port is set to 8888 again as the README explains and dropped the need for a proxy container.

This should solve all issues with the ju5t-branch. I've tested a vanilla installation on MacOS and Debian 9 on a Raspberry Pi.

**Comment by daemenseth** [comment]
its working now I forget the build option
