### ISSUE TITLE
Naming of the Environment Variables

### ISSUE THREAD

**Issue by bikeymouse** [xirixiz/dsmr-reader-docker#72]
Hi, I have some issues with the proper naming of the Environment Variables. 
If I use the naming in the [readme](https://github.com/xirixiz/dsmr-reader-docker/blob/master/README.md) I get this error:

_Error: Format string '%(ENV_SD_START_DATALOGGER)s' for _'program:dsmr_datalogger.autostart' contains names ('ENV_SD_START_DATALOGGER') which cannot be expanded.__ 

Only after renaming the Environment Variables: 
      - SD_AUTOSTART_DATALOGGER
      - SD_AUTOSTART_BACKEND
      - SD_AUTOSTART_MQTT
To:
      - SD_START_DATALOGGER
      - SD_START_BACKEND
      - SD_START_MQTT

I got this working after looking at the [supervisord.ini](https://github.com/xirixiz/dsmr-reader-docker/blob/master/app/supervisord.ini) file. 

So I guess either the documentation (in the [readme](https://github.com/xirixiz/dsmr-reader-docker/blob/master/README.md) and the [example docker compose](https://github.com/xirixiz/dsmr-reader-docker/blob/master/docker-compose.example.yaml)) is wrong or this is a bug the duspervisord.ini file?

**Comment by bikeymouse** [comment]
Ik kom er nu achter dat andere omgevevingsvariabelen opeens ook niet meer gebruikt lijken te worden als ik deze in de docker-compose.yaml opneem. 
Zoals die DSMRREADER_BACKEND_SLEEPen DSMRREADER_DATALOGGER_SLEEP.
Ik dacht dat dit aan DSMR lag [en heb daar een melding gemaakt](https://github.com/dennissiemensma/dsmr-reader/issues/729), maar als ik dit [conform de handleiding](https://dsmr-reader.readthedocs.io/nl/latest/settings.html#dsmrreader-backend-sleep) direct aanpas in dsmrreader/settings.py dan werkt het wel. Misschien ligt het aan deze docker image?

**Comment by xirixiz** [comment]
....stupid of me... I made the necessary changes after the last update on github and not in my build pipeline....so indeed this issues appear therefor. I've synced all changes now, so everything should be fine in the next release.

**Comment by xirixiz** [comment]
Aan DSMRREADER_BACKEND_SLEEP en DSMRREADER_DATALOGGER_SLEEP is niets gewijzigd en werkt bij mij ook gewoon wanneer ik de laatste Docker image start...

**Comment by bikeymouse** [comment]
Hij  zou die environment waarden die je meegeeft toch in dsmrreader/settings.py moeten schrijven? Dat gebeurt bij mij niet. Als ik dat in de Docker container met de hand aanpas werkt het wel.

**Comment by xirixiz** [comment]
Probeer het eens met de onderstaande variabelen:
- DSMR_BACKEND_SLEEP
- DSMR_DATALOGGER_SLEEP

**Comment by xirixiz** [comment]
I just added a changelog. Next update I`ll fix all issues and update the changelog accordingly.

**Comment by bikeymouse** [comment]
Ah, net een andere naam! Ga het proberen, thanks. 
Deze staan overigens niet in de Readme beschreven, of in de voorbeeld Docker-compose.yaml Misschien handig om dat nog even toe te voegen? 🤗

**Comment by bikeymouse** [comment]
> ....stupid of me... I made the necessary changes after the last update on github and not in my build pipeline....so indeed this issues appear therefor. I've synced all changes now, so everything should be fine in the next release.

I just pulled the new image, but I'm afraid it still gives me the same errors.
I have to use 
- SD_START_DATALOGGER
- SD_START_BACKEND
- SD_START_MQTT
To get it working.

**Comment by bikeymouse** [comment]
> Probeer het eens met de onderstaande variabelen:
> 
> * DSMR_BACKEND_SLEEP
> * DSMR_DATALOGGER_SLEEP

Ok nu worden die waarden inderdaad in de dsmrreader/settings.py file geschreven. 
Echter...dat is niet juist, je moet de volgende waarden gebruiken:

DSMRREADER_BACKEND_SLEEP
DSMRREADER_DATALOGGER_SLEEP

**Comment by xirixiz** [comment]
Ah, ik zie het, vanavond release ik een nieuwe versie met een fix

**Comment by bikeymouse** [comment]
Top, dank voor al het goede werk!

**Comment by xirixiz** [comment]
@bikeymouse as per coincidence a new version of DSMR Reader has been released Yesterday. I tested the new Docker image and I think it's working fine now. I`m thinking of adding some tests so this won't happen again in the future.

**Comment by bikeymouse** [comment]
Just checked with the new image, and everything works as expected. Thanks, great work!
