### ISSUE TITLE
Postgres 12 support

### ISSUE THREAD

**Issue by jorkzijlstra** [xirixiz/dsmr-reader-docker#75]
I have been doing some testing with Postgres 12. Everything seems to run except for the Database backup. The 11.5 client tools can talk with a 12 database (e.g. pg_dump doesn't work).

Not sure though if the postgresql-client packave is already available for Postgres 12.

**Comment by xirixiz** [comment]
Hi Jork, the postgresql-client package for Postgres 12 isn't available yet on released Alpine Docker images (except for Edge, but I don't recommend using that Docker image).

https://pkgs.alpinelinux.org/packages?name=postgresql-client&branch=v3.10&repo=main&arch=x86_64

However, I suppose release 12 will be added soon of the postgresql-client package.

**Comment by jorkzijlstra** [comment]
Zo een vermoeden had ik al, bedankt voor het checken

**Comment by RezzZ** [comment]
ahh ik was ook al van plan een issue aan te maken voor support voor pg12. het is niet zo simpel als het pg_dump file uit de postgres12 alpine container te kopiëren naar de dsmr container?

**Comment by jorkzijlstra** [comment]
@RezzZ Bij het bouwen van deze container wordt er gewoon een installatie stap gedaan van de client: https://github.com/xirixiz/dsmr-reader-docker/blob/master/Dockerfile.cross#L33

Er wordt aan de client gewerkt (RC) maar deze is gewoon nog niet uitgebracht als versie: https://pkgs.alpinelinux.org/packages?name=postgresql-client&branch=edge&repo=main&arch=aarch64

**Comment by xirixiz** [comment]
@jorkzijlstra Wat ik al eerder aangaf, dat is alleen in de Edge versie van Alpine, en die wil ik niet gebruiken. Dat is namelijk een development tree, en die kan unstable zijn.

**Comment by jorkzijlstra** [comment]
@xirixiz dat is ook wat ik probeerde aan te geven. 

Heb genoeg ervaring met Beta / RC versies om te weten dat je die ten aller tijden moet vermijden tenzij je eventueel wil mee werken aan het project, gezien je waarschijnlijk wel issues tegen komt.

In dit geval dus gewoon niet doen :)

**Comment by RezzZ** [comment]
duidelijk! dank voor de uitleg. nog even wachten op de release van de client dus.

**Comment by HellStorm666** [comment]
Onderhand ruim een jaar later, maar ik loop helaas nog tegen deze foutmelding aan.
Is hier al een oplossing voor?

**Comment by xirixiz** [comment]
Voor PG12 werkt het allemaal (gebruik ik zelf ook nu). Gebruik je de laatste Docker images van DSMR Reader , die is namelijk op Alpine 3.12 gebasseeerd waar de PG12 client package beschikbaar voor is.

https://pkgs.alpinelinux.org/packages?name=postgresql-client&branch=v3.12&repo=main&arch=aarch64

Voor PG13 is er nog geen client beschikbaar in Alpine.

**Comment by HellStorm666** [comment]
Sorry, zie het inderdaad.
Postgres nu gezet naar postgres:12.3-alpine en nog is proberen ;)

**Comment by sweetpants** [comment]
Same issue here: Just installed latest (Docker) Postgres Database ((Debian 13.0-1.pgdg100+1) but (Docker) DSMR still uses pg_dump 12.4 client version. Are there plans to update pg_dump again?

**Comment by xirixiz** [comment]
...didn't read through this post I guess *sigh*
