### ISSUE TITLE
Feature: add support for plugins in settings.py

### ISSUE THREAD

**Issue by jorkzijlstra** [xirixiz/dsmr-reader-docker#76]
I would like to add plugins to the settings.py.

As described here: https://dsmr-reader.readthedocs.io/en/latest/plugins.html#example-3-forwarding-raw-telegram-data-to-another-instance-by-api

The plugin itself can be added via a volume mount, however the array of which plugin to load needs to be added to the settings.py

**Comment by jorkzijlstra** [comment]
I now see that needs to be added to the dsmr reader software.

I just created a PR for the [DSMRREADER_LOGLEVEL](https://github.com/dennissiemensma/dsmr-reader/pull/749). Once that has been proved to be ok Ill try to create one for the plugins

**Comment by jorkzijlstra** [comment]
For now closing it

**Comment by xirixiz** [comment]
Thanks! Sorry for the late reply. I was busy working on some other project for Home Assistant (afvaldienst/afvalwijzer component).
