### ISSUE TITLE
dsmr_mqtt does not seem to be very stable

### ISSUE THREAD

**Issue by pimvullers** [xirixiz/dsmr-reader-docker#84]
Hi, 

I just managed to get DSMR Reader running on my QNAP NAS using your docker configuration. The docker instance shows up nicely in the Container Station interface of the NAS. However, in the Console view I see quite some messages like these:
```
2019-11-07 20:54:47,943 INFO spawned: 'dsmr_mqtt' with pid 201                                                                                                                                                                 
2019-11-07 20:54:48,944 INFO success: dsmr_mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                  
2019-11-07 20:55:49,313 INFO exited: dsmr_mqtt (exit status 1; not expected)                                                                                                                                                   
2019-11-07 20:55:49,399 INFO spawned: 'dsmr_mqtt' with pid 203                                                                                                                                                                 
2019-11-07 20:55:50,631 INFO success: dsmr_mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                  
2019-11-07 20:56:50,902 INFO exited: dsmr_mqtt (exit status 1; not expected)                                                                                                                                                   
2019-11-07 20:56:51,608 INFO spawned: 'dsmr_mqtt' with pid 205
```

Overall it still seems to work, but this doesn't look like OK behavior to me. Any ideas what could cause this, and whether it can be solved?

**Comment by RezzZ** [comment]
what hardware are you using? I recently migrated most of my containers to a more powerfull i7 server and don't find any errors like that since my last upgrade 24 hours ago

**Comment by EvtK** [comment]
I can report the same problem. Just installed the latest version of the dsmr docker, running it on a Synology DS218+ machine. MQTT seems to work, but the log is full of this type of errors.

**Comment by xirixiz** [comment]
If you don't use mqtt, then it's possible to disable it. Check the variable here.
```https://github.com/xirixiz/dsmr-reader-docker``

Please let me know if this resolves the issue, otherwise I`ll look into it.

**Comment by pimvullers** [comment]
So the MQTT integration is optional, and only needed for potential external services. I thought that this was used internally as well to queue the readings for processing etc

**Comment by xirixiz** [comment]
I have disabled it as well and everything is working fine and without any mqtt related errors.

**Comment by 2Gapps** [comment]
> Hi,
> 
> I just managed to get DSMR Reader running on my QNAP NAS using your docker configuration. The docker instance shows up nicely in the Container Station interface of the NAS. However, in the Console view I see quite some messages like these:
> 
> ```
> 2019-11-07 20:54:47,943 INFO spawned: 'dsmr_mqtt' with pid 201                                                                                                                                                                 
> 2019-11-07 20:54:48,944 INFO success: dsmr_mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                  
> 2019-11-07 20:55:49,313 INFO exited: dsmr_mqtt (exit status 1; not expected)                                                                                                                                                   
> 2019-11-07 20:55:49,399 INFO spawned: 'dsmr_mqtt' with pid 203                                                                                                                                                                 
> 2019-11-07 20:55:50,631 INFO success: dsmr_mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                  
> 2019-11-07 20:56:50,902 INFO exited: dsmr_mqtt (exit status 1; not expected)                                                                                                                                                   
> 2019-11-07 20:56:51,608 INFO spawned: 'dsmr_mqtt' with pid 205
> ```
> 
> Overall it still seems to work, but this doesn't look like OK behavior to me. Any ideas what could cause this, and whether it can be solved?

Hi @pimvullers, Can you please tell me how you have installed the doker? I have tried to install it in a QNAP NAS  (TS-321P2 -ARM32) but I always get this error message.

[ INFO ] Checking if the DSMR web credential variables have been set...                                                                                                              
[ INFO ] Fixing /dev/ttyUSB* security...                                                                                                                                             
[ INFO ] Removing existing PID files...                                                                                                                                              
[ INFO ] Creating log directory...                                                                                                                                                   
[ INFO ] Verifying if Postgres in running...                                                                                                                                         
[ FAIL ] Could not connect to database server. Aborting...    

![20200608_chrome_633](https://user-images.githubusercontent.com/7052267/84071184-97e55380-a9cd-11ea-881c-112877a06064.png)
![20200608_chrome_635](https://user-images.githubusercontent.com/7052267/84071182-974cbd00-a9cd-11ea-85a4-676056f4c4fc.png)
![20200608_chrome_634](https://user-images.githubusercontent.com/7052267/84071183-97e55380-a9cd-11ea-85ba-20bf7bcb6e2e.png)
![20200608_chrome_632](https://user-images.githubusercontent.com/7052267/84071185-97e55380-a9cd-11ea-87aa-76b5bc3b4b7a.png)

**Comment by pimvullers** [comment]
I have a TS-473, x86_64-based NAS. I have PostgreSQL app installed through App Center, this is the database that your instance cannot connect to.
I have the docker container started using a script (it gives a better control than the web interface, it also ensures an up-to-date image):
```
[~] # cat /share/Container/docker_run_dsmr.sh
docker stop dsmr
docker rm dsmr
docker image pull xirixiz/dsmr-reader-docker:latest
#docker run -d --name dsmr --restart always -p 7777:80 -p 7779:443 -e TZ=Europe/                                                                                                                                                             Amsterdam --network=bridge -e DB_HOST=10.0.3.1 -e DB_USER=dsmrreader -e DB_PASS=                                                                                                                                                             dsmrreader -e VIRTUAL_HOST=localhost --device /dev/ttyUSB0:/dev/ttyUSB0 xirixiz/                                                                                                                                                             dsmr-reader-docker:latest

docker run \
  --name=dsmr \
  --restart=always \
  --detach=true \
  --network=bridge \
  --publish 0.0.0.0:7777:80 \
  --publish 0.0.0.0:7779:443 \
  --device /dev/ttyUSB0:/dev/ttyUSB0 \
  --tty \
  --env="TZ=Europe/Amsterdam" \
  --env="DSMR_USER=admin" \
  --env="DSMR_EMAIL=dsmr@vullersmail.nl" \
  --env="DSMR_PASSWORD=***" \
  --env="DB_HOST=10.0.3.1" \
  --env="DB_PORT=5432" \
  --env="DB_NAME=dsmrreader" \
  --env="DB_USER=dsmrreader" \
  --env="DB_PASS=***" \
  --env="SD_USER=root" \
  --env="SD_GROUP=root" \
  --env="SD_LOGLEVEL=info" \
  --env="SD_AUTOSTART_DATALOGGER=true" \
  --env="SD_AUTORESTART_DATALOGGER=true" \
  --env="SD_AUTOSTART_BACKEND=true" \
  --env="SD_AUTORESTART_BACKEND=true" \
  --env="SD_AUTOSTART_MQTT=false" \
  --env="SD_AUTORESTART_MQTT=false" \
  xirixiz/dsmr-reader-docker:latest
```
DB_HOST (10.0.3.1) is the NAS itself (i.e. the PostgreSQL package), and the IP is the one from the Container Network (lxcbr0) interface.

Hope this helps.
