### ISSUE TITLE
Backup creation failed with alternat DB_PORT

### ISSUE THREAD

**Issue by sanderplug** [xirixiz/dsmr-reader-docker#85]
Hi, getting `Backup creation failed, please check the dsmr_backend logfile.` with DB_PORT set to 55432, instead of the normal 5432 value. My postgres database is running on my synology where port 5432 was already occupied. I had changed the port in the docker configuration to 55432 and dsmr-reader is working fine.

However I can not make backups, the following message is shown in the UI of dsmr reader: `"Backup creation failed, please check the dsmr_backend logfile. "` 

In the dsmr_backend logfile the following is shown:
```
[2019-11-17 11:03:46,275] CRITICAL  - Unexpected exit code (1) for backup: b'could not find a "pg_dump" to execute\npg_dump: [archiver (db)] connection to
 database "dsmrreader" failed: could not connect to server: Connection refused\n\tIs the server running on host "10.0.0.240" and accepting\n\tTCP/IP conne
ctions on port 5432?\n'                                                                                                                                   
[2019-11-17 11:03:46,308] ERROR    b'could not find a "pg_dump" to execute\npg_dump: [archiver (db)] connection to database "dsmrreader" failed: could not
 connect to server: Connection refused\n\tIs the server running on host "10.0.0.240" and accepting\n\tTCP/IP connections on port 5432?\n'                 
NoneType: None '  
```
Could it be that the DB_PORT value is not populated to the backup routines and how can this be fixed?

**Comment by EvtK** [comment]
checking in to report some sort of the same issue. I did not change the port value, but I do have the same error in my dashboard.

Where did you find this in the logs exactly?

**Comment by sanderplug** [comment]
I think I found the logs in the /tmp directory.

**Comment by xirixiz** [comment]
I`ll verify the backup strategy this weekend

**Comment by xirixiz** [comment]
Do you have the backups folder mounted with the correct security settings?
--volume ${SOME_LOCAL_FOLDER}:/dsmr/backups:rw

Can you run:
docker exec -t dsmrdb pg_dumpall -c -U dsmrreader > dsmrreader.sql
Can you see the data in the exported file then?

I don't have any errors using the default port, so I think the issue you two have are different to eachother. I`ll look into the port issue first. Within the docker container, you're still using 5432?

**Comment by EvtK** [comment]
In the end my problem turned out having picked 'latest' for the postgres container image, while is should have picked 11.6 alpine. Version 12 is not yet compatible.

I found a way to get debugging information by tweaking the debug settings in the environment settings. Though I was never able to build up a log file in dsmr_backed. I watched the output receiving in the terminal in synology docker view.

**Comment by Xitro01** [comment]
Still an issue, when will there be support voor V12 of postgres?

**Comment by xirixiz** [comment]
There is, not PG13. Be more clear please. What is it you're trying to achieve.

**Comment by Xitro01** [comment]
> There is, not PG13. Be more clear please. What is it you're trying to achieve.

I would like to have my daily back-ups, but they're not working. Got the exact same issue as above.

**Comment by rogierlommers** [comment]
Same here; started about 10/15 days ago.
It used to run fine (I'm using postgres 12:latest).

**Comment by xirixiz** [comment]
Ok, that's something I can look at. If you're using PG12 and a recent DSMR Docker image, the backup should be running fine. I`ll reopen this issue and verify some things.

**Comment by Xitro01** [comment]
I'm running PG_VERSION | 13.0-1.pgdg100+1 (which is postgres:latest).
I probably have to downgrade to 12, to make it work, right?
Any idea when 13 will be supported?

**Comment by xirixiz** [comment]
Yes, indeed. PG13 isn't supported in Alpine. Not sure when it will be supported.

You can verify it here (edge branch selected in the url below):
https://pkgs.alpinelinux.org/packages?name=postgres*&branch=edge

**Comment by xirixiz** [comment]
@rogierlommers it must be something else, I just tested with PG12 and the backup is working fine. I also see backups in the mounted folder. 

![image](https://user-images.githubusercontent.com/11210639/97905567-7d2bc680-1d42-11eb-8b25-0ca28f3ea6e1.png)

Do you mount a volume/folder with the DSMR container? I have something like this configured:
```
--volume ${DOCKER_DATA}/dsmr/backups:/dsmr/backups:rw \
```

**Comment by rogierlommers** [comment]
@xirixiz , stupid question, but when I get this: `Backup creation failed, please check the dsmr_backend logfile.`
Where exactly (in the container) can I see these logfiles? because the tailing the docker container (`dockter tail -f dsmr`) does not privde any additional info.

**Comment by xirixiz** [comment]
It shows the location of the logfiles on container startup.
![image](https://user-images.githubusercontent.com/11210639/97907547-bb76b500-1d45-11eb-9ea9-7074159bb685.png)

**Comment by rogierlommers** [comment]
Damn; must have overseen that. Sorry.
So, the backend logs shows a bunch of these lines:

```
[2020-11-02 19:58:21,694] CRITICAL  - Unexpected exit code (1) for backup: b'could not find a "pg_dump" to execute\npg_dump: error: no matching tables were found\n'
[2020-11-02 19:58:21,697] ERROR    (OSError) dsmr_backup.services.backup.run errored: b'could not find a "pg_dump" to execute\npg_dump: error: no matching tables were found\n'
[2020-11-02 19:58:43,048] CRITICAL  - Unexpected exit code (1) for backup: b'could not find a "pg_dump" to execute\npg_dump: error: no matching tables were found\n'
[2020-11-02 19:58:43,051] ERROR    (OSError) dsmr_backup.services.email.run errored: b'could not find a "pg_dump" to execute\npg_dump: error: no matching tables were found\n'
[2020-11-02 19:58:52,222] CRITICAL  - Unexpected exit code (1) for backup: b'could not find a "pg_dump" to execute\npg_dump: error: no matching tables were found\n'
[2020-11-02 19:58:52,225] ERROR    (OSError) dsmr_backup.services.backup.run errored: b'could not find a "pg_dump" to execute\npg_dump: error: no matching tables were found\n'
```

**Comment by rogierlommers** [comment]
How exactly does the backup mechanism work?

Are you shelling out to use pg_dump? That command is inside the postgres container, right? How do you get from the dsmr container to the postgres container? I don't really get that part.

**Comment by xirixiz** [comment]
Ahh, ofcourse, that is most probably because of the different schema you are using which is currently not supported with DSMR Reader 😖.

**Comment by rogierlommers** [comment]
I indeed remembered a few seconds ago.
You know what... I'll switch back to dedicated postgres containers for all my stuff.

**Comment by rogierlommers** [comment]
fuck these resources... :).. give me reasons to but a heavier server in my meterkast ;).

**Comment by xirixiz** [comment]
Or you just use the script I mentioned earlier, stop dsmr, take a backup, start dsmr

**Comment by rogierlommers** [comment]
> Or you just use the script I mentioned earlier, stop dsmr, take a backup, start dsmr

Well, for some reason I can't disable the backup mechanism. If you "uncheck" it in the settings page; then I still get these errors.

**Comment by xirixiz** [comment]
postgres, not much of a resource, but I agree it would be nicer to merge these rather small services/datbases.

**Comment by xirixiz** [comment]
> > Or you just use the script I mentioned earlier, stop dsmr, take a backup, start dsmr
> 
> Well, for some reason I can't disable the backup mechanism. If you "uncheck" it in the settings page; then I still get these errors.

Ah, that's something for Dennis to fix 👍
