### ISSUE TITLE
update to latest version of dsmr?

### ISSUE THREAD

**Issue by wivaku** [xirixiz/dsmr-reader-docker#88]
Is there a way to update to the latest version of dsmr-reader from inside the docker container?
Or do we need to wait for updated Docker image?
I am getting notifications in the app that there is a new version.

**Comment by xirixiz** [comment]
Hi, I`m currenty updating the image. However, it would be nice to have a dynamic image as well...download the latest version within the container at startup....

I`ll see what I can do.

**Comment by xirixiz** [comment]
Branch created, need to test it first. Will do that soon. https://github.com/xirixiz/dsmr-reader-docker/tree/dsmr-update-on-startup

In the future you can provide env var if you'd like to update on startup 👍

**Comment by jghaanstra** [comment]
Why was this ticket closed? It seems to be a relevant feature request that has not been fulfilled yet. I'd like to see this as well.

**Comment by xirixiz** [comment]
I'm managing this on my own and don't have enough time to create such an image for multiple architectures. If anyone can contribute, feel free to fork and create a pull request 👍

**Comment by jghaanstra** [comment]
Ok, clear. I unfortunately lack the skills to do that myself so I'm hoping that someone else can pick that up.

Enjoy the coffee ;-)

**Comment by xirixiz** [comment]
Hmm, I just checked it quickly. As I moved over to a different image creation meganism, it might have become more easy. I`ll check it once again myself this weekend.

**Comment by xirixiz** [comment]
Oke, created a test image per architecture. You may try to use the DYNUP-<arch> release. Can you try if it's working?

**Comment by jghaanstra** [comment]
I have`DYNUP-arm64v8` on my Synology DS216+II tried but the container keeps restarting with the following error: `standard_init_linux.go:222: exec user process caused "exec format error"`

**Comment by jghaanstra** [comment]
I just pulled `DYNUP-amd64` and started it up with my existing Postgres database. Works fine. Do I need to test more?
