### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by willumpie82** [xirixiz/dsmr-reader-docker#89]
Hi, 

I'm trying to deploy dsmr-reader-docker on my rpi4 running raspbian buster. 
I'm already running pihole and portainer docker succesfully.

I tried installation via the docker-compose file, the containers get created but won't start
error in the log "standard_init_linux.go:211: exec user process caused "exec format error"

then I tried to build the image on the pi with the following cmd
`./update_images.sh --local --arch arm64v8`

```
Step 22/31 : RUN ["/usr/bin/qemu-aarch64-static", "/bin/sh", "-c",      "apk --update add --no-cache       bash       curl       nginx       openssl       postgresql-client       tzdata       supervisor"]
 ---> Running in 80d959403e90
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/usr/bin/qemu-aarch64-static /bin/sh -c apk --update add --no-cache       bash       curl       nginx       openssl       postgresql-client       tzdata       supervisor' returned a non-zero code: 1
```
Full output
[https://pastebin.com/raw/jS7uni4s](url)

It seems that qemu is not happy, any clues?

**Comment by bikeymouse** [comment]
You are using the 64-bit image  (the default one), that does not run on an Rpi. That needs 32bits images (64 is not yet suppported even if Raspbian is 64-bit). 
Use eg. the tag arm32v6-latest to get the 32-bit version. 
See Docker hub for all the versions.

**Comment by willumpie82** [comment]
thanks for the reply, now it works.

I modified the compose file with `image: xirixiz/dsmr-reader-docker:arm32v6-latest`

How come Docker does not detect the correct arch?
