### ISSUE TITLE
how to use 3x branch?

### ISSUE THREAD

**Issue by remb0** [xirixiz/dsmr-reader-docker#92]
I use the compose version of xirixiz and when I wanted to update I recreate the stack from portainer, portainer then downloaded the latest image.
But the update to the 3.x branch works different. 

What's the procedure now. I'm not sure.

Kind regards,

remco

**Comment by alexswart** [comment]
you have to ad tag V3.1.0

**Comment by remb0** [comment]
don't know how and where.  can you tell me?

**Comment by maikvitesse** [comment]
You can do it like this:

![Image](https://i.imgur.com/5vD99WW.png)

The only thing i'm wondering is if you can just upgrade without compatibility issues with your database, anyone knows?

**Comment by search-tool** [comment]
Did a DB backup and pulled image with tag xirixiz/dsmr-reader-docker:arm32v6-v3.1.0 and everything is working fine.
i believe its "just" a python and django upgrade, DB stuff didnt change.

**Comment by search-tool** [comment]
maybe @xirixiz can make a arm32v6-v3 tag so you can fetch always the latest v3 image

**Comment by maikvitesse** [comment]
thanks @search-tool 
Works perfectly indeed.
