### ISSUE TITLE
arm32v6 build op x86_64 ubuntu: exec format error 127

### ISSUE THREAD

**Issue by tomkooij** [xirixiz/dsmr-reader-docker#93]
Ik probeerde zojuist de nieuwste versie lokaal te builden. Dat doe ik op mijn ubuntu (x86) machine, want veel sneller dan raspberry pi. Het installeren van de depencies van dsmr duurt eeuwen op mijn raspberry pi (psycog2 builden vanaf source duurt lang)

Dus: 
 * Host: Ubuntu 16.04 LTS x86_64:
 * target: arm32v6 (raspberry pi)

```
./update_images.sh --local --arch arm32v6
[ INFO ] Generating local Docker image for arm32v6

[...KNIP...]

Removing intermediate container d4f09d86c833
 ---> 43f5e22bc447
Step 22/31 : RUN ["/usr/bin/qemu-arm-static", "/bin/sh", "-c",      "apk --update add --no-cache       bash       curl       nginx       openssl       postgresql-client       tzdata       supervisor"]
 ---> Running in 059b99890f4b
/bin/sh: apk: Exec format error
The command '/usr/bin/qemu-arm-static /bin/sh -c apk --update add --no-cache       bash       curl       nginx       openssl       postgresql-client       tzdata       supervisor' returned a non-zero code: 126

```

Als ik in het docker image kijk, dan gaat het mis omdat het prefixen met `/usr/bin/qemu-arm-static` niet voldoende is. `/bin/sh` of `apk` probeert weer een ander proces te forken en de kernel denkt dat dit `x86_64` zou moeten zijn, terwijl het `arm32v6` is.

Oplossing is het installeren van qemu op de Ubuntu host:

```
sudo apt-get install qemu-user-static binfmt-support
sudo update-binfmts --enable
```

(Nu is het hele prefixen van /usr/bin/qemu-arm-static helemaal niet meer nodig vermoed ik, maar dat heb ik niet getest)

Is dit iets voor een PR/docs/wiki? Is er documentatie voor het zelf bouwen van de docker images?

**Comment by tomkooij** [comment]
Ik heb het nu wel getest en inderdaad: `usr/bin/qemu-arm-static` is overbodig (en het werkt niet) op mijn ubuntu host.

Ik heb de azure-pipelines niet in detail bekeken, maar dat is ook ubuntu en het lijkt mij dat dat het QEMU prefixen weg kan. Dat vereenvoudigd de build aanzienlijk.

**Comment by xirixiz** [comment]
Thanks! Dat ga ik testen! Ik heb daar in het verleden veel tijd aan besteed, en het koste veel moeite om voor andere architectuur een fatsoenlijke image te bouwen. Maar het zou inderdaad mooi zijn wanneer het gewoon kan worden weggelaten.

**Comment by tomkooij** [comment]
@xirixiz : Te vroeg gejuigd helaas... Ik probeer het nu in een fork. En het werkt toch niet... (Dit zou niet door het prefixen met `/usr/bin/qemu-arm-static` moeten komen... Maar ja, voorlopig werkt het met de prefix WEL en zonder NIET.

Anyway. Als het werkt stuur ik zeker een PR.
