### ISSUE TITLE
Missing tag arm64v8-latest

### ISSUE THREAD

**Issue by jorkzijlstra** [xirixiz/dsmr-reader-docker#98]
Hey, I mostly using the arm64v8-latest tag and noticed that since the last release its wasn't updated.

Is this on purpose and do I need to update my docker-compose file each release now?

**Comment by xirixiz** [comment]
Hey Jork, sorry, I stopped using the latest tags behind an architecture. Please start using:
`` xirixiz/dsmr-reader-docker:arm64v8``` ...which is latest. Sorry for the inconvenience.
