### ISSUE TITLE
Pulling docker image failes (arm32v6)

### ISSUE THREAD

**Issue by frankforpresident** [xirixiz/dsmr-reader-docker#99]
I'm unable to pull the image xirixiz/dsmr-reader-docker:arm32v6-latest from docker hub. I actually tried to update all my images but this one failed.

Pulling dsmr        ... error                                                                                                                                               
ERROR: for dsmr  manifest for xirixiz/dsmr-reader-docker:arm32v6-latest not found
ERROR: manifest for xirixiz/dsmr-reader-docker:arm32v6-latest not found

**Comment by frankforpresident** [comment]
changing the tag to arm32v6. I guess this one replaces arm32v6-latest?

**Comment by xirixiz** [comment]
https://github.com/xirixiz/dsmr-reader-docker/issues/98
